### PR TITLE
Rebasing Btag/Jet type modification to 14_0_0_pre3

### PR DESCRIPTION
**Pull request by Duchstf**
Discussion in #1198

### CODE REVIEW

**Comment by Duchstf** [comment]
@aloeliger Sorry for the delay again! I feel really bad about this :(

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by Duchstf** [comment]
I don't think this file was changed at all in this PR.

**Comment by epalencia** [comment]
Yes, that is correct, don't worry about it.

**Comment by Duchstf** [comment]
@epalencia so can this be merged now?

**Comment by aloeliger** [comment]
@Duchstf We'll go ahead and merge this now for v6. If there isn't already a PR for this to central, please go ahead and make it.

**Pull request merged**
