### PR TITLE
Calostage2eg layer1 update

### PR DESCRIPTION
**Pull request by tstreble**
@mulhearn This PR includes various updates to the Layer-2 EG algorithm, including new LUTs designed to be used on top of Layer-1 tower corrections.

### CODE REVIEW

**Comment by mulhearn** [comment]
But will this break workflows which do not use bitwise layer1 (our current default)?

**Comment by tstreble** [comment]
@mulhearn 
This is only to be used with bitwise layer1 and must not be used with the current default.
As long as the default stays without bitwise layer1, I think there is no point in including this PR.

**Comment by mulhearn** [comment]
Thanks for clarifying.

**Comment by rekovic** [comment]
@mulhearn Can't we not merge this and then turn off the bitwise layer1 ? That way we have these changes when we turn it on...or am I missing something?

**Comment by tstreble** [comment]
@rekovic 
This changes must not be used with bitwise layer 1 turned off.
It includes update of EG calibration + isolation which are not adapted to the current default with bitwise layer1 turned off.

**Comment by rekovic** [comment]
@tstreble I see. Thanks.

**Pull request merged**
