### PR TITLE
emulator for Phase-2 GCT calo jets and taus

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:

- adds a data format: l1tp2::Phase2L1CaloJetCollection
- depends on PR https://github.com/cms-l1t-offline/cmssw/pull/1069 for input GCT towers collection (ECAL clusters + HCAL towers)
- refer to presentation here: https://indico.cern.ch/event/1288569/timetable/?view=standard#68-calorimeter-trigger-firmwar
- not a backport

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found issues with the headers. These issues likely arise from improper build files.

The following is the stderr of the header checking:
```
src/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloJetEmulator.h:489:27: error: 'l1tp2' has not been declared
  489 |   inline bool compareByEt(l1tp2::Phase2L1CaloJet i, l1tp2::Phase2L1CaloJet j) { return (i.jetEt() > j.jetEt()); };
      |                           ^~~~~
src/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloJetEmulator.h:489:53: error: 'l1tp2' has not been declared
  489 |   inline bool compareByEt(l1tp2::Phase2L1CaloJet i, l1tp2::Phase2L1CaloJet j) { return (i.jetEt() > j.jetEt()); };
      |                                                     ^~~~~
src/L1Trigger/L1CaloTrigger/interface/Phase2L1CaloJetEmulator.h:489:77: error: expression list treated as compound expression in initializer [-fpermissive]
  489 |   inline bool compareByEt(l1tp2::Phase2L1CaloJet i, l1tp2::Phase2L1CaloJet j) { return (i.jetEt() > j.jetEt()); };
      |                                                                             ^
gmake: *** [config/SCRAM/GMake/Makefile.rules:1721: tmp/slc7_amd64_gcc10/src/L1Trigger/L1CaloTrigger/src/L1TriggerL1CaloTrigger/Phase2L1CaloJetEmulator.h.chk_header] Error 1
gmake: Target 'check-headers' not remade because of errors.

```
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`2`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 2 files that did not meet formatting requirements:
 - L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc
 - L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloJetEmulator.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@pallabidas Could you fix the header issues that script found? And fix the formatting problems in the CaloJets?

**Comment by pallabidas** [comment]
`L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc` is not a file that I added, should I still format it?

**Comment by aloeliger** [comment]
No, don't worry about that. Stephanie snuck in an unformatted file.

**Comment by aloeliger** [comment]
But if you changed it it probably would match central better.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@pallabidas Please rebase this to CMSSW-13_3_0_pre3, and we will merge it into the new IB under our new scheme. Then make a PR from that to the main branch.

**Comment by epalencia** [comment]
This PR has been rebased to 13_3_0 (https://github.com/cms-l1t-offline/cmssw/pull/1174), I'm closing it.

**Pull request closed without merging**
