### PR TITLE
More small fixes to jets & sums saturation

### PR DESCRIPTION
**Pull request by bundocka**
Now HT, MHT saturate in the same way as MET corresponding to firmware update next week. 
Update plotting scripts.

### CODE REVIEW

**Comment by rekovic** [comment]
@bundocka 
Clarification before merging:
The last commit reverts `caloStage2Params_2017_v1_7_cfi.py`.  
`2017_v1_7` is not the default configuration. What is the point of this change?

**Comment by bundocka** [comment]
When running the hw/emu comparisons, I changed the eta restriction on HT and MHT as that was programmed differently when running the tests. All I did here was revert this change, so that caloStage2Params_2017_v1_7_cfi.py is unmodified when merging this PR...

**Comment by rekovic** [comment]
@bundocka  OK.  So the file stayed unchanged, after the PR.
Thanks

**Comment by rekovic** [comment]
Rebased and merged to l1t-integration-CMSSW_9_2_4.
Tagged as `l1t-integration-v96.13`

**Pull request closed without merging**
