### PR TITLE
Changing handling of track addresses in RegionalMuonCand

### PR DESCRIPTION
**Pull request by jlingema**
This moves the track-address from an integer to a map: This has the benefit of making access to the sub-addresses (for different stations / rings) easier / more explicit for the uGMT cancel-out. To avoid having to keep integer / map in synch, we drop the integer (it is of course still implicitly contained in the m_dataword). 

Can you please have a look if you have any objections and if we decide to go with this, the implementation in the track-finders, @akalinow, @mrcarver, @gflouris, @mulhearn?

If everybody is fine with this, we still have to adapt the unpacker, @thomreis.

### CODE REVIEW

**Comment by akalinow** [comment]
This is fine with me.

**Comment by gflouris** [comment]
This is also fine with me.

**Comment by thomreis** [comment]
I have made the changes to the RawDigiTranslator. The correct widths and shifts for the subAddresses need to be set still.

**Comment by akalinow** [comment]
What is the status of this request? I would like to put my latest OMTF updates on top of it. Could you please merge it with the main branch?

**Comment by mulhearn** [comment]
FYI:  any collaborator can merge it... no need to wait for me!

**Comment by jlingema** [comment]
I was waiting for comments by the EMTF folks. After an email exchange, we realised that their use-case is not covered 100%. We can, however, merge this and extend the EMTF enum in another PR, if it is holding you up.

**Comment by mulhearn** [comment]
Oh, sorry, looked to me like it was all clear.  I can revert the merge if necessary, but it seems like maybe we should go ahead...

**Comment by jlingema** [comment]
For me it's fine to merge it and reiterate after some discussion with EMTF ppl. Especially, if this is holding Artur up.. So I'll go ahead and merge.

**Pull request merged**
