### PR TITLE
L1t ntuples cmssw 8 0 0 pre6

### PR DESCRIPTION
**Pull request by apana**
Changes for L1Ntuples package.
- Add L1EventTree to standard production
- Fix some InputTags, also change InputTag defaults for stage1 running
- Use JEC from GlobalTag instead of local sqlite file

### CODE REVIEW

**Comment by jimbrooke** [comment]
@apana you could also remove the l1Tree from L1NtupleRAW_cff, since this includes only legacy systems and takes up a lot of space.  It was useful previously for the Event tree, but now that is made separately we don't need it.

**Comment by jimbrooke** [comment]
You might also want this
https://github.com/cms-l1t-offline/cmssw/commit/8b948b95accc4fc376856d42c2e1bc5a6bad18a0

**Comment by jimbrooke** [comment]
Actually, we could probably include all these commits from calostage2 dev branch
ab1a7f7738fae12c989ba933d5ea2d5a9c66bda6
7164084e2fb75ab0b8d6d36181d43d9a57e91311
2dd10433a5aac867f453a85ba442a868a808a585
6cd6362b3b3937e1db3b0669b3f3a33767ca2547
9789e7c260c450afd29843edaa472d426361c59e

**Comment by apana** [comment]
Hi Jim,

Thanks for going over the PR and for the suggestions. The commits you
listed all look like they should go in.

-Len

**Comment by mulhearn** [comment]
@apana this branch is now merged.  Please check that you are happy with dev-recipe tag l1t-tsg-v1, delete the branch, and close this PR.

If you want to continue work on ntuples, you should simply start fresh from dev-recipe.

**Comment by mulhearn** [comment]
The commits suggested by Jim have all been cherry-picked.

**Comment by rekovic** [comment]
I guess this PR should be closed?

**Pull request closed without merging**
