### PR TITLE
microGMT unpacker

### PR DESCRIPTION
**Pull request by thomreis**
This is the first version of the microGMT unpacker. In order to test it it was necessary to change the bufferDumpToRaw module that was putting a too short AMC header in the event.
I have also fixed a wrong numbering scheme for the links in the RegionalMuonCand.

### CODE REVIEW

**Comment by jimbrooke** [comment]
What CMSSW version is this based on?

Some comments
- problems with buffer dump to raw have been fixed since some time ago, I thought
- naming is inconsistent with other names in this package
- the GMT output collections will need to be shared with GT, as per CaloCollections.  this may mean ALL the src files should be under src/implementations_stage2?  (Matthias?)

**Comment by thomreis** [comment]
This is based on CMSSW_7_6_0_pre4.

For the l1t-muon-CMSSW_7_6_0_pre4 branch the buffer dump to raw problem was not fixed but I found the fix in the l1t-devel-CMSSW_7_5_0_pre5 branch.
Can you be more precise on what you mean that the naming is inconsistent?
I was not sure about if I should put the files in implementations_stage2 so I put them in a separate directory.

**Comment by jlingema** [comment]
> - the GMT output collections will need to be shared with GT, as per CaloCollections. this may mean ALL the src files should be under src/implementations_stage2? (Matthias?)

Doesn't that mean that in the end all unpacker implementations have to end up in `implementations_stage2`? Seeing that the uGMT uses the track-finder collections which use track-segment collections of the TwinMux, etc. (Not saying that this is necessarily a bad thing, just asking if I understand correctly and whether that is what you'd want.)

**Comment by jimbrooke** [comment]
So yes, there are fixes in the 750-pre5 dev branch that we have not pushed to CMSSW, including for the buffer dump module.

Regarding names, we did not use "micro" for the GT.  eg. 
https://github.com/cms-l1t-offline/cmssw/blob/l1t-devel-CMSSW_7_5_0_pre5/EventFilter/L1TRawToDigi/src/implementations_stage2/GTCollections.h

I am not 100% certain that unpackers using shared collections _must_ live in the same src dir.  But if I am right, then yes all stage 2 unpackers using this framework must live in src/implementations_stage2

**Comment by thomreis** [comment]
OK, I have renamed MicroGMT to GMT and put everything in implementations_stage2 and in the stage2 namespace as well.

**Pull request merged**
