### PR TITLE
Phase-2: rewrite L1 Puppi emulator to use ap_fixed types

### PR DESCRIPTION
**Pull request by gpetruc**
The old emulator was written long time ago using ap_uint and implementing bit shifts by hand.
This new version uses ap_fixed types, resulting in cleaner code, and also better agreement with the floating point expectations (roundings are handled better) and the associated firmware is also a bit better as it uses less bits in the accumulation part.

Physics performance is expected to be essentially identical (I'll try to add some comparison plot next week)

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TTrackMatch/plugins/L1TrackJetClustering.h

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by gpetruc** [comment]
I've made a few sanity check plots in https://gpetrucc.web.cern.ch/gpetrucc/drop/plots/l1stage2/pr-1201/ comparing the old and new version of the emulator on 1k TTbar events, showing that there's very little difference in the outputs between the two.

**Comment by gpetruc** [comment]
CMSSW master PR: https://github.com/cms-sw/cmssw/pull/43821

**Comment by gpetruc** [comment]
Hi,
It doesn't make sense to just change the target branch for this PR. 
If the integration branch is now 14_0_0_pre3 I can make a new PR for that instead

**Comment by aloeliger** [comment]
@gpetruc Apologies for the delay in talking to people about this, but you are correct and it is what we were/are going to recommend people do to keep the IB up to date, whether they want to rebase their PR or do whatever else. I'll ask, but I assume you probably don't need instructions to rebase/change your PR?

**Comment by gpetruc** [comment]
Replaced by #1205

**Pull request closed without merging**
