### PR TITLE
Layer1 proper saturation 92X

### PR DESCRIPTION
**Pull request by nsmith-**
This is mainly for discussion and upstream testing since the new integration branch is on 93X.

### CODE REVIEW

**Comment by nsmith-** [comment]
@bundocka this is what the hardware will ultimately do w.r.t. saturation

**Comment by rekovic** [comment]
@nsmith- 
When do we plan to put this in the fw?
We should probably merge this into l1t-integration once the fw change has been made
as to not confuse when re-emulating current data taken without fw change. 
Unless we will track fw version in the emulator. 

MC:
- physics MC production is envisioned with some future CMSSW release,  Sept 2017. This should go in.
- current ongoing effort to finalise release for MC production with 92X does not have trigger as the main
objective.

**Comment by nsmith-** [comment]
Its already online at P5
I think its best to make a direct PR to cmssw, and a backport
There is a firmware version switch in the emulator configuration

**Comment by rekovic** [comment]
@nsmith- 
OK. Thanks.
Can be merged in l1t-integration as well.

**Pull request merged**
