### PR TITLE
Menu ntupler updates + fixing tkWord Phi

### PR DESCRIPTION
**Pull request by artlbv**
Updates for the menu ntupler for the 13_1 recipe validation, including the fix of the erroneous TkWord Phi offset.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 13 files that did not meet formatting requirements:
 - DataFormats/L1TParticleFlow/interface/gt_datatypes.h
 - L1Trigger/DTTriggerPhase2/src/MPQualityEnhancerFilter.cc
 - L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
 - L1Trigger/DemonstratorTools/src/codecs_tkjets.cc
 - L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloPFClusterEmulator.cc
 - L1Trigger/L1TNtuples/interface/L1AnalysisPhaseIIStep1DataFormat.h
 - L1Trigger/L1TNtuples/plugins/L1PhaseIITreeStep1Producer.cc
 - L1Trigger/L1TNtuples/src/L1AnalysisPhaseIIStep1.cc
 - L1Trigger/L1TTrackMatch/interface/L1TkEtMissEmuAlgo.h
 - L1Trigger/L1TTrackMatch/plugins/L1TrackerEtMissEmulatorProducer.cc
 - L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
 - L1Trigger/Phase2L1ParticleFlow/plugins/L1NNTauProducer.cc
 - L1Trigger/VertexFinder/src/VertexFinder.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
I don't think the formatting things matter too much here.

**Pull request merged**
