### PR TITLE
Final (ish) changes to EMTF emulator before MC production

### PR DESCRIPTION
**Pull request by abrinke1**
Added sector overlap analysis; emulator now matches FW to > 90%.  Implemented data classes for unpacker, emulator, and DQM as per discussion with Mike.  One remaining item that should be checked is whether the pT assignment as implemented by Mike in PtAssignment.cc contains our latest fixes.  Also Matt may have a few-line fix to PrimitiveConverter_Neighbors.h in the works.

### CODE REVIEW

**Comment by thomreis** [comment]
@abrinke1 the changes to the RegionalMuonRawDigiTranslator are already the final ones?

**Comment by abrinke1** [comment]
Yes, as far as I know ... i.e. the format matches the firmware Alex has on
the EMTF boards now (and the format document he sent around), and he is not
planning any changes.  Unfortunately the EMTF emulator does not yet fill
these fields (although it didn't fill them before, either), but the EMTF
unpacker in this PR does fill them.

Regards,
Andrew

**Comment by rekovic** [comment]
@abrinke1  This does not pass L1T emulation test

<pre>
# test emulate on MC
L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 500 --era Run2_2016 --mc --no_output  --filein=/store/relval/CMSSW_7_6_0_pre7/RelValTTbar_13/GEN-SIM/76X_mcRun2_asymptotic_v9_realBS-v1/00000/0A812333-427C-E511-A80A-0025905964A2.root
----- Begin Fatal Exception 15-May-2016 23:53:58 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'L1simulation_step'
   [2] Calling event method for module L1TMuonEndCapTrackProducer/'simEmtfDigis'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
----- End Fatal Exception -------------------------------------------------
</pre>

Can you please check?

**Comment by abrinke1** [comment]
Added small EMTF fixes theta assignment, pT calculation, and the runtime error.  Sorry about that, an odd transient problem - happened when running on a file once, then you just try cmsRun again and it usually worked.  Thought it was an issue with accessing /store files, turns out it wasn't.

Also, is there a way I can see what files are in L1Trigger/L1TMuon/data/emtf_luts/v_16_02_21/?  The directory seems to be mis-labeled: it should be "v_16_04_21".  If you change the directory name, be sure to edit L1Trigger/L1TMuonEndCap/interface/PtAssignment.h as well.

Best,
Andrew

**Pull request merged**
