### PR TITLE
Phase 2 GTT fix off-by-one error and collection mismatch in L1TrackObjectNtupleMaker

### PR DESCRIPTION
**Pull request by NJManganelli**
Edit note: this is not time-critical, and can be deferred as needed according to AR timeline (but this is adjacent to everything outside the GTT ntuples)

Phase 2 GTT fix off-by-one error and collection mismatch in L1TrackObjectNtupleMaker
#### PR description:

This PR addresses a bug in the L1TrackObjectNtupleMaker for GTT ntuple production (being deprecated in favor of L1Nano, but submitted for posterity), which cross-linked the wrong track indices for the various GTT selected collections.

#### PR validation:

scram b code-checks
scram b code-format
scram b
cmsRun L1TrackObjectNtupleMaker_cfg.py

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This will require a forward-port to master as well

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@NJManganelli This can be merged immediately too. I would suggest merging it with the other minor bug-fixes for PRs to central CMSSW.

**Pull request merged**
