### PR TITLE
use 2nd bit of quality word to define forward

### PR DESCRIPTION
**Pull request by harmonicoscillator**
update JetFinderMethods and GCT converter to use new forward definition

### CODE REVIEW

**Comment by harmonicoscillator** [comment]
This supersedes https://github.com/cms-l1t-offline/cmssw/pull/11

**Comment by harmonicoscillator** [comment]
@jimbrooke @mulhearn @kalanand @apana 

This uses the second bit of the quality word to define forward for Stage1Layer2 jets. I hope that this meets everyone's criteria and doesn't step on the unpacker's toes. Let me know if you spot any problems.

**Comment by mulhearn** [comment]
Looks good.

**Comment by harmonicoscillator** [comment]
Oops, accidentally merged this. I'll leave as-is unless we have problems.

**Pull request merged**
