### PR TITLE
Gkaratha/twinmux emulator 3step process

### PR DESCRIPTION
**Pull request by gkaratha**
@thomreis @rekovic ,

Dear all,

So I addressed most of the comments. I used everywhere possible smart pointers, change the names of files check spaces removed tabs added comments. I tried to implement everything. The code compiles and runs.

### CODE REVIEW

**Comment by rekovic** [comment]
@gkaratha 
Thanks.  I will check/test it.

**Comment by thomreis** [comment]
@gkaratha 
This PR looks exactly like the PR #589 . None of my comments there have been addressed as is seems. You might have forgotten a commit.

**Comment by thomreis** [comment]
@gkaratha please close this if it is superseded by #612

**Comment by thomreis** [comment]
Closing this.

**Pull request closed without merging**
