### PR TITLE
Add Correlator Layer-2 e/g objects to the Phase-2 event content (12.5.X)

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

This PR adds the Correlator Layer-2 e/g products (`TkElectron` and `TkEM` collections) to the event content.
These are produced by the emulator for GT (and menu studies) consumption.
The corresponding task is already in the configuration.

The corresponding PR to `master` is: #41021

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!

**Comment by aloeliger** [comment]
@cerminar thanks for opening this synchronization PR. Is this urgent to be merged? If you don't mind, I'd like to test some further software validation checks out for our fork.

**Comment by cerminar** [comment]
@aloeliger thanks. Not sure what you mean by "urgent": it can certainly wait a few days without problems on my side. Other users in need to re-run a production workflow might have a different opinion. You have a better overview of these use cases.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found new L1 contents added by this PR:
| Type | Module | Label | Process |
|:----:|:------:|:-----:|:-------:|
|BXVector<l1t::EGamma>|l1tLayer2EG|L1CtEgEE|L1
|vector<l1t::TkElectron>|l1tLayer2EG|L1CtTkElectron|L1
|vector<l1t::TkEm>|l1tLayer2EG|L1CtTkEm|L1

**Comment by aloeliger** [comment]
@cerminar Could you confirm for me these are the expected Phase 2 L1 additions from this PR? I want to make sure the validation script found everything.

**Comment by cerminar** [comment]
Hello @aloeliger, I confirm!

**Comment by aloeliger** [comment]
@epalencia anything else? Otherwise I'm fine merging this in now, I've gotten all the testing I need out of this.

**Comment by epalencia** [comment]
> @epalencia anything else? Otherwise I'm fine merging this in now, I've gotten all the testing I need out of this.

No, we can merge it and tag.

**Comment by epalencia** [comment]
Tagged as **_l1t-phase2-v56_**.

**Pull request merged**
