### PR TITLE
Update muon shower (un)packers for 2023 running (Backport of 41172)

### PR DESCRIPTION
**Pull request by epalencia**
Backport of https://github.com/cms-sw/cmssw/pull/41172.

Added logic to the (un)packers to deal with the new "two loose showers" bit that will be used in 2023. The logic for those changes is gated behind either the firmware version that was extracted from the readout record or by the era.

### CODE REVIEW

**Comment by dinyar** [comment]
Hi @epalencia,

Just to make sure: I think you'll also need the PR with the modified data formats (https://github.com/cms-sw/cmssw/pull/40890) too.

Cheers,
Dinyar

**Comment by epalencia** [comment]
Hi @dinyar, 408900 is included in [13_1_0_pre 2](https://github.com/cms-sw/cmssw/releases/CMSSW_13_1_0_pre2) already, it should have been included in the IB when doing the rebase, no?

**Comment by dinyar** [comment]
Oh, sorry hadn't checked that. :⁠-⁠)

**Comment by epalencia** [comment]
Tagged as _l1t-integration-v150_.

**Pull request merged**
