### PR TITLE
Updates L1 calibrations for all objects: towers, jets, eg & tau

### PR DESCRIPTION
**Pull request by bundocka**
Consistent set of calibrations to be used for L1 menu studies.

### CODE REVIEW

**Comment by bundocka** [comment]
This deprecates #481 for eta restricted HTT and tower count fix. Those commits are now included in this PR.

**Comment by fwyzard** [comment]
Does this *ADD* a further |eta|-restricted HT, or does this change the
definition of the existing HT triggers ?

.Andrea

On 2 Apr 2017 23:34, "bundocka" <notifications@github.com> wrote:

This deprecates #481 <https://github.com/cms-l1t-offline/cmssw/pull/481>
for eta restricted HTT and tower count fix. Those commits are now included
in this PR.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cms-l1t-offline/cmssw/pull/486#issuecomment-291016860>,
or mute the thread

**Comment by bundocka** [comment]
This changes the configuration of the emulator such that the maximum eta for jets in the HT sum is now 26 *instead* of 28. So it changes the definition of the existing HT sum. After speaking to Takashi this will be called HTer2p5 or something to that effect. Eventually we can also send HTTHF, but that is not currently implemented in the firmware.
Cheers,
Aaron

**Comment by rekovic** [comment]
@bundocka This should be rebased to the default branch l1t-integration-CMSSW_9_0_0.

**Comment by rekovic** [comment]
Rebased and merged to l1t-integration-CMSSW_9_0_0 branch.
Tagged as v92.11

**Pull request closed without merging**
