### PR TITLE
Phase 2 jet event content

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

This PR changes with jet collections are produced in the standard L1 sequence, and are stored in the event content:

- 7x7 histogram puppi jets are removed
- 9x9trimmed histogram jets are added, 9x9 histogram jets are kept in
- Simulated seeded cone puppi jets are removed, keeping only the collection produced by emulation
- The HPS tau simulation/emulation are updated to use the 9x9trimmed jet instead of 7x7 jets.

#### PR validation:

Ran the L1T sequence, checked that the relevant collections are now added/removed.

### CODE REVIEW

**Comment by cecilecaillol** [comment]
@EmyrClement  Could you move this PR to the new rebased branch phase2-l1t-integration-1252patch1?

**Comment by EmyrClement** [comment]
I'm rebasing to the new branch, following the instructions on the twiki, but the example cmsDriver command fails.  It looks like these lines may have been left in after the rebase  :

https://github.com/cms-l1t-offline/cmssw/blob/l1t-phase2-v51-CMSSW_12_5_2_patch1/L1Trigger/Configuration/python/SimL1Emulator_cff.py#L183-L192

They look like the sequences for GTT jet/met objects using the previous naming convention.  The objects with the new naming convention appear a few lines earlier.

If you confirm that's correct, I can remove them in this PR, or let you handle it in another?

**Comment by EmyrClement** [comment]
Rebase in #1062, closing this one.

**Comment by cecilecaillol** [comment]
> I'm rebasing to the new branch, following the instructions on the twiki, but the example cmsDriver command fails. It looks like these lines may have been left in after the rebase :
> 
> https://github.com/cms-l1t-offline/cmssw/blob/l1t-phase2-v51-CMSSW_12_5_2_patch1/L1Trigger/Configuration/python/SimL1Emulator_cff.py#L183-L192
> 
> They look like the sequences for GTT jet/met objects using the previous naming convention. The objects with the new naming convention appear a few lines earlier.
> 
> If you confirm that's correct, I can remove them in this PR, or let you handle it in another?

Yes these should be removed, thank you for catching it and making the modifications in 1062!

**Pull request closed without merging**
