### PR TITLE
Phase2 l1t integration cmssw 10 6 0 pre4 nntau

### PR DESCRIPTION
**Pull request by violatingcp**
Updating the NN taus so that it compiles with 10_6

### CODE REVIEW

**Comment by rekovic** [comment]
@violatingcp 
This PR is not compiling.  It is missing the file `L1Trigger/Phase2L1Taus/interface/TauNNId.h`. Please fix.

**Comment by violatingcp** [comment]
I added the file

**Comment by rekovic** [comment]
@violatingcp 
Thanks.  Now merged and two producers included in the menu `l1NNTauProducer` and `l1NNTauProducerPuppi`
Are both non-puppi and puppi versions to be used in the Menu?

**Comment by violatingcp** [comment]
I think we can just use PUPPI for now. It is better.

**Pull request merged**
