### PR TITLE
Add caloParams for 100X Layer 1 SF

### PR DESCRIPTION
**Pull request by bundocka**
Added two new caloParams for 2018 running with new Layer 1 SF derived from MC, with and without ECAL TP ZS to suppress high eta noisy ECAL TPs:

L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_0_ECALZS_inconsistent_cfi.py
L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_0_inconsistent_cfi.py

### CODE REVIEW

**Comment by abrinke1** [comment]
Hi @bundocka ,
Thanks for pushing these.  A few questions:

1) I take it the "ECALZS" is with your latest "Medium" level thresholds, i.e. 3 / 6 / 9 GeV in TT 26 / 27 / 28? [1]

2) I notice that most of the existing CaloParams (and your new ones) have "inconsistent" in the name.  For my education, what does this indicate?

3) @christopheralanwest had mentioned one other HCAL pull request that needs to be included for the proper derivation of Layer-1 and Layer-2 scale factors.  Is this already in cms-l1t-offline:l1t-integration-CMSSW_10_0_0, or will @rekovic need to add that PR as well for the integration tag to derive Layer-2 scale factors?

Cheers,
Andrew

[1] https://indico.cern.ch/event/716805/contributions/2946490/attachments/1623925/2585288/ecalThresh_TP_180327.pdf

**Comment by christopheralanwest** [comment]
@abrinke1 No, PR #22291 is not included in cms-l1t-offline:l1t-integration-CMSSW_10_0_0.

**Comment by rekovic** [comment]
this PR is merged and is tagged as `l1t-integration-v97.21`.

**Comment by rekovic** [comment]
@bundocka, @abrinke1 
for your temp work, if urgent use the rebase branch I put in my repo

`rekovic:l1t-integration-CMSSW_10_1_0 `
tag `l1t-integration-v97.20-CMSSW_10_1_0`

This has PR #22291 included as it is part of CMSSW_10_1_0.

**Comment by bundocka** [comment]
Hi all,

Thanks for this Vladimir. 

Andrew, correct, ECALZS is using medium thresholds. These were actually the thresholds James put in 
the caloParams files he sent round, so I didn’t have to change the SF LUTs. I also cross-checked them 
against caloStage2Params_2017_v1_8_4, which corresponds to the online configuration as of end of 
2017 pp running, and corrected the egIsoLUT2 and MET PUS LUT.

“Inconsistent” indicates that the Layer 1 and Layer 2 calibrations are inconsistent in these files, so these 
are just config files with only updated Layer 1 calibrations to be used to derive new Layer 2 calibrations. 

Regarding PR #22291 <https://github.com/cms-sw/cmssw/pull/22291>, I still think the safest approach is to follow the same recipe as James, i.e. for derivation 
of Layer 2 calibrations use CMSSW 10_0_0 with l1t-integration-v97.21 and manually merge this PR. I think this 
is the only way we can guarantee consistency without performing additional cross-checks. 

Thanks all, and Happy Easter :)

Aaron

**Comment by rekovic** [comment]
Hi guys, 

The branch `rekovic:l1t-integration-CMSSW_10_1_0` is updated
to include this PR and the tag is `l1t-integration-v97.21-CMSSW_10_1_0`.

Happy Easter!

Vladimir

**Comment by abrinke1** [comment]
Hi @rekovic ,
One quick question: I see rekovic:l1t-integration-CMSSW_10_1_0 in your gitHub area:
https://github.com/rekovic/cmssw/tree/l1t-integration-CMSSW_10_1_0

but I don't see the tag l1t-integration-v97.21-CMSSW_10_1_0 anywhere in l1t-offline:
https://github.com/cms-l1t-offline/cmssw/releases

Or is the tag l1t-integration-v97.21 identical to rekovic:l1t-integration-CMSSW_10_1_0?
https://github.com/cms-l1t-offline/cmssw/releases/tag/l1t-integration-v97.21

**Comment by abrinke1** [comment]
Oh wait, I see - it's in your own gitHub area:
https://github.com/rekovic/cmssw/releases
https://github.com/rekovic/cmssw/releases/tag/l1t-integration-v97.21-CMSSW_10_1_0

Thanks much,
Andrew

**Comment by rekovic** [comment]
@abrinke1 Correct.

**Pull request merged**
