### PR TITLE
TPS version with the algorithm used for the TDR results 

### PR DESCRIPTION
**Pull request by bachtis**
Finally this is fixed.
The algorithm changes are propagated to L1TNtuples etc 

@rekovic Хвала

### CODE REVIEW

**Comment by rekovic** [comment]
@bachtis 
Please resolve the conflict.  Thanks.

**Comment by bachtis** [comment]
@rekovic Done. I used the name L1TPS Muons because TPS has nothing to do with KBmtf and this is the name I updated as well in the L1 analysis ntuples

**Comment by rekovic** [comment]
@bachtis 
I  fixed the conflicts when merging locally.  However, the code crashes when executing the phase2 l1t sequence, as in the primer config file in Phase2 twiki.  
Error report:
```
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 1 event: 13 stream: 0
   [1] Running path 'L1simulation_step'
   [2] Calling method for module L1TTPSProducer/'l1TPSMuons'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<L1MuCorrelatorHit>
Looking for module label: l1TPSStubs
Looking for productInstanceName:

   Additional Info:
      [a] If you wish to continue processing events after a ProductNotFound exception,
add "SkipEvent = cms.untracked.vstring('ProductNotFound')" to the "options" PSet in the configuration.

----- End Fatal Exception -------------------------------------------------
```

**Comment by rekovic** [comment]
@bachtis 
I don't see where is the instance for the module `L1TMuCorelatorHitProducer`.  Nor its cfi file.

Please add missing file(s) and test.

**Comment by rekovic** [comment]
You were missing to include the full TPS sequence in the phase2 l1t sequence.
I fixed it.  
```
+#l1TPSMuons = l1StubMatchedMuons.clone()
+#phase2_SimL1Emulator += l1TPSMuons
+phase2_SimL1Emulator += l1TrackerPlusStubsSequence
```

**Comment by bachtis** [comment]
Thanks Vlad, sorry was away the last two days!

**Pull request merged**
