### PR TITLE
New uGMT extrapolation LUTs

### PR DESCRIPTION
**Pull request by thomreis**
New extrapolation LUTs to go along with the BMTF improvements in PR #478 

LUTs are in https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/pull/3

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic hold this PR for now. We have discovered a drop in di-muon efficiency when applying PR #478  that we need to understand first.

**Comment by rekovic** [comment]
hold

**Comment by thomreis** [comment]
I think this has no effect here. :-)

**Comment by rekovic** [comment]
it is a note for you :-)

**Comment by thomreis** [comment]
Superseded by #523

**Pull request closed without merging**
