### PR TITLE
New uGMT extrapolation LUTs

### PR DESCRIPTION
**Pull request by thomreis**
New uGMT extrapolation LUTs.

These take the BMTF eta scale fix into account.

### CODE REVIEW

**Comment by rekovic** [comment]
@thomreis 
You confirm the improved performance of di-muons with the latest fixed BMTF PR #522 ?

**Comment by thomreis** [comment]
Not yet. Waiting for plots from Dinyar.

**Comment by thomreis** [comment]
Validation plots can be found here:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/extrapolation/muon_extrapolation_histos_5eta_7pt_4out_2outshiftphi_0outshifteta_20170505/

**Comment by thomreis** [comment]
The LUTs to the data directory are in this PR: https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/pull/4

**Comment by thomreis** [comment]
Plots look OK. @rekovic please go ahead with this.

**Pull request merged**
