### PR TITLE
New phi extrapolation LUTs

### PR DESCRIPTION
**Pull request by thomreis**
New phi extrapolation LUTs in the current format with improved performance.

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic do you actually see the new LUTs in this PR? Because I do not since they are in the data repo.

**Comment by thomreis** [comment]
The impact of the new LUT can be seen on the plots here:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/extrapolation/muon_extrapolation_histos_6eta_6pt_3out_3outshift_new_tune_20170217/

**Comment by thomreis** [comment]
The LUTs are in this commit
https://github.com/thomreis/L1Trigger-L1TMuon/commit/6f794f7320ff9080625ddaa95ec4c91e72ba58f3

**Comment by rekovic** [comment]
LUT's are merged directly to cms-l1t-offline/L1Trigger-L1TMuon.  
To have them locally, use clone:
<pre>
git clone https://github.com/cms-l1t-offline/L1Trigger-L1TMuon.git L1Trigger/L1TMuon/data
</pre>

**Comment by thomreis** [comment]
@rekovic I don't see the LUTs in cms-l1t-offline/L1Trigger-L1TMuon. There are only the ones from PR #463 
This PR should include a single LUT file named microgmt_luts/PhiExtrapolation_6eta_6pt_3out_3outshift_20170217.txt

**Comment by thomreis** [comment]
It's there now. Thanks.

**Pull request merged**
