### PR TITLE
Updates for GE1/1-ME1/1 and GE2/1-ME2/1 integrated trigger

### PR DESCRIPTION
**Pull request by dildick**
PR following the presentation in today's muon trigger meeting.

We are currently checking the ALCT/CLCT and LCT efficiency at PU200. @rekovic I will get back to you tomorrow with news on the performance, so you can integrate the branch.

@jiafulow @tahuang1991

### CODE REVIEW

**Comment by dildick** [comment]
@rekovic You can integrate the branch, GEM-CSC TP performance looks good at PU200

**Comment by rekovic** [comment]
@jiafulow 
This PR, especially the last commit 5b99163 could (negatively) effect the EMTF++ performance. Please confirm. Thanks

**Comment by dildick** [comment]
@jiafulow Specifically, look at |eta|~1.7. There is an efficiency that I'm trying to fix.

**Comment by dildick** [comment]
see #818

**Pull request closed without merging**
