### PR TITLE
Adding basic P2 L1CaloTaus - Cleaner

### PR DESCRIPTION
**Pull request by truggles**
Same as [PR760](https://github.com/cms-l1t-offline/cmssw/pull/760) except beginning with latest integration branch tag l1t-phase2-v2.17.15.1 making it a little cleaner.

This PR adds L1CaloTaus based on the results shown during the March L1T P2 meeting. The L1CaloTaus are produced in the same EDProducer as the L1CaloJets and simply use a different clustering geometry and have different calibrations and the loose isolation WP applied. We added a BXV output collection for use in the menu studies where the quality bit indicates whether the loose iso WP was passed or not. L1CaloTaus BXV Output

Additional changes:

    Minor change to L1CaloJets calibration based on the adjustment I made in the treatment of L1EGs for determination of the seed tower. This will slightly increase efficiency and does not alter rate noticeably.
    Adds an L1CaloJetHTT producer which runs by default from the L1CaloJetSequence.
        No calibrations are applied in the producer which would align gen HTT and L1 reco calo HTT.

### CODE REVIEW

**Comment by rekovic** [comment]
@truggles 
I will merge this now, but please submit a new PR which would further rid this code from commented lines.  Thanks.

**Comment by rekovic** [comment]
@truggles 
Digging deeper into the code, the way this CaloTau producer is organized is very difficult to follow it as everything is cluttered into the existing CaloJet producer. You have L1TCaloTau be stored as L1TCaloJet DataForma but with additional ID values.  This is very confusing. 
We already said multiple times that we need producers which produce (add into the event) collections with final versions of objects.  If there are multiple versions of objects depending on the value of some ID cut then those objects should be stored in different containers. If a producer produces more than one product of the same type, each must be given a different product instance label which can then be used to distinguish them. 

Please make changes.

**Comment by truggles** [comment]
Hi @rekovic.  The CaloTaus are stored in l1t::Tau objects.  Please see [here](https://github.com/truggles/cmssw/blob/phase2-l1taus_10_5_Xv2/L1Trigger/L1CaloTrigger/plugins/L1CaloJetProducer.cc#L1162-L1171) with all the normal l1t::Tau information available.  The container is uniquely named "L1CaloTauCollectionBXV".

I will not have time to make any further changes as I quit CMS one month ago.  Sorry.

**Comment by bisnupriyasahu** [comment]
@rekovic I will follow up this onwards. So as Tyler mentioned we are indeed making different collection here. But we can definitely follow up on how you want it to clean it further. I will start a email for this with Sascha in cc.

**Comment by gomber** [comment]
@rekovic , I meant to write the above comment from my account, somehow I didn't realise that my student was logged in.. So its actually me (i.e Bhawna ) who will do this, not bisnupriya. Sorry for the confusion. Anyways I have also written you via email, so we can follow up there.

**Comment by rekovic** [comment]
Hi @gomber Thank you.
Since in the meantime we have moved to `phase2-l1t-integration-CMSSW_10_6_0_pre4`, can you please rebase this PR to this new integration branch?

Please make sure that the objects stored in a collection have the appropriate ID cuts applied.

**Comment by rekovic** [comment]
I  rebased this PR to  `phase2-l1t-integration-CMSSW_10_6_0_pre4` and merged it, and made a tag `l1t-phase2-v2.17.30`.  

So, close this PR.

**Pull request closed without merging**
