### PR TITLE
uGMT upgrades and bugfixes

### PR DESCRIPTION
**Pull request by thomreis**
Load LUTs from l1t::LUT object from conditions DB instead of from files.
Increase the LUT size for cancel out to 5 bit dEta inputs
Emulator bugfixes:
- handle wrap-around for negative globalPhi
- Fix sorters to not let more than the required number of muons pass

This PR supersedes https://github.com/cms-l1t-offline/cmssw/pull/246 to 8_0_2

### CODE REVIEW

**Comment by mulhearn** [comment]
Ah, does this fix the crashes I see like this:

```
----- Begin Fatal Exception 05-May-2016 14:03:31 CEST-----------------------
An exception of category 'Uninitialized' occurred while
   [0] Processing run: 1 lumi: 1 event: 1
   [1] Running path 'L1simulation_step'
   [2] Calling event method for module L1TMuonProducer/'simGmtStage2Digis'
Exception Message:
If you're not loading a LUT from file you need to implement lookupPacked.
----- End Fatal Exception -------------------------------------------------
```

**Comment by mulhearn** [comment]
Wait, why does this PR mix emulator fixes and o2o updates?  Where is this going?

**Comment by mulhearn** [comment]
I don't want emulator changes in o2o branch, so we can know things are working by checking bitwise agreement with l1t-integration-v47.0 ...

**Comment by thomreis** [comment]
This does not touch the O2O and is supposed to go in the normal integration branch. The LUTs are in the cond format for a while already (written by the fake2O producer https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_7/L1Trigger/L1TMuon/plugins/L1TMuonGlobalParamsESProducer.cc#L189) but were not used so far because they were taken from files.

**Comment by thomreis** [comment]
In which workflow do you see this crash?
It means that there was no path to a LUT file given and that the emulator does not know how to generate the LUT on the fly (it does know this only for cancel out LUTs and the sortRank LUT).

**Comment by mulhearn** [comment]
Ah, I see, this is only for integration branch.  No O2O here, you are just taking these from CondFormat now.

**Comment by thomreis** [comment]
Yes, exactly. 
However, these are changes that are required if we want to later USE what the O2O will write to the DB. So these changes work without the O2O, but once the O2O is in place they will be needed.

**Comment by mulhearn** [comment]
Right, OK, we'll put in both.

**Comment by thomreis** [comment]
Perfect.

**Comment by mulhearn** [comment]
This is in the o2o integration branch already with tag l1t-o2o-integration-v1.0.  Vladimir said he'll handle the integration branch.

**Pull request merged**
