### PR TITLE
Update jet collection used by HPS taus

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

A commit that was missed for #1210

#### PR validation:

Ran L1 sequence, see new collection in output root file.

### CODE REVIEW

**Comment by EmyrClement** [comment]
We should also probably add a requirement that the jet collection is only consumed if `fUseJets_` is true:

https://github.com/cms-l1t-offline/cmssw/blob/85d58ce03560972fcebbb69b34f23410332f67fb/L1Trigger/Phase2L1ParticleFlow/plugins/L1HPSPFTauProducer.cxx#L64

Maybe that's a comment we can add to the HPS tau PR to master?

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
> We should also probably add a requirement that the jet collection is only consumed if `fUseJets_` is true:
> 
> https://github.com/cms-l1t-offline/cmssw/blob/85d58ce03560972fcebbb69b34f23410332f67fb/L1Trigger/Phase2L1ParticleFlow/plugins/L1HPSPFTauProducer.cxx#L64
> 
> Maybe that's a comment we can add to the HPS tau PR to master?

I think it needs to be consumed regardless to be passed to this function: 

https://github.com/cms-l1t-offline/cmssw/blob/85d58ce03560972fcebbb69b34f23410332f67fb/L1Trigger/Phase2L1ParticleFlow/plugins/L1HPSPFTauProducer.cxx#L139

the result of `fUseJets` is passed here too, so without reading too much further I would guess it is fine flagging using jets or not for it's own behavior, but attempting to prevent the read overall may be more trouble than it is worth.

**Comment by aloeliger** [comment]
@EmyrClement I've tested that this fix works. I am going to merge this for the v2 tag. Please ASAP open a PR for #1204, #1210, and #1212 to CMSSW (as one PR is probably easiest, but however you can make work).

**Comment by EmyrClement** [comment]
@aloeliger I won't open a PR in master for this, as it's already fixed in [#43848](https://github.com/cms-sw/cmssw/pull/43848), specifically in the corresponding [fillDescriptions](https://github.com/cms-sw/cmssw/pull/43848/files#diff-42957d57605f6b3be3f2ea64db317139c2d59d29d45599122c8bd46dee4731acR57-R68), which replaced the python config modified here.

**Pull request merged**
