### PR TITLE
 Add caloParams_2023_v0_1

### PR DESCRIPTION
**Pull request by jonamotta**
Upload of caloParams_2023_v0_1.

The caloParams are derived from caloParams_2022_v0_6 and include the following modifications:

1. New eg/tau calibration/isolation LUTs for 2023 data-taking start as detailed in [this PR](https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter/pull/16)
2. ZS of the HB trigger towers with 0.5GeV energy deposit

### CODE REVIEW

**Comment by jonamotta** [comment]
Re-built the caloParams based on 2023_v0_0 [1] as requested by @bundocka via email

[1] https://github.com/cms-sw/cmssw/blob/master/L1Trigger/L1TCalorimeter/python/caloParams_2023_v0_0_cfi.py

**Comment by aloeliger** [comment]
Hi @jonamotta We usually request that phase 1 PRs get opened directly to central CMSSW first. It is a better and more accurate reflection of what phase 1 looks like, and has better testing. Could you please open this PR up to central CMSSW for us to review and sign on?

**Comment by elfontan** [comment]
Hi @aloeliger,
I am not sure if these updates are usually included also in Master or just in the OSW branch for our offline studies with L1Ntuples (see list of old PRs in central CMSSW about caloParams [here](https://github.com/cms-sw/cmssw/pulls?q=is%3Apr+is%3Aclosed+caloParams)). We should probably check with Aaron.

Cheers,
--Elisa

**Comment by aloeliger** [comment]
Okay. That's probably fine. I just don't want a commit to get forgotten here in our phase 1 IB without a necessary corresponding PR to master.

**Comment by bundocka** [comment]
Yes, I think these can just go into the master from now on. 
correction: in addition to the integration branch (since they are needed there for the menu rate studies!)

**Comment by elfontan** [comment]
Thanks @bundocka!
In my understanding, the reason why we were going to OSW before in this case was to fully validate the caloParams updates (before any deployment), and then maybe deploy them, and go to master eventually later on with something final. However, it looks to me that we were not going to master with such updates at all (see [config files](https://github.com/cms-sw/cmssw/tree/master/L1Trigger/L1TCalorimeter/python), am I wrong?)...

Maybe we should simply define a new workflow for these changes for this year and follow the usual "MASTER+Backport", up to Andrew and OSW the decision!

Cheers,
ELisa

**Comment by bundocka** [comment]
Yes indeed I noticed this as well, that these updates are missing from the master. I think in the past every so often the changes in the integration branch were merged into master, but this hasn't been done for some time. So I think we probably move forward also with a PR to master, but Andrew should of course decide what he thinks is best!

**Comment by jonamotta** [comment]
Sorry for the late reply, and thanks for the comments.
I wait for @aloeliger's confirmation on what to do then, I have no issue with either option.

**Comment by aloeliger** [comment]
I have merged this as agreed in the last two software meetings.

**Comment by epalencia** [comment]
Tagged as **_l1t-integration-v153_**.

**Pull request merged**
