### PR TITLE
Rewrite linpuppi emulator with ap_fixed (14_0_0_pre3 branch)

### PR DESCRIPTION
**Pull request by gpetruc**
Replaces #1201 that was based on the 13_3_X branch.

PR to master https://github.com/cms-sw/cmssw/pull/43821 is merged already

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@gpetruc  In order to start constructing a protoytype branch for the menu team to validate, this PR is being merged immediately. If there is no corresponding PR to CMSSW, please make it now.

**Comment by gpetruc** [comment]
Hi @aloeliger : as it was already written above in the PR description, the CMSSW PR exists already and has already been merged in the CMSSW master (one week ago)

**Pull request merged**
