### PR TITLE
L1T Tau: adding trimming + shape veto dummy LUT - replaces PR #549

### PR DESCRIPTION
**Pull request by davignon**
This PR concerns changes that are needed for the O2O.
We implement a dummy Trimming + Shape Veto LUT that can be retrieved from online.
The LUT is currently not used in the emulator. However given the current online configuration, the emulator and firmware would still give the exact same answer.
I will update the emulator in a subsequent PR such that it reads this dummy LUT (to prepare for when it's not dummy anymore).
Please consider for merging as this is very important for O2O.

Cheers,
- Olivier

### CODE REVIEW

**Comment by davignon** [comment]
@kkotov 

About your questions on the previous PR #549 (still relevant here):

"what is the LUT's name in the online DB?"
--> Should be "P_TauTrimming_13to8.mif" if I'm not mistaken. Can you please confirm?

"should I use caloStage2Params_2017_v1_7_2_cfi.py as a prototype, or is v1_7 still good?"
--> I added caloStage2Params_2017_v1_8_1_cfi.py which can serve as a prototype.

**Comment by kkotov** [comment]
@davignon I cannot confirm the new lut name. Dumping configs with a recent calo TSC key doesn't match a pattern:

python ~kkotov/public/caloDump.py
python ~/public/caloDump.py calol2_commissioning2017/v21
grep -i Trim *

looking into MP_TAU keys shows that the most recent one was aggregated by a TSC key (and, hence, couldn't have been missed above):

select distinct MP_TAU from CMS_TRG_L1_CONF.CALOL2_ALGO_KEYS ;

Therefore, I suspect the new "P_TauTrimming"P_TauTrimming_13to8.mif" haven't yet been put online.

**Comment by kkotov** [comment]
@davignon , I've updated the L1T O2O. Before we can use it we will need to merge you v1_8_1 with @bundocka v1_7 in the prototype payload.

**Comment by rekovic** [comment]
@davignon Please fix conflicts.

**Comment by davignon** [comment]
Replaced by PR #560. Closing.

**Pull request closed without merging**
