### PR TITLE
Phase2 prototype gt v0 1

### PR DESCRIPTION
**Pull request by jheikkil**
PR for the GT emulator V0_1. This GT emulator includes the abbreviated Step-1 Menu with 16 seeds requested by our HLT colleagues, and the performance has been validated in detail with the help of the menu team. We include two changes to the upstream emulators, one concerning taus (as per recommendation by Emyr), and another to change to the trkIso for tkPhotons (instead of trkIsoPV, as per recommendation by Gianluca). 

I am opening this PR for documentation for now, possible merge (incl. target branch and tag) needs to be discussed in detail with @aloeliger.

### CODE REVIEW

**Comment by aloeliger** [comment]
@jheikkil Are all 170 of these commits GT intended commits? There seems to be a lot of duplicate information here..

**Comment by aloeliger** [comment]
This PR has also been opened to a snapshot branch. We are very much trying to discourage development on snapshot branches.

**Comment by jheikkil** [comment]
> @jheikkil Are all 170 of these commits GT intended commits? There seems to be a lot of duplicate information here..

They must come from building our branch on top of the Snapshot_3. I tried using rebasing, and it didn't work. I also had to pick up new changes to objects after snapshot branch was updated. If you have clear instructions on how to fix this, I gladly do it. We can take the discussion to private channels.

> This PR has also been opened to a snapshot branch. We are very much trying to discourage development on snapshot branches.

I am aware of this, and that is why I said that this is mainly for documentation for now. I would be happy to receive instructions to where to open the final PR.

**Comment by jheikkil** [comment]
Another point @aloeliger : Including this GT emulator to the L1 sequence must be still discussed. I understood that the conclusion was that the SW team has the final say on how this should be done. We didn't propose a solution given the file determining the L1 sequence included also Phase-1 information that might in some cases complicate building the solution. The file test_GT.py does include an example configuration file that hopefully helps.

**Comment by aloeliger** [comment]
> > @jheikkil Are all 170 of these commits GT intended commits? There seems to be a lot of duplicate information here..
> 
> They must come from building our branch on top of the Snapshot_3. I tried using rebasing, and it didn't work. I also had to pick up new changes to objects after snapshot branch was updated. If you have clear instructions on how to fix this, I gladly do it. We can take the discussion to private channels.
> 
> > This PR has also been opened to a snapshot branch. We are very much trying to discourage development on snapshot branches.
> 
> I am aware of this, and that is why I said that this is mainly for documentation for now. I would be happy to receive instructions to where to open the final PR.

@jheikkil Trying to rebase your branch to the snapshot to remove duplicate commits introduces multiple merge conflicts. What series of steps did you do to set-up the commits in this PR?

**Comment by aloeliger** [comment]
Trying to unsnarl all the merge conflicts they seem to be mostly white space and formatting conflicts. Do you know how these were introduced?

**Comment by jheikkil** [comment]
Hi @aloeliger!

If I recalled right, I took our prototype branch (based on Shapshot 1), tried to rebase to Snapshot_3. At this point there were maybe 3 conflicts, but nothing major. When you included taus to Snapshot_3, I went ahead and tried to use rebasing again, only to find this wouldn't compile. Then I used cms-merge-topic, which worked, but probably got all those commits with it. 

Would it make sense if I start from a clean area with Snapshot_3, bring in only our emulator and the tau fixes, and then try to make a new PR?

**Comment by aloeliger** [comment]
@jheikkil Well, there's really no clean solution for this, the best thing may be (depending on the number of commits in the GT emulator, seems liike 20?) simply to cherry-pick them over to this branch. Depending on how the emulator development team feels about whether specific commits are necessary, you might also be able to squash them to make this task easier. This particular PR is likely not going to be reformatted easily, so it may be best to start over from a new one.

Just to make sure that a record exists of the individual commits as they exist now, the particular course of action I would recommend is:

```
git checkout -b GT_squashCommits
git reset --soft <first commit that is not the GT emulator, assuming that GT emulator commits are *On top of, not weaved into other commits*>
git commit -m "GT emulator draft for snapshot 3"
git push my-cmssw GT_squashCommits
```
Then use `git log` to locate the GT emulator commit hash
Then in a new/clean CMSSW_12_5_2_patch1
```
git cms-rebase-topic -u cms-l1t-offline:Phase2_prototypeSnapshot_3
git fetch my-cmssw
git cherry-pick <GT emulator commit hash>
```

This will only really work I think assuming that the GT emulator commits  are by themselves, at the top of the history, and do not have other commits tangled into them. If they are, you really only have one course of action which is locate each individual commit by hand and move it onto this branch one at a time.

**Comment by aloeliger** [comment]
superseded

**Pull request closed without merging**
