### PR TITLE
extrapolated muon eta and phi in L1 ntuples

### PR DESCRIPTION
**Pull request by thomreis**
Store the L1 muon eta and phi extrapolated to the vertex in the L1 ntuples.

Two static functions are provided that return the extrapolated coordinates of a given l1t::Muon.

```
static double calcMuonEtaExtra(const l1t::Muon& mu);
static double calcMuonPhiExtra(const l1t::Muon& mu);
```

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic @mulhearn could you merge this please and make a tag? @bortigno will make new ntuples for the full year for the TSG workshop and we would like to have the extrapolated coordinates in if possible.

**Comment by thomreis** [comment]
@rekovic what is the status of this? Can it be merged asap? The trigger workshop starts in 2 days and we would like check the behaviour if possible.

**Comment by rekovic** [comment]
@thomreis  Sorry for the delay.  Now merged and tagged as l1t-integration-v88.1
Use it with CMSSW_8_0_21.

**Comment by thomreis** [comment]
Thanks @rekovic

**Pull request merged**
