### PR TITLE
[Phase-2] Updated of GCT jets and taus collection

### PR DESCRIPTION
**Pull request by pallabidas**
#### PR description:

Restricting total number of GCT jets/taus to 6 per eta half (12 in total, previously was 36). Updated seed tower energy threshold to 5 GeV to suppress PU contribution. The calibrations of jets/taus have been updated using Spring23 samples in 14X release.

#### PR validation:

Passes local validation checks with efficiency and rate plots, to be presented in a DP note.

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

Not a backport.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by pallabidas** [comment]
@aloeliger the code-format suggestion is for a non GCT code

**Comment by EmyrClement** [comment]
@pallabidas can you provide some efficiency and rate plots on how you expect the physics performance changes (or not)?

**Comment by pallabidas** [comment]
Hi @EmyrClement here are some performance plots.
[Uploading Performance of GCTJet-Tau in 14X.pdf…]()

**Comment by pallabidas** [comment]
Hi @EmyrClement here are some performance plots.
[Performance of GCTJet-Tau in 14X.pdf](https://github.com/cms-l1t-offline/cmssw/files/14750633/Performance.of.GCTJet-Tau.in.14X.pdf)

**Comment by EmyrClement** [comment]
From a quick check with the menu tools, I can reproduce the physics performance in the slides shown above for the taus.  There is a drop in performance for lower pt taus in the endcap, but things look ok for the use case of this emulator in the Step 1 menu (tau pt>~60 GeV, |eta|<2.172).

If possible, we need to integrate this into IBv6.

**Comment by aloeliger** [comment]
@pallabidas I think this is fine. Could you please open this PR up to CMSSW and we'll merge it here.

**Comment by pallabidas** [comment]
Done https://github.com/cms-sw/cmssw/pull/44606

**Pull request merged**
