### PR TITLE
Bmtf Packer Warning Removal 

### PR DESCRIPTION
**Pull request by panoskatsoulis**
Removed the disturbing warning

### CODE REVIEW

**Comment by thomreis** [comment]
Hi @panoskatsoulis there is a similar warning in EventFilter/L1TRawToDigi/python/l1tRawtoDigiBMTF_cfi.py
Can that one be removed as well?

**Comment by rekovic** [comment]
@panoskatsoulis 
Cherry-picked and merged in l1t-integration-CMSSW_10_1_5.

**Comment by rekovic** [comment]
@thomreis 
EventFilter/L1TRawToDigi/python/l1tRawtoDigiBMTF_cfi.py is not used anywhere.

**Comment by rekovic** [comment]
> @thomreis
EventFilter/L1TRawToDigi/python/l1tRawtoDigiBMTF_cfi.py is not used anywhere.

So it  should be removed

**Pull request closed without merging**
