### PR TITLE
Correlator Layer 1 updates for Multiboard tests

### PR DESCRIPTION
**Pull request by gpetruc**
This PR updates the CMSSW Correlator Layer 1 code for the use in multi-board tests:
 * the forward hgcal region is now emulated accurately (physics performance should be unchanged since occupancies are well below the threshold at which truncations happen)
 * emulation of the correlator at tmux18 is now possible in CMSSW
 * the correlator pattern file writers are updated to run on the newer samples, to use a cabling map that reflects the current firmware, and to support also the tmux18 option

CMSSW master PR: https://github.com/cms-sw/cmssw/pull/42643

### CODE REVIEW

**Comment by epalencia** [comment]
Hi @gpetruc, this PR is missing the latest commits in https://github.com/cms-sw/cmssw/pull/42643, no?

**Comment by gpetruc** [comment]
yes, i'll push them later tonight or tomorrow

Giovanni

**Comment by gpetruc** [comment]
Done now

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by epalencia** [comment]
Tagged as `l1t-phase2-v77`.

**Pull request merged**
