### PR TITLE
Add HPS tau emulator to sequence + event content

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

Following #1175, this PR replaces the existing HPS tau simulation with the new emulator in the L1 sequence and event content.

#### PR validation:

Ran L1 sequence, see new collection in output root file.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by EmyrClement** [comment]
Do I need to take care of the `code-format` changes for `L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc`, given it's not touched by this PR?  The same question applies to #1211

**Comment by epalencia** [comment]
No, if it is not yours, do not worry about it.

**Comment by aloeliger** [comment]
@EmyrClement This looks relatively simply. Would you please already make the PR to CMSSW master. We will merge this here and test the recipe again once we have accumulated a few changes.

**Comment by aloeliger** [comment]
@EmyrClement Because this is simple enough, we are going to merge it immediately for the menu team. Please open a PR for this to CMSSW at your earliest convenience. @epalencia FYI.

**Comment by aloeliger** [comment]
@EmyrClement I likely should have tested this before I merged, the PR, however this doesn't seem to get all required modules for the new sequence. I get an error:

```
----- Begin Fatal Exception 21-Feb-2024 07:48:22 CST-----------------------
An exception of category 'ProductNotFound' occurred while
   [0] Processing  Event run: 1 lumi: 133 event: 37795 stream: 3
   [1] Running path 'FEVTDEBUGHLToutput_step'
   [2] Prefetching for module PoolOutputModule/'FEVTDEBUGHLToutput'
   [3] Calling method for module L1HPSPFTauProducer/'l1HPSPFTauEmuProducer'
Exception Message:
Principal::getByToken: Found zero products matching all criteria
Looking for type: std::vector<reco::CaloJet>
Looking for module label: l1tPhase1JetProducer
Looking for productInstanceName: UncalibratedPhase1L1TJetFromPfCandidates
```

Were any of the customizations we have been discussing necessary for this?

And I guess while I am looking at this, why is it using Phase 1 jets?

**Comment by EmyrClement** [comment]
This is my bad, there was another change I didn't commit.  I'll add it now.

**Comment by EmyrClement** [comment]
Fixed in #1212.  The "Phase 1" jets are the "Phase 2 histogram" jets here.  I don't think it matters whether the histo jets or seeded cone jets are used right now.

**Comment by EmyrClement** [comment]
@chnielse are you able to add the few lines of changes introduced here to your PR to [master](https://github.com/cms-sw/cmssw/pull/43848)?

**Comment by chnielse** [comment]
Can do.

**Pull request merged**
