### PR TITLE
L1t integration v28.0 tau - new calibration and isolation

### PR DESCRIPTION
**Pull request by davignon**
@mulhearn @rekovic @jimbrooke
This pull request concerns Stage-2 Layer-2 taus, and includes new LUTs for compression, calibration and isolation (Option 21). The calibration and isolation LUTs come in two flavors: with or without Layer-1 trigger towers calibration (.txt files with explicit and different names wrt previous files).
Please consider this pull request, and thank you in advance!

### CODE REVIEW

**Comment by fwyzard** [comment]
hi @davignon ,
maybe Vladimir or Mike will take care of moving them, but otherwise, could you make a pull request for the new data files at https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter instead of here ?

**Comment by jimbrooke** [comment]
I think the changes in caloStage2Params_cfi.py need to be propagated to caloStage2Params_2016_v2.0_cfi.py introduced in PR #236 

@davignon are any changes required to caloStage2Params_2016_v1.0_cfi.py (ie. without Layer 1 corrections)

**Comment by rekovic** [comment]
@davignon,  

> maybe Vladimir or Mike will take care of moving them, but otherwise, could you make a pull request for the new data files at https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter instead of here ?

For the tsg-v5(6) tag I will clean the data directory anyhow, so will move the tau data files as well.  @davignon No need to make a separate PR for data.

**Comment by davignon** [comment]
@jimbrooke 
Yes there are changes needed. Right now caloStage2Params_cfi.py contains the 'default' (i.e. LUTs that correspond to the situation **with** Layer-1 corrections).
If you push the v1.0 and v2.0 configs, I can change them for taus and make the corresponding PR. Below is a summary of how the tau LUTs should read in the configs.

**In caloStage2Params_2016_v1.0_cfi.py** (without Layer-1 corrections)
caloStage2Params.tauIsoLUTFile                 = cms.FileInPath("L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_NoLayer1Calibration_noCompressionBlock_v4.0.0.txt")
caloStage2Params.tauCalibrationLUTFile         = cms.FileInPath("L1Trigger/L1TCalorimeter/data/Tau_Calibration_LUT_NoLayer1Calibration_v9.0.0.txt")
caloStage2Params.tauCompressLUTFile            = cms.FileInPath("L1Trigger/L1TCalorimeter/data/tauCompressAllLUT_12bit_v3.txt")

**In caloStage2Params_2016_v2.0_cfi.py** (with Layer-1 corrections, equivalent to default in current caloStage2Params_cfi.py)
caloStage2Params.tauIsoLUTFile                 = cms.FileInPath("L1Trigger/L1TCalorimeter/data/Tau_Iso_LUT_Option_21_Layer1Calibration_noCompressionBlock_v4.0.0.txt")
caloStage2Params.tauCalibrationLUTFile         = cms.FileInPath("L1Trigger/L1TCalorimeter/data/Tau_Calibration_LUT_Layer1Calibration_v9.0.0.txt")
caloStage2Params.tauCompressLUTFile            = cms.FileInPath("L1Trigger/L1TCalorimeter/data/tauCompressAllLUT_12bit_v3.txt")

**Comment by davignon** [comment]
@rekovic
Thanks a lot for that, let me know if you need anything else from me.

**Comment by jimbrooke** [comment]
@davignon #236 is integrated, so can you make a new PR with the changes you mention above ?

**Comment by rekovic** [comment]
@davignon @jimbrooke 
I tried to put the additional changes suggested above into 2016 v1 and v2, and tag it as l1t-integration-v31.0.  Please check and if needed make a new PR.

**Comment by jimbrooke** [comment]
ah, OK!  I'll let @davignon check this rather than add any more noise....

**Comment by davignon** [comment]
@rekovic @jimbrooke 
Thanks. This looks good! No further PR needed.

**Pull request merged**
