### PR TITLE
Protecting uGMT emulator from zero pT muons

### PR DESCRIPTION
**Pull request by dinyar**
Hi,

muon data with pT = 0 is defined as 'no muon' according to the interface note. The uGMT firmware detects such data and discards it at the inputs, but the emulator seems to be susceptible to receiving muons with reasonable coordinates and quality but pT = 0. In such a case it can happen that a pT = 0 muon cancels out a proper one leading to a mismatch between firmware and emulator.

I've introduced a simple pT > 0 check in the L1TMuonProducer to make sure we only accept proper muons in our input.

@rekovic, please let me know if I should make this PR against a different branch.
@thomreis if you could have a quick look to make sure I didn't miss anything this would be appreciated.

Cheers,
Dinyar

### CODE REVIEW

**Comment by thomreis** [comment]
Hi,
this looks OK to me. Double check if the BX range is still correctly calculated by the autoBxRange algorithm, if a muon with pT == 0 is eventually removed and it is the only on in a BX. I think there should be no problem with BXs without muons in principle, but better be sure.

**Comment by abrinke1** [comment]
Looks good to me: but as discussed in the email @jiafulow and @zuoxunwu and I should track down if there's an emulator bug in EMTF assigning pT = 0 when it should not be.

**Comment by dinyar** [comment]
Hi Thomas,

thanks for the reply and sorry for the long silence. I managed to have a think about this now and I think you're right that it shouldn't be negatively affected. If I understand the autoBxRange algo correctly this is to avoid computing outputs for BXs where only partial information is available, so if we do have a muon in some BX (even if it's with pT 0) this would still correctly indicate the BX range as the pT != 0 cleaning is done later.

Given that @rekovic, could you merge this PR?

Cheers,
Dinyar

**Comment by rekovic** [comment]
@dinyar 
Can you please rebase this old PR to `l1t-integration-CMSSW_10_6_0` branch.  
Thanks.

**Comment by dinyar** [comment]
@rekovic ok, done at #835.

**Pull request closed without merging**
