### PR TITLE
Seeded Cone jets update

### PR DESCRIPTION
**Pull request by thesps**
This PR:

- introduces the R=0.8 configuration for Seeded Cone jets (SC8)
- renames existing Seeded Cone jet collections to 'SC4' for consistency
- fixes some issues with bit-exact matching of the emulator wrt the firmware particularly for MHT
- makes the jets/sums pattern file writer more flexible for testing against the firmware with different configurations

For testing, the emulator now matches the firmware tested on a board at the level of 99.9% for jets and 95% for sums (100% on the scalar sum and 95% on the vector sum do a difference in libraries for the trigonometry).

One thing I haven't done is to update any consumers of the renamed collections.

This branch is rebased on `phase2-l1t-integration-13_3_0_pre3` and supersedes #1165, which I will now close.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@epalencia I think I'm okay with this. Any comment from your side?

**Comment by epalencia** [comment]
No, if needed we can already merged it. Otherwise, we can wait until it is merged in master. @thesps , could you make the corresponding PR in CMSSW?

**Comment by thesps** [comment]
Thanks, I've just opened [the PR](https://github.com/cms-sw/cmssw/pull/43233) to `cms-sw:master`. From my side we can wait for review and merge to master before merging here.

**Comment by epalencia** [comment]
Thanks @thesps . In case you missed it, https://github.com/cms-sw/cmssw/pull/43233 failed the code checks.

**Comment by thesps** [comment]
The PR to https://github.com/cms-sw/cmssw/pull/43233 was merged, but I still need to pull the changes after the review there to here.

**Comment by epalencia** [comment]
Tagged as `phase2-l1t-1330pre3_v14`.

**Pull request merged**
