### PR TITLE
Bmtf unpacker 802 new

### PR DESCRIPTION
**Pull request by eparadas**
Please merge, because this pull request refers to some changes that are added in the unpacker in the naming of the output collections. The changes are used by the emulator as well.

Thanks,
Vangelis

### CODE REVIEW

**Comment by mulhearn** [comment]
Is this needed online urgently?

**Comment by eparadas** [comment]
Hi Mike,
not that much. It contains the latest changes.

**Comment by mulhearn** [comment]
OK, I'm going to prepare an independent unpacker update PR "soon" that will go into CMSSW directly.  This will go there.

**Comment by eparadas** [comment]
Hi Mike, 
in case you have not done yet the pull request, I added a few more changes. These changes are almost the final.

**Comment by rekovic** [comment]
Hi @eparadas , is this 802 PR still needed or is it super-seeded by 807 PR #304 ?

**Comment by eparadas** [comment]
```
                                                                                  ‎@rekovic Hi, I think there is no need for that since we have the 807.                                                                                                                                                                                                                                                                                                                                        Thanks,VangelisSent from BB Q10                                                                                                                                                                                                                Από: rekovicΕστάλη: Παρασκευή, 13 Μαΐου 2016 - 12:59Προς: cms-l1t-offline/cmsswΑπάντηση σε: cms-l1t-offline/cmsswΚοιν.: Evangelos Paradas; MentionΘέμα: Re: [cms-l1t-offline/cmssw] Bmtf unpacker 802 new (#279)Hi @eparadas , is this 802 PR still needed or is it super-seeded by 807 PR #304 ?
```

—You are receiving this because you were mentioned.Reply to this email directly or view it on GitHub

**Comment by rekovic** [comment]
OK.  I will close this PR then.

**Pull request closed without merging**
