### PR TITLE
Support multiple Calo configs

### PR DESCRIPTION
**Pull request by jimbrooke**
This includes layer 1, EG and jet configurations compatible with layer 1 corrections enabled and disabled.  We are waiting for updates from Tau.  @davignon let me know when you have the new tau configs, and I will add them to this branch/PR

### CODE REVIEW

**Comment by jimbrooke** [comment]
Note that this relies on one or other of #217 or #235

**Comment by jimbrooke** [comment]
Also note that these new cfi files are not actually _used_ anywhere.  I forget how the config is selected in standard workflows/cmsDriver.  We should probably add customisations that allow users to select which setup they want.

**Comment by jimbrooke** [comment]
#238 should be integrated first - this PR will need modification afterwards.

**Comment by rekovic** [comment]
@jimbrooke @tstreble @davignon 
Incorporated the suggested changes in configurations for 2016_v1 and 2016_v2.

**Comment by tstreble** [comment]
@rekovic @jimbrooke 
I see that in the current configuration 2016_v2 still old LUTs are used for EG.
I guess this comes from a conflict between #236 and #217 
Is it possible to have

caloStage2Params.egCompressShapesLUTFile    = cms.FileInPath("L1Trigger/L1TCalorimeter/data/egCompressLUT_v4.txt")
caloStage2Params.egShapeIdLUTFile           = cms.FileInPath("L1Trigger/L1TCalorimeter/data/shapeIdentification_adapt0.99_compressedieta_compressedE_compressedshape_v15.12.08.txt")
caloStage2Params.egIsoLUTFile               = cms.FileInPath("L1Trigger/L1TCalorimeter/data/IsoIdentification_0.25_adapt_extrap_v16.04.05.txt")
caloStage2Params.egCalibrationLUTFile       = cms.FileInPath("L1Trigger/L1TCalorimeter/data/corrections_Trimming10_compressedieta_compressedE_compressedshape_v16.03.14.txt")

I can prepare a PR if needed.

**Comment by jimbrooke** [comment]
Hi Thomas - this PR is merged, so please do submit a new one with correct config for 2016_v2 (and 2016_v1, and 2015_v1 if any changes needed there)

**Comment by rekovic** [comment]
@tstreble I thought merged your suggested changes.  Apparently not.  Sorry about that.
Please make a new PR with your suggested changes.

**Comment by tstreble** [comment]
Included in #241

**Pull request merged**
