### PR TITLE
Update GMT track PTLUT

### PR DESCRIPTION
**Pull request by zhenbinwu**
#### PR description:

1. Update the output quallity to apQualFlags() according to GT suggestion.
2. Update the track PTLUT based upon the unpack rinv bits from L1 Track Trigger.

### CODE REVIEW

**Comment by zhenbinwu** [comment]
I think there are changes made in the [EMTF PR](https://github.com/cms-sw/cmssw/pull/43766/commits) to CMSSW is not in the [cms-l1t-offline:phase2-l1t-integration-14_0_0_pre3](https://github.com/cms-l1t-offline/cmssw/tree/phase2-l1t-integration-14_0_0_pre3). I need to update the interface to the EMTF tracks for the CMSSW PR. 

@omiguelc, can you please make a PR to this branch so that I can sync the two GMT code? Thanks

**Comment by omiguelc** [comment]
Hey @zhenbinwu, I've opened a PR for this: https://github.com/cms-l1t-offline/cmssw/pull/1229

**Comment by zhenbinwu** [comment]
> Hey @zhenbinwu, I've opened a PR for this: #1229

Great. Thanks

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@epalencia I don't think I have anything for this here. Any comments from your side before this is merged?

**Comment by epalencia** [comment]
No, you can merge it.

**Comment by aloeliger** [comment]
@zhenbinwu We can merge this now. Does this _require_ #1236 to make sense?

**Comment by zhenbinwu** [comment]
Hi,let us merge this PR. I am expecting some fixes for the current GMT performance, which will come later

**Comment by aloeliger** [comment]
@zhenbinwu Does this require #1236 to make sense? We are about to merge that as well, but need to know if it is required for this.

**Comment by zhenbinwu** [comment]
No, this PR doesn't need #1236. thanks

**Comment by aloeliger** [comment]
@zhenbinwu This is getting merged. Please open a PR to CMSSW as soon as possible with these commits.

**Comment by aloeliger** [comment]
@zhenbinwu Has a PR to CMSSW with these changes been opened?

**Comment by zhenbinwu** [comment]
Hi, I will cherry pick of all the recent GMT commits, add them to the central CMSSW PR.

**Pull request merged**
