### PR TITLE
L1EG modified electron ID cuts

### PR DESCRIPTION
**Pull request by tstreble**
This PR includes the modified implementation of the electron ID cuts in the L1EG algorithm.

### CODE REVIEW

**Comment by rekovic** [comment]
@tstreble We will need a way to turn this on and off, since we already took data without this
relaxation of ID cuts.  Emulator needs to be able to detect which version of firmware was used
in data taking.

Will merge now as is.

**Comment by tstreble** [comment]
@rekovic 
Was there any similar feature introduced for the new BMTF algorithm?
If so, I can have a look to try to reproduce the same logic.

**Comment by rekovic** [comment]
@tstreble We need a way to version the firmware.  An example from CaloLayer2 used fw versioning
in the unpacker: https://github.com/cms-l1t-offline/cmssw/commit/74354f0e2c313a6b165ed660b741383f9549d736

Will check for BMTF and @gflouris.

**Comment by rekovic** [comment]
@tstreble In the meantime, please coordinate fw versioning with @jimbrooke.

**Pull request merged**
