### PR TITLE
Demonstrator tools: Support for EMP v0.7.x buffer file format

### PR DESCRIPTION
**Pull request by tswilliams**
#### PR description:

This pull request extends the phase-2 buffer I/O buffer text file utilities from #900, by adding support for the new format for data files from the EMP firmware/software framework. No existing functionality is removed - the new EMP buffer file format is simply added as a new option. The new EMP framework version that requires this buffer format is already being used for firmware builds in the correlator, GTT and GT.

#### PR validation:

The following checks have been run on this code (beyond confirming that the code compiles):

 * Ran `scram b code-checks` and `scram b code-format`.
 * Ran `test/gtt/createFirmwareInputFiles_cfg.py` with format set to `EMPv2` and inspected output files to verify their format.
 * Ran `test/gtt/verifyFirmwareOutput_cfg.py` to confirm that the new test/gtt/example_*.txt files were parsed correctly

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
Hi @tswilliams apologies for getting to this late. I'm not as familiar with the demonstrator tools. Is this intended for eventual merging into central CMSSW?

**Comment by tswilliams** [comment]
Hi @aloeliger 

> Is this intended for eventual merging into central CMSSW?

Good question. The key practical requirement from my perspective is that this needs to be available whenever emulators are run with the purpose of comparing emulator output with the output from hardware or from FW simulation (e.g. from Vivado sim / QuestaSim). By contrast, the demonstrator tools wouldn't be required in workflows that only create efficiency/rate plots for specific triggers, or e.g. when doing menu studies. 

For context, which parts of the level-1 software are currently excluded from merges into central CMSSW? And are there specific requirements on what code/packages can be included in central CMSSW (beyond maybe passing more in-depth line-by-line code reviews)?

**Comment by EmyrClement** [comment]
Hi @tswilliams @aloeliger just one additional comment - these tools are also useful for other projects outside L1T e.g. I use them on the HGCal side of the HGCal-L1T interface.  For now, I ported them to the HGCal equivalent of cms-1lt-offline, but it would be nice if these tools made it into central CMSSW so it's easier for others to use them.

**Comment by gpetruc** [comment]
Hi Tom,

I second Emyr's suggestion that since these writers are used by emulator CMSSW modules that end up in central CMSSW, and the older version of `L1Trigger/DemonstratorTools` is in CMSSW then this PR should propagated to central CMSSW.

So, you could just rebase these to cms-sw/master from one of the latest CMSSW_13_2_X integration builds and open a PR?

**Comment by aloeliger** [comment]
My apologies for letting this fall of my radar again, but since @EmyrClement and @gpetruc represent a pretty significant portion of the experienced upgrade crew, I would agree that at this point it is desirable to have these tools available in central CMSSW. @tswilliams Would you please open a PR for this to central CMSSW following @gpetruc's suggestion? I'll have another look at this again.

**Comment by tswilliams** [comment]
Hi @aloeliger 

Sure. I rebased this branch on top of cms-sw/cmssw master and created a pull request: https://github.com/cms-sw/cmssw/pull/41768

FYI, this is the first time I've opened a pull request to core CMSSW; I think I've followed the right procedure, but let me know if I need to do anything else

**Comment by gpetruc** [comment]
Hi,
The CMSSW PR https://github.com/cms-sw/cmssw/pull/41768 is merged so I suppose this can be merged here as well?

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by epalencia** [comment]
Tagged as `l1t-phase2-v67`.

**Pull request merged**
