### PR TITLE
Add B tag NN to ntuples

### PR DESCRIPTION
**Pull request by EmyrClement**
#### PR description:

- Add the seededcone jet collection that's produced using the extended tracking to the event content.
  - Also including the Puppi candidates produced using the extended tracking
- Add the "extended Puppi" seeded cone jet collection to the ntuples, and add the b jet NN score that's computed for each jet
- Store the parton/hadron flavour of the Gen jets in the ntuples

I have tried to factorise out only the changes that are required for adding the b jet NN score to the ntuples.  I made similar local changes to what @artlbv has done in #1082 (see [here](https://github.com/EmyrClement/cmssw/commits/bTagNN) for all my changes, including possible duplicates), and the changes in this PR should go on top of those.  Once that is merged (or both are merged) I can double check that no further changes are required.

#### PR validation:

Checked with standard cmsDriver command that reruns L1 trigger sequence.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 4 files that did not meet formatting requirements:
 - L1Trigger/L1TNtuples/interface/L1AnalysisPhaseIIStep1.h
 - L1Trigger/L1TNtuples/plugins/L1GenTreeProducer.cc
 - L1Trigger/L1TNtuples/plugins/L1PhaseIITreeStep1Producer.cc
 - L1Trigger/L1TNtuples/src/L1AnalysisPhaseIIStep1.cc

Please run `scram b code-format` to auto-apply code formatting

**Comment by aloeliger** [comment]
@EmyrClement Could you please reapply the code formatting to these files?

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR passes available unit tests!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b runtests`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found new L1 contents added by this PR:
| Type | Module | Label | Process |
|:----:|:------:|:-----:|:-------:|
|BXVector<l1t::EGamma>|l1tLayer1HGCalExtended|L1Eg|L1
|l1t::RegionalOutput<vector<l1t::PFCandidate> >|l1tLayer1BarrelExtended|PuppiRegional|L1
|l1t::RegionalOutput<vector<l1t::PFCandidate> >|l1tLayer1Extended|PuppiRegional|L1
|l1t::RegionalOutput<vector<l1t::PFCandidate> >|l1tLayer1HGCalExtended|PuppiRegional|L1
|l1t::RegionalOutput<vector<l1t::TkElectron> >|l1tLayer1BarrelExtended|L1TkElePerBoard|L1
|l1t::RegionalOutput<vector<l1t::TkElectron> >|l1tLayer1HGCalExtended|L1TkElePerBoard|L1
|l1t::RegionalOutput<vector<l1t::TkEm> >|l1tLayer1BarrelExtended|L1TkEmPerBoard|L1
|l1t::RegionalOutput<vector<l1t::TkEm> >|l1tLayer1HGCalExtended|L1TkEmPerBoard|L1
|vector<l1t::PFCandidate>|l1tLayer1BarrelExtended|Calo|L1
|vector<l1t::PFCandidate>|l1tLayer1Extended|Calo|L1
|vector<l1t::PFCandidate>|l1tLayer1HGCalExtended|Calo|L1
|vector<l1t::PFCandidate>|l1tLayer1BarrelExtended|EmCalo|L1
|vector<l1t::PFCandidate>|l1tLayer1HGCalExtended|EmCalo|L1
|vector<l1t::PFCandidate>|l1tLayer1BarrelExtended|PF|L1
|vector<l1t::PFCandidate>|l1tLayer1Extended|PF|L1
|vector<l1t::PFCandidate>|l1tLayer1HGCalExtended|PF|L1
|vector<l1t::PFCandidate>|l1tLayer1BarrelExtended|Puppi|L1
|vector<l1t::PFCandidate>|l1tLayer1Extended|Puppi|L1
|vector<l1t::PFCandidate>|l1tLayer1HGCalExtended|Puppi|L1
|vector<l1t::PFCandidate>|l1tLayer1BarrelExtended|TK|L1
|vector<l1t::PFCandidate>|l1tLayer1Extended|TK|L1
|vector<l1t::PFCandidate>|l1tLayer1HGCalExtended|TK|L1
|vector<l1t::PFJet>|l1tSCPFL1PuppiExtendedCorrectedEmulator||L1
|vector<l1t::TkElectron>|l1tLayer1BarrelExtended|L1TkEle|L1
|vector<l1t::TkElectron>|l1tLayer1HGCalExtended|L1TkEle|L1
|vector<l1t::TkEm>|l1tLayer1BarrelExtended|L1TkEm|L1
|vector<l1t::TkEm>|l1tLayer1HGCalExtended|L1TkEm|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPF|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPF|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFCharged|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFCharged|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFChargedHadron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFChargedHadron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFElectron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFElectron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFMuon|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFMuon|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFNeutral|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFNeutral|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFNeutralHadron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFNeutralHadron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPFPhoton|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPFPhoton|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppi|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppi|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiCharged|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiCharged|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiChargedHadron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiChargedHadron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiElectron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiElectron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiMuon|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiMuon|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiNeutral|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiNeutral|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiNeutralHadron|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiNeutralHadron|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNPuppiPhoton|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNPuppiPhoton|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNRegCalo|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNRegCalo|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNRegEmCalo|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNRegEmCalo|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNRegMu|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNRegMu|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNRegTK|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNRegTK|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNSecCalo|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNSecCalo|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNSecEmCalo|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNSecEmCalo|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNSecMu|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNSecMu|L1
|vector<unsigned int>|l1tLayer1BarrelExtended|vecNSecTK|L1
|vector<unsigned int>|l1tLayer1HGCalExtended|vecNSecTK|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPF|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPF|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFCharged|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFCharged|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFChargedHadron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFChargedHadron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFElectron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFElectron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFMuon|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFMuon|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFNeutral|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFNeutral|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFNeutralHadron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFNeutralHadron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPFPhoton|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPFPhoton|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppi|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppi|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiCharged|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiCharged|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiChargedHadron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiChargedHadron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiElectron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiElectron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiMuon|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiMuon|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiNeutral|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiNeutral|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiNeutralHadron|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiNeutralHadron|L1
|unsigned int|l1tLayer1BarrelExtended|maxNPuppiPhoton|L1
|unsigned int|l1tLayer1HGCalExtended|maxNPuppiPhoton|L1
|unsigned int|l1tLayer1BarrelExtended|maxNRegCalo|L1
|unsigned int|l1tLayer1HGCalExtended|maxNRegCalo|L1
|unsigned int|l1tLayer1BarrelExtended|maxNRegEmCalo|L1
|unsigned int|l1tLayer1HGCalExtended|maxNRegEmCalo|L1
|unsigned int|l1tLayer1BarrelExtended|maxNRegMu|L1
|unsigned int|l1tLayer1HGCalExtended|maxNRegMu|L1
|unsigned int|l1tLayer1BarrelExtended|maxNRegTK|L1
|unsigned int|l1tLayer1HGCalExtended|maxNRegTK|L1
|unsigned int|l1tLayer1BarrelExtended|maxNSecCalo|L1
|unsigned int|l1tLayer1HGCalExtended|maxNSecCalo|L1
|unsigned int|l1tLayer1BarrelExtended|maxNSecEmCalo|L1
|unsigned int|l1tLayer1HGCalExtended|maxNSecEmCalo|L1
|unsigned int|l1tLayer1BarrelExtended|maxNSecMu|L1
|unsigned int|l1tLayer1HGCalExtended|maxNSecMu|L1
|unsigned int|l1tLayer1BarrelExtended|maxNSecTK|L1
|unsigned int|l1tLayer1HGCalExtended|maxNSecTK|L1
|unsigned int|l1tLayer1BarrelExtended|totNPF|L1
|unsigned int|l1tLayer1HGCalExtended|totNPF|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFCharged|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFCharged|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFChargedHadron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFChargedHadron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFElectron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFElectron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFMuon|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFMuon|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFNeutral|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFNeutral|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFNeutralHadron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFNeutralHadron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPFPhoton|L1
|unsigned int|l1tLayer1HGCalExtended|totNPFPhoton|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppi|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppi|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiCharged|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiCharged|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiChargedHadron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiChargedHadron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiElectron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiElectron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiMuon|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiMuon|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiNeutral|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiNeutral|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiNeutralHadron|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiNeutralHadron|L1
|unsigned int|l1tLayer1BarrelExtended|totNPuppiPhoton|L1
|unsigned int|l1tLayer1HGCalExtended|totNPuppiPhoton|L1
|unsigned int|l1tLayer1BarrelExtended|totNRegCalo|L1
|unsigned int|l1tLayer1HGCalExtended|totNRegCalo|L1
|unsigned int|l1tLayer1BarrelExtended|totNRegEmCalo|L1
|unsigned int|l1tLayer1HGCalExtended|totNRegEmCalo|L1
|unsigned int|l1tLayer1BarrelExtended|totNRegMu|L1
|unsigned int|l1tLayer1HGCalExtended|totNRegMu|L1
|unsigned int|l1tLayer1BarrelExtended|totNRegTK|L1
|unsigned int|l1tLayer1HGCalExtended|totNRegTK|L1
|unsigned int|l1tLayer1BarrelExtended|totNSecCalo|L1
|unsigned int|l1tLayer1HGCalExtended|totNSecCalo|L1
|unsigned int|l1tLayer1BarrelExtended|totNSecEmCalo|L1
|unsigned int|l1tLayer1HGCalExtended|totNSecEmCalo|L1
|unsigned int|l1tLayer1BarrelExtended|totNSecMu|L1
|unsigned int|l1tLayer1HGCalExtended|totNSecMu|L1
|unsigned int|l1tLayer1BarrelExtended|totNSecTK|L1
|unsigned int|l1tLayer1HGCalExtended|totNSecTK|L1

**Comment by EmyrClement** [comment]
This PR is superseded and split up into #1090 and #1091.  `scram b code-format` has been run in the new PRs.

**Pull request closed without merging**
