### PR TITLE
Dt hough np 20190625 106 x l1 tbranch

### PR DESCRIPTION
**Pull request by pozzobon**
Phase 1 DT TPG histogram-based: different vDrift (chamber and data/MC switch) -- this PR supersedes PR #775 (10_6_0_pre4) in 10_6_1_patch2

### CODE REVIEW

**Comment by rekovic** [comment]
@pozzobon  Thanks for rebasing the PR. 
However, there seem to be problems with the compilation

```
>> Checking EDM Class Version for src/L1Trigger/DTHoughTPG/src/classes_def.xml in libL1TriggerDTHoughTPG.so
In file included from /afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/DTTPG.h:239:0,
                 from /afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/DTTPG.cc:9:
/afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/./DTTPG_Prod.icc: In member function 'std::map<DTChamberId, std::vector<std::pair<unsigned int, edm::Ref<MuonDigiCollection<DTLayerId, DTDigi>, DTDigi> > > > DTTPG::RetrieveDigis(const edm::Event&) const':
/afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/./DTTPG_Prod.icc:24:58: error: 'makeRefToMuons' was not declared in this scope
       edm::Ref< DTDigiCollection, DTDigi > thisDigiRef = makeRefToMuons( DTDigiHandle, thisLayerId, iterDigi );
                                                          ^~~~~~~~~~~~~~
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/Ref.h:139:0,
                 from /afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/DTTPG.h:21,
                 from /afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/DTTPG.cc:9:
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/RefTraits.h: In instantiation of 'const T* edm::refhelper::FindUsingAdvance<C, T>::operator()(edm::refhelper::FindUsingAdvance<C, T>::first_argument_type, edm::refhelper::FindUsingAdvance<C, T>::second_argument_type) [with C = MuonDigiCollection<DTLayerId, DTDigi>; T = DTDigi; edm::refhelper::FindUsingAdvance<C, T>::result_type = const DTDigi*; edm::refhelper::FindUsingAdvance<C, T>::first_argument_type = const MuonDigiCollection<DTLayerId, DTDigi>&; edm::refhelper::FindUsingAdvance<C, T>::second_argument_type = unsigned int]':
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/RefItemGet.h:70:22:   required from 'static const T* edm::refitem::GetRefPtrImpl<C, T, F, unsigned int>::getRefPtr_(const edm::RefCore&, unsigned int) [with C = MuonDigiCollection<DTLayerId, DTDigi>; T = DTDigi; F = edm::refhelper::FindUsingAdvance<MuonDigiCollection<DTLayerId, DTDigi>, DTDigi>]'
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/RefItemGet.h:87:60:   required from 'const T* edm::getRefPtr(const edm::RefCore&, const KEY&) [with C = MuonDigiCollection<DTLayerId, DTDigi>; T = DTDigi; F = edm::refhelper::FindUsingAdvance<MuonDigiCollection<DTLayerId, DTDigi>, DTDigi>; KEY = unsigned int]'
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/Ref.h:611:30:   required from 'const T* edm::Ref<C, T, F>::operator->() const [with C = MuonDigiCollection<DTLayerId, DTDigi>; T = DTDigi; F = edm::refhelper::FindUsingAdvance<MuonDigiCollection<DTLayerId, DTDigi>, DTDigi>]'
/afs/cern.ch/work/r/rekovic/private/relaeses/10x/CMSSW_10_6_1_patch2-Phase2/src/L1Trigger/DTHoughTPG/plugins/./DTTPG_Prod.icc:25:39:   required from here
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/RefTraits.h:18:36: error: conversion from 'MuonDigiCollection<DTLayerId, DTDigi>::DigiRangeIterator {aka DigiContainerIterator<DTLayerId, DTDigi>}' to non-scalar type 'MuonDigiCollection<DTLayerId, DTDigi>::const_iterator {aka __gnu_cxx::__normal_iterator<const DTDigi*, std::vector<DTDigi, std::allocator<DTDigi> > >}' requested
         typename C::const_iterator it = iContainer.begin();
                                    ^~
/cvmfs/cms.cern.ch/slc7_amd64_gcc700/cms/cmssw-patch/CMSSW_10_6_1_patch2/src/DataFormats/Common/interface/RefTraits.h:19:26: error: no type named 'size_type' in 'class MuonDigiCollection<DTLayerId, DTDigi>'
         std::advance(it, static_cast<typename C::size_type>(iIndex));
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by rekovic** [comment]
Please fix.

**Comment by pozzobon** [comment]
this time should be ok. the comparison shows that the MuonDigiCollection header file is now the correct one https://github.com/cms-l1t-offline/cmssw/compare/phase2-l1t-integration-CMSSW_10_6_1_patch2...pozzobon:DTHough_NP_20190625_106X_L1Tbranch?expand=1
please let me know if this works

**Comment by rekovic** [comment]
hi @pozzobon  coming back to this. 
I still see the same problem.  Please check with the following the recipe
```
cmsrel CMSSW_10_6_1_patch2
cd CMSSW_10_6_1_patch2/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline phase2-l1t-integration-CMSSW_10_6_1_patch2
git cms-merge-topic -u cms-l1t-offline:l1t-phase2-v2.25.0

git pull https://github.com/pozzobon/cmssw.git DTHough_NP_20190625_106X_L1Tbranch


scram b -j 8
```

**Comment by rekovic** [comment]
ping @pozzobon 

Any news here?  There are still problems with compilation, and it cannot be merged like this.  Please check this recipe and provide feedback.
```
cmsrel CMSSW_10_6_1_patch2
cd CMSSW_10_6_1_patch2/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline phase2-l1t-integration-CMSSW_10_6_1_patch2
git cms-merge-topic -u cms-l1t-offline:l1t-phase2-v2.34.0
git pull https://github.com/pozzobon/cmssw.git DTHough_NP_20190625_106X_L1Tbranch

scramv1 b -j 8
```

**Comment by rekovic** [comment]
Attn @battibass

**Pull request closed without merging**
