### PR TITLE
Update the TTTrack_TrackWord DataFormat

### PR DESCRIPTION
**Pull request by aperloff**
#### PR description:

Update the TTTrack_TrackWord DataFormat and to the latest digitization parameters as specified in the corresponding [Phase 2 L1Trigger interface document](https://www.overleaf.com/read/ddsnkprgjmnp). The specifications have been agreed upon by the track trigger and the L1Trigger project leads. Besides these changes, there are some additional small changes which were implemented during https://github.com/cms-sw/cmssw/pull/32574 and https://github.com/cms-sw/cmssw/pull/32859.

#### PR validation:

This PR was created by doing:
```bash
cmsrel CMSSW_11_1_7
cd CMSSW_11_1_7/src
cmsenv
git-cms-init
git-cms-checkout-topic -u cms-l1t-offline:phase2-l1t-integration-CMSSW_11_1_7
git cms-addpkg L1Trigger/L1TMuon
git clone -u official-cmssw:phase2-l1t-integration-CMSSW_11_1_7 https://github.com/cms-l1t-offline/L1Trigger-L1TMuon.git L1Trigger/L1TMuon/data
git cms-addpkg  L1Trigger/TrackTrigger
git cms-addpkg SimTracker/TrackTriggerAssociation
git checkout -b phase2-l1t-integration-CMSSW_11_1_7-TTTrackTrackWordUpdate
```
and then manually adding the changed files to avoid issues with the divergent histories of cms-l1t-offline/cmssw and cms-sw/cmssw.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This is a backport of https://github.com/cms-sw/cmssw/pull/34550. It is needed so that we can continue development within cms-l1t-offline/cmssw while we wait for more PRs to be merged into cms-sw/cmssw.

@tomalin @skinnari @emacdonald16

### CODE REVIEW

**Comment by gpetruc** [comment]
Hi,

Will it also did the issues of the digitization bias & the filling of phi
in local coordinates that we discussed in github in the past?

Giovanni

Il Lun 19 Lug 2021, 23:39 Alexx Perloff ***@***.***> ha
scritto:

**Comment by aperloff** [comment]
@gpetruc, I tried to follow the previous conversation when it was taking place. However, I don't remember seeing a concrete recommendation. Do you have:
1. A recommendation for how to "fix" the digitization bias?
2. A recommendation for where to modify the filling of phi?
Remember, any change we make also needs to be approved by the track trigger team, so I will need to run those modifications by them.

The other point I'd like to make is that this is a backport of some features introduced in cms-sw/cmssw. It would be more appropriate to but the changes you are asking for in a separate PR; just to keep the PR topics separate.

**Comment by tomalin** [comment]
For reference, the previous discussion on the digitization recipe can be found at https://github.com/cms-l1t-offline/cmssw/pull/896#discussion_r636079432 . I believe Thomas, Giovanni & I all ended up in agreement about the recipe.

**Comment by aperloff** [comment]
@tomalin @gpetruc Please correct me if I'm wrong, but what I got out of the previous discussion (https://github.com/cms-l1t-offline/cmssw/pull/896#discussion_r636079432) was:
1. I should move the `std::abs` from https://github.com/cms-l1t-offline/cmssw/pull/938/files#diff-a2f9e944733440cb6cd7bf9d7a1aa5426419ac783592f50e8c00e7a382178e5aR257 in `digitizeSignedValue` outside of the `std::floor` operation.
  - This is more of a note for me, but whatever I do I will want to tell Chris to replicate at https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-CMSSW_11_1_7/L1Trigger/L1TTrackMatch/interface/L1TkEtMissEmuAlgo.h#L101.
2. For `unpackSignedValue` I don't see anything wrong and there never was any concrete recommendation.
  - Again, this is a note for me: Chris will want to also make updates to his code if that is what we decide (https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-CMSSW_11_1_7/L1Trigger/L1TTrackMatch/src/L1TkEtMissEmuAlgo.cc#L34).
3. For the setting of phi:
  - The `setTrackWord` function with ap_uint arguments just sets bits. The `setTrackWord` function with unsigned int inputs does a type conversion and then passes off the work to the version with ap_uint arguments. I think it's safe to assume that no conversions will be done here and that these functions will take in local phi. Neither of them are used in TTTrack.h anyway, so we have more control over how they will be used. I can add a comment in both TTTrack_TrackWord.h and TTTrack_TrackWord.cc to make sure it's clear that these functions take in local phi.
  - Shall we assume the `setTrackWord` function taking in a `GlobalVector` is taking in global phi and that the conversion needs to be done somewhere in https://github.com/cms-l1t-offline/cmssw/pull/938/files?file-filters%5B%5D=.cc#diff-6e795a8c5ee6eae0757f2898b146a5f1614067afedca66b20785518e915e4891R56-R64? If so, we will need to send in the sector index (`phiSector()`) as an argument and then do something equivalent to https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-CMSSW_11_1_7/L1Trigger/L1TTrackMatch/src/L1TkEtMissEmuTrackTransform.cc#L42-L60. Does this sound about right?

**Comment by rekovic** [comment]
merging as is, to reflect the changes introduced in the central CMSSW.

Any additional changes as a follow up to the above discussion are to come in additional PRs, both to cms-l1t-integration and CMSSW.

**Pull request merged**
