### PR TITLE
L1track jet emulator update (backport of PR40563)

### PR DESCRIPTION
**Pull request by epalencia**
This PR includes the updated trackjet emulation code. The new code has a different structure and uses common functions between emulator and simulation. This way we are sure that exactly the same code is run in both cases and the only difference is in the inputs. The code was presented in the GTT meeting:

- https://indico.cern.ch/event/1203796/
- https://indico.cern.ch/event/1211843/

Backport of https://github.com/cms-sw/cmssw/pull/40563: Had to modify `L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker_cfg.py` to solve conflicts due to different geometry (favoring D88 instead of D49).

This PR supersedes https://github.com/cms-l1t-offline/cmssw/pull/1116

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR failed.

The following is the stderr of the compilation attempt:
```
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc: In constructor 'L1TrackNtupleMaker::L1TrackNtupleMaker(const edm::ParameterSet&)':
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:258:90: warning: 'edm::EDAnalyzer::EDAnalyzer()' is deprecated [-Wdeprecated-declarations]
  258 | L1TrackNtupleMaker::L1TrackNtupleMaker(edm::ParameterSet const& iConfig) : config(iConfig) {
      |                                                                                          ^
In file included from /tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:11:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EDAnalyzer.h:43:20: note: declared here
   43 |     CMS_DEPRECATED EDAnalyzer();
      |                    ^~~~~~~~~~
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc: In member function 'virtual void L1TrackNtupleMaker::analyze(const edm::Event&, const edm::EventSetup&)':
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:671:61: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<TrackerGeometry>]' is deprecated [-Wdeprecated-declarations]
  671 |   iSetup.get<TrackerDigiGeometryRecord>().get(geometryHandle);
      |                                                             ^
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetup.h:33,
                 from /tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:14:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetupRecord.h:110:27: note: declared here
  110 |       CMS_DEPRECATED bool get(HolderT& iHolder) const {
      |                           ^~~
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:674:51: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<TrackerTopology>]' is deprecated [-Wdeprecated-declarations]
  674 |   iSetup.get<TrackerTopologyRcd>().get(tTopoHandle);
      |                                                   ^
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetup.h:33,
                 from /tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:14:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetupRecord.h:110:27: note: declared here
  110 |       CMS_DEPRECATED bool get(HolderT& iHolder) const {
      |                           ^~~
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:677:58: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<TrackerGeometry>]' is deprecated [-Wdeprecated-declarations]
  677 |   iSetup.get<TrackerDigiGeometryRecord>().get(tGeomHandle);
      |                                                          ^
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetup.h:33,
                 from /tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:14:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetupRecord.h:110:27: note: declared here
  110 |       CMS_DEPRECATED bool get(HolderT& iHolder) const {
      |                           ^~~
/tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:680:65: warning: 'bool edm::eventsetup::EventSetupRecord::get(HolderT&) const [with HolderT = edm::ESHandle<MagneticField>]' is deprecated [-Wdeprecated-declarations]
  680 |   iSetup.get<IdealMagneticFieldRecord>().get(magneticFieldHandle);
      |                                                                 ^
In file included from /cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetup.h:33,
                 from /tmp/palencia/pr_1117/new/src/L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker.cc:14:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EventSetupRecord.h:110:27: note: declared here
  110 |       CMS_DEPRECATED bool get(HolderT& iHolder) const {
      |                           ^~~
/tmp/palencia/pr_1117/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc: In constructor 'L1PhaseIITreeProducer::L1PhaseIITreeProducer(const edm::ParameterSet&)':
/tmp/palencia/pr_1117/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:189:78: warning: 'edm::EDAnalyzer::EDAnalyzer()' is deprecated [-Wdeprecated-declarations]
  189 | L1PhaseIITreeProducer::L1PhaseIITreeProducer(const edm::ParameterSet& iConfig) {
      |                                                                              ^
In file included from /tmp/palencia/pr_1117/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:25:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EDAnalyzer.h:43:20: note: declared here
   43 |     CMS_DEPRECATED EDAnalyzer();
      |                    ^~~~~~~~~~
/tmp/palencia/pr_1117/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc: In member function 'virtual void L1PhaseIITreeProducer::analyze(const edm::Event&, const edm::EventSetup&)':
/tmp/palencia/pr_1117/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:370:9: warning: unused variable 'Z0' [-Wunused-variable]
  370 |   float Z0 = *z0Puppi;
      |         ^~
{standard input}: Assembler messages:
{standard input}:45560: Warning: end of file not at end of a line; newline inserted
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
gmake: *** [config/SCRAM/GMake/Makefile.rules:1712: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o] Error 1
gmake: *** Waiting for unfinished jobs....

```
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`2`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR failed.

The following is the stderr of the compilation attempt:
```
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o: warning: relocation against `.LC192' in read-only section `.text._ZN11Phase2L1GMT9Isolation22isolation_allmu_alltrkERSt6vectorIN3l1t11TrackerMuonESaIS3_EERS1_INS_16ConvertedTTTrackESaIS7_EE[_ZN11Phase2L1GMT9Isolation22isolation_allmu_alltrkERSt6vectorIN3l1t11TrackerMuonESaIS3_EERS1_INS_16ConvertedTTTrackESaIS7_EE]'
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o: in function `Phase2L1TGMTProducer::~Phase2L1TGMTProducer()':
Phase2L1TGMTProducer.cc:(.text+0x824): undefined reference to `vtable for Phase2L1TGMTProducer'
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o: in function `Phase2L1TGMTProducer::Phase2L1TGMTProducer(edm::ParameterSet const&)':
Phase2L1TGMTProducer.cc:(.text+0x1bbf): undefined reference to `vtable for Phase2L1TGMTProducer'
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o: in function `Phase2L1TGMTProducer::produce(edm::Event&, edm::EventSetup const&)':
Phase2L1TGMTProducer.cc:(.text+0x2966): undefined reference to `.LC206'
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o: relocation R_X86_64_PC32 against undefined symbol `.LC206' can not be used when making a shared object; recompile with -fPIC
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/gcc/10.3.0-84898dea653199466402e67d73657f10/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
gmake: *** [config/SCRAM/GMake/Makefile.rules:1712: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/libPhase2L1GMTPlugins.so] Error 1
gmake: *** Waiting for unfinished jobs....

```
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`2`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by BenjaminRS** [comment]
I had a quick look through and it looks good to me. Thanks @epalencia 
I do not know why the first 2 attempts to compile the PR failed and it worked on the third attempt?

**Comment by epalencia** [comment]
> I had a quick look through and it looks good to me. Thanks @epalencia I do not know why the first 2 attempts to compile the PR failed and it worked on the third attempt?

I believe it was a temporary issue (I had other problems in other PRs as well...). I just resubmitted exactly the same scripts without changing anything in the code.

**Comment by gkaratha** [comment]
+1

**Comment by epalencia** [comment]
Tagged as _**l1t-phase2-v60**_.

**Pull request merged**
