### PR TITLE
Update Correlator layer 1 barrel "TDR" regionizer emulator

### PR DESCRIPTION
**Pull request by gpetruc**
#### PR description:

This PR propagates to cms-l1t-offline two correlator updates to the Barrel "TDR" regionizer, from @jmitrevs:
 * https://github.com/p2l1pfp/cmssw/pull/112
 * https://github.com/p2l1pfp/cmssw/pull/116

Note that the default configuration of the correlator emulator is running the "ideal" regionizer in the barrel, so no changes at all are expected in the physics output with this PR. 
A switch to the "TDR" emulator in the default configuration may happen in a later PR after physics validation.

It also brings the head of the correlator fork mostly up to date to cms-l1t-offline.

Apologies for the number of commits, but we can't do any rebase of it in this branch since the first of the two PRs was merged on our side quite some time ago before we started synchronizing with cms-l1t-offline and cms-sw/master for all individual PRs 

#### PR validation:

 * passes standard code checks
 * L1Trigger/Phase2L1ParticleFlow/test/make_l1ct_binaryFiles_HGCTest_cfg.py runs successfully
 * correlator-common CI runs successfully
 * in the CMSSW master version, RelVal matrix workflow 23234.0 runs

#### CMSSW master PR

https://github.com/cms-sw/cmssw/pull/41838

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by epalencia** [comment]
Tagged as `l1t-phase2-v69`.

**Pull request merged**
