### PR TITLE
BMTF Inputs in the ntuples

### PR DESCRIPTION
**Pull request by gflouris**
BMTF Inputs added in the ntuples.
L1AnalysisL1UpgradeTfMuon also modified in order to write out the track address and the number of the wheel.

I have only tested with test_UpgradeTfMuonProducer.py. It is producing the expected results.

### CODE REVIEW

**Comment by rekovic** [comment]
@gflouris  When merged, it does not compile, can you please take a look

<pre>
cmsrel CMSSW_8_0_2
cd CMSSW_8_0_2/src
cmsenv
git cms-init 
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic -u cms-l1t-offline:l1t-integration-CMSSW_8_0_2
git checkout -b gflouris-mydevel802_ntuples l1t-integration-CMSSW_8_0_2
git pull https://github.com/gflouris/cmssw.git mydevel802_ntuples
scramv1 b -j 8
</pre>

Errors...

<pre>
>> Compiling  /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_2_l1t_integration_2/src/L1Trigger/L1TNtuples/src/L1AnalysisL1UpgradeTfMuon.cc 
gmake: *** [tmp/slc6_amd64_gcc493/src/L1Trigger/L1TNtuples/src/L1TriggerL1TNtuples/a/L1TriggerL1TNtuples_xr.cc] Error 1
gmake: *** Waiting for unfinished jobs....
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
</pre>

**Comment by gflouris** [comment]
@rekovic I get the same error when compiling a different file. Then try scram b -j6, same error different file. Then scram b -j4 and it works.

**Comment by rekovic** [comment]
@gflouris Thanks. Also, compiling twice with 'scramv1 b -j 8' works too.

**Comment by bortigno** [comment]
@rekovic @mulhearn  can we merge this one too so we have more information about the muons in our ntuples? thanks

**Comment by mulhearn** [comment]
This is merged into v84.0

**Pull request closed without merging**
