### PR TITLE
caloParams_2023_v0_3 to use latest L1T JEC 2023_v0

### PR DESCRIPTION
**Pull request by siddhesh86**
A new configuration file caloParams_2023_v0_3_cfi.py (copied from caloParams_2023_v0_2_cfi.py) and updating to read JEC LUT [PR-18](https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter/pull/18), which is deployed online on June 11, 2023. 

This PR depends upon  [PR-18](https://github.com/cms-l1t-offline/L1Trigger-L1TCalorimeter/pull/18).
The JEC LUTs were discussed on [JIRA-CMSLITDPG-1147](https://its.cern.ch/jira/browse/CMSLITDPG-1147).

This PR expects changes in L1T jet PU subtraction scheme (phi-ring) and JEC only.

### CODE REVIEW

**Comment by aloeliger** [comment]
Hi @siddhesh86 Is this urgent? This is a situation that hasn't come up before in my testing script, which is PRs dependent on a an external data file. I would like the chance to try and modify them for that. Is there any reason that this cannot wait?

**Comment by siddhesh86** [comment]
Hi @aloeliger, the L1T JEC LUTs have already been deployed online this week and data have been taken with using the LUTs since then. So the PR is not very urgent. Just that this PR will bring L1T online and offline repositories in sync.

**Comment by aloeliger** [comment]
Okay, @bundocka Actually needs these PRs ASAP and I haven't had the time to consider recipes with externals. So I will go ahead and merge this, and the requisite data PR.

**Comment by aloeliger** [comment]
Tagged as `l1t-integration-v157`

**Pull request merged**
