### PR TITLE
phase 2 DT Trigger Primitives

### PR DESCRIPTION
**Pull request by camilocarrillo**
- The first pull request for the phase-2 Trigger Primitives with the Analytical Method.
- Performance studies with satisfactory results have been done comparing with offline reconstructed segments with data (2016 and 2017 ) and MonteCarlo with PU200.
- Several grouping options are included as several filters. 
- This version of the code follows the current FPGA firmware running in the demostrator at P5 and good agreement has also been observed.
- The phase-2 dataformat is also included in this pull request but this part should

### CODE REVIEW

**Comment by folguera** [comment]
This is superseeded by #790

**Comment by rekovic** [comment]
obsolete

**Comment by camilocarrillo** [comment]
Hi Vladimir @rekovic,
I have just seen you marked the pull request as obsolete two weeks ago. In fact last week during our first meeting TPs-TrackFinder Michalis asked us to merge this PR to your L1 branch. Is it possible to re open it and merge it?
Thanks!
Camilo

**Comment by folguera** [comment]
@camilocarrillo I think that what we want @rekovic to merge is PR #790 right?

**Comment by camilocarrillo** [comment]
Sorry for the spam, I see another PR supersedes this one

**Pull request closed without merging**
