### PR TITLE
Phase-2 L1T: Fix GT packed format for Correlator e/gamma and tau objects

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

This PR addresses a bug in converting the hardware data format used in the Correlator to the GT one.

The corresponding PR to master is https://github.com/cms-sw/cmssw/pull/43075

### CODE REVIEW

**Comment by aloeliger** [comment]
@cerminar We are trying to use `phase2-l1t-integration-13_3_0_pre3` as the integration branch. Could you please rebase this work there? (Should just be a clean CMSSW_13_3_0_pre3 release before your PR).

Otherwise the content looks fine. @epalencia I see you've commented on the CMSSW version, I will let you sign there. Any comments for here, or should we just merge it once rebased?

**Comment by epalencia** [comment]
Yes, this can be merged once rebased (and master PR is signed already).

**Comment by cerminar** [comment]
> @cerminar We are trying to use `phase2-l1t-integration-13_3_0_pre3` as the integration branch. Could you please rebase this work there? (Should just be a clean CMSSW_13_3_0_pre3 release before your PR).
> 
Done in: https://github.com/cms-l1t-offline/cmssw/pull/1177

**Comment by epalencia** [comment]
I'm closing this PR as the 13_3 rebased version already exists.

**Pull request closed without merging**
