### PR TITLE
L1 Phase2: Use HGCal towers in PF (includes required update to HGCal v2.7.3)

### PR DESCRIPTION
**Pull request by gpetruc**
Enable the use of HGCal trigger towers from the standard HGCal L1 emulator into PF, instead of the hack based on trigger cells that we were using before, plus a few other small improvements to the PF calo clustering algo.

The PR includes the update to the v2.7.3 tag of the HGCal emulator ( @cerminar @jbsauvan @tstreble ), which is needed in order to get correct trigger towers.

### CODE REVIEW

**Comment by rekovic** [comment]
@gpetruc 
 v2.7.3 tag of the HGC is now merged in the integration branch  `phase2-l1t-integration-CMSSW_10_1_7`

**Comment by gpetruc** [comment]
ok will have a look later to see why this is now conflicting.

**Comment by gpetruc** [comment]
Updated to v2.16.21 to solve the spurious github conflict.

**Comment by rekovic** [comment]
@gpetruc 
This is ready for merging now?
Cristina B. mentioned you had some last minute changes.....   but that might be unrelated.

**Comment by gpetruc** [comment]
Ready for merging. What I mentioned to Cristina is whether they could
re-make rates with this version of the PF code.

**Pull request merged**
