### PR TITLE
From cmssw 9 3 2 displaced muon dev

### PR DESCRIPTION
**Pull request by dildick**
No change to existing algorithms. In this PR I made a few fixes to ensure that the displaced L1Mu producer can run in the main L1Mu sequence. Following PRs will fill bits and pieces of algorithm

### CODE REVIEW

**Comment by dildick** [comment]
@thomreis  @rekovic can you please merge this PR? I made sure that the BMTF label was updated so it does not crash anymore

**Comment by dildick** [comment]
@rekovic @thomreis can you please comment?

**Comment by dildick** [comment]
@rekovic @thomreis can you please comment?

**Comment by rekovic** [comment]
Hi @dildick 

This does not compile for me.  Can you please have a look. 

Although not introduced in the latest PR, can you please clean up the declared but not used variables 
`const auto& gp`, 
`float minDR_L1Mu_ME0`,
`const float muon_sign`
which give warnings.

**Comment by dildick** [comment]
the compilation errors are fixed. Could you please merge it?

**Comment by rekovic** [comment]
still failing for me

```
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_3_2-Phase2/src/L1Trigger/L1TMuon/src/Phase2/L1TDisplacedMuonStubRecovery.cc: In member function 'bool L1TMuon::L1TDisplacedMuonStubRecovery::stubInEMTFTrack2016s(const CSCCorrelatedLCTDigi&, const EMTFTrack2016Collection&) const':
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_3_2-Phase2/src/L1Trigger/L1TMuon/src/Phase2/L1TDisplacedMuonStubRecovery.cc:161:41: error: passing 'const l1t::EMTFTrack2016' as 'this' argument discards qualifiers [-fpermissive]
     for (const auto& hit : tftrack.Hits()){
                                         ^
In file included from /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_3_2-Phase2/src/L1Trigger/L1TMuon/src/Phase2/L1TDisplacedMuonStubRecovery.h:17:0,
                 from /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_9_3_2-Phase2/src/L1Trigger/L1TMuon/src/Phase2/L1TDisplacedMuonStubRecovery.cc:1:
/cvmfs/cms.cern.ch/slc6_amd64_gcc630/cms/cmssw/CMSSW_9_3_2/src/DataFormats/L1TMuon/interface/EMTFTrack2016.h:43:27: note:   in call to 'l1t::EMTFHit2016Collection l1t::EMTFTrack2016::Hits()'
     EMTFHit2016Collection Hits()       { return _Hits; }
                           ^~~~
```

**Comment by dildick** [comment]
@rekovic shoot. I must have modified that function myself and not update the branch. Anyway, perhaps we should consider building on top of a more recent CMSSW release. I don't think I want to use the EMTF2016 collections.

**Comment by dildick** [comment]
to be honest, I'd rather to all this development in cms-sw, where the bot can do automatic testing and such...

**Comment by rekovic** [comment]
> Anyway, perhaps we should consider building on top of a more recent CMSSW release. I don't think I want to use the EMTF2016 collections.

Do you want to close this PR and open one for 940 branch ?

**Comment by dildick** [comment]
I will open one for 940 soon

**Pull request closed without merging**
