### PR TITLE
EMTF fix 2016 emulation (no RPCs)

### PR DESCRIPTION
**Pull request by abrinke1**
@thomreis @jiafulow : This should fix bad EMTF re-emulation for 2016 in RPC coverage region:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_run2016B-H_SingleMuon_ZMu-skim_33fb-1_i96p17/

@kkotov @rekovic : This should also fix Global Tag / O2O / Conditions DB problem described here:
https://github.com/cms-l1t-offline/cmssw/issues/583

@thomreis can you check this before it gets pulled in?  Maybe run over a couple runs (early 2016, late 2016), and see if the agreement is OK?  Or run over the whole year, if that's simpler for you.

You should be able to pull in these changes via this command:
git cms-merge-topic -u abrinke1:EMTF_May_2017_merge

### CODE REVIEW

**Comment by jiafulow** [comment]
Hi Andrew,

How does this fix the problem exactly besides simply setting RPCEnable to False for 2016? I also doubt there is a use case of keeping and converting the RPC hits when running in the 2016 configuration. 

Also, introducing a 'valid' flag in the RPC hit, which you have set to false, and convert it to an EMTF hit with a 'valid' flag set to true, is dangerous in my opinion. Especially since a 'valid' flag has a very specific meaning in the firmware, typically used when you have a fixed-size array of things, and you want to use a flag to mark which index has valid/real information, and which doesn't/is only an empty reserved space. Also, I typically only keep things that are valid, and you can see that I actively delete everything that is set to invalid in the firmware.

A minor comment on the bug related to the same bank address in the pT LUT. I remember I have already sent you the fix for that. (should be a minor effect).

Jia Fu

*edit: added comment on RPC valid flag.

**Comment by abrinke1** [comment]
Hi Jia Fu,

Setting RPCEnable to false is the main fix.  I also added the thetaWindow, which is important:

https://github.com/cms-l1t-offline/cmssw/pull/591/files#diff-6df04c2d27531c39d9694ff2c483b075R132

While doing that, I also decided to add the full set of "legacy" 2016 parameters, in case we change the defaults for other configurables in the future.

Keeping all clustered RPC hits (CPPF digis) in the EMTFHitCollection, even if there is a CSC LCT in the corresponding CSC chamber, is important because we need it for data-emulator comparisons.  We unpack all the hits received from CPPF, but then only some are used in the track-building.

The "valid" flag is probably not the best thing to use, as you say.  Do you have another suggestion?  The reason I had to add it to the RPCData rather than, say, the EMTFHit class, is that we're at the point in the code where you look for CSC chambers that correspond to RPC chambers, we don't have EMTFHits yet - just the trigger primitives.

Also, thanks for reminding me about the bank address code.  I need to go back and look at those emails you sent me a few weeks ago, also about the strip number in cancel-out.

Best,
Andrew

**Comment by jiafulow** [comment]
Hi Andrew,

Yes, `thetaWindow` should have been included in the `if (fw_version < 50000)` block for 2016. Although I'd have preferred to add just that one parameter. Every time the default changes, I would just add one more. It's something one would have to remember to do anyway whenever there is a new parameter. But I can also see why you want to hardcode all the legacy values, since they are legacy values, so it's ok.

In my original comment, I misunderstood what you are trying to do with the changes in PrimitiveSelection.cc. But I think I understand now, I need to think about this. (Though, this is kind of unrelated to the issue Thomas reported).

Regarding the bank address code, it was just a comment/reminder. Not saying you have to include it now. Let's push everything into CMSSW first, which is what you and others are already doing, and then we can make incremental changes after that.

Cheers,
Jia Fu

**Comment by thomreis** [comment]
I have launched the ntuple production for runs 2016B and 2016H with the fix of @abrinke1 . No other changes have been applied.

**Comment by thomreis** [comment]
Looks like it takes the values from fake parameters
Run number: 278820 fw_version: 123456 pt_lut_version: 7 pc_lut_version: 1

**Comment by abrinke1** [comment]
Hmm ... interesting.  To be investigated.  Probably Monday.

**Comment by jiafulow** [comment]
Hi Andrew,

Would this help with the problem that you are trying to solve regarding keeping all the RPC hits for data-emulator comparisons?
https://github.com/jiafulow/cmssw/commit/2477f4cc3

In the commit, I create a new collection called `inclusive_conv_hits` to keep all the hits without truncation, and write out that collection. The original `conv_hits` collection continues to be used as usual, so you don't have to modify the subsequent steps. I think it's simpler this way, and also helps with how I'm handling new extra hits in the Phase 2 simulation. 

But if you insist on what you currently have, it's ok too. I misunderstood what you are trying to do in my original comment. Just be careful not to unintentionally change the `pc_segment` value.

Jia Fu

**Comment by thomreis** [comment]
95% of the crab jobs crash with error 134:
```
== CMSSW: cmsRun: /afs/cern.ch/work/t/treis/ugmt/ntuple/CMSSW_9_2_5_patch2/src/L1Trigger/L1TMuonEndCap/src/PrimitiveConversion.cc:78: void PrimitiveConversion::process(const std::map<int, std::vector<L1TMuon::TriggerPrimitive> >&, EMTFHitCollection&) const: 
Assertion `pc_segment <= 4' failed.
```

**Comment by jiafulow** [comment]
The assertion in L1Trigger/L1TMuonEndCap/src/PrimitiveConversion.cc line 78 can be removed.

It fails now because of the changes Andrew made in PrimitiveSelection.cc, which is unrelated to the original issue. The change causes the number of EMTF hits to be possibly more than 4 in a chamber, with the extra ones marked by the new valid flag (and set to false). It's safe to remove the assertion.

**Comment by abrinke1** [comment]
@thomreis I'll take a look at the pc_segment error as well.  Please don't re-run with the assertion commented out; there are at least 2 things wrong, so I should fix them properly first.

@jiafulow Your solution looks good - I'll try implementing it.

**Comment by abrinke1** [comment]
Please see my last comment on issue #583 .  I've created a new branch [1] to try to debug this, but I think it will need some examination by @kkotov .  It contains the changes from @jiafulow as well, and the pc_segment error fix.

[1] https://github.com/abrinke1/cmssw/tree/EMTF_July_2017_conditions_fix

**Comment by abrinke1** [comment]
Superseded by PR #604 , incorporating Jia Fu's comments.  Many of the problems discussed in issue #583 still need to be addressed, in particular a central mechanism to configure for 2016 or 2017 emulation.

**Pull request closed without merging**
