### PR TITLE
New Attempt to fix uGT emulator bug for evaluation of conditions for displaced muons

### PR DESCRIPTION
**Pull request by cavana**
#### PR description:

  - This PR is needed to fix a bug in the evaluation of displaced muon conditions in MuConditions.cc
  - This PR replaces a previous PR, which had a conflict that was incorrectly resolved using the GitHub editor.
  - There are no changes to output expected

#### PR validation:

The updated MuConditions.cc file compiles correctly and has been tested using runTheMatrix test workflow, and test vectors agree with firmware.

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

This PR is not a backport.

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by rekovic** [comment]
@cavana This PR has conflicts too !

**Comment by cavana** [comment]
@rekovic Indeed it had conflicts, but I resolved those conflicts.  Indeed, when I view this PR on GitHub, I do not see any conflicts to resolve anymore.  But,  I do see that a review is required.

**Comment by rekovic** [comment]
please do not resolve conflicts on the git hub, but resolve them locally, commit the changes, and push the local branch to the offline repository.

**Review by rekovic — APPROVED** [review]

**Comment by rekovic** [comment]
@cavana 
This PR can be closed now.

**Pull request closed without merging**
