### PR TITLE
Config customise updates

### PR DESCRIPTION
**Pull request by thomreis**
- Change the OMTF emulator input to emtfStage2Digis since csctf is not read out anymore this year.
- Add # to prints in order to produce an executable python configuration with edmConfigDump.

### CODE REVIEW

**Comment by abrinke1** [comment]
Technically this should be era-dependent: csctfDigis for 2016, emtfStage2Digis for 2017.  The difference should be fairly small, and I don't know if L1TReEmulFromRAWCalouGT is used for re-emulating 2016 data, but if it's a simple thing to change, I would.

**Comment by thomreis** [comment]
There is a L1TReEmulFromRAW2016 that sets csctf as input.
The twiki says L1TReEmulFromRAWCalouGT is for 2016 and 2017 data so an additional way to distinguish is necessary in this case.

**Comment by abrinke1** [comment]
Then I would propose making two sequences: "L1TReEmulFromRAWCalouGT" which uses "L1TReEmulFromRAW", and "L1TReEmulFromRAWCalouGT2016" which uses "L1TReEmulFromRAW2016".  And the twiki should be updated to indicate "2016" usage for 2016 data.

**Comment by rekovic** [comment]
@thomreis @abrinke1 Thx.
Proliferation of number of sequences quickly becomes difficult to maintain manually. 
We should be able to use eras flag `run2_2016` and `run2_2017` to switch between the two.
I will take a look.

**Comment by rekovic** [comment]
@abrinke1 
Do EMTF experts prefer to use cscDigis over emtfDigis for re-emulation of 2016 EMTF data?

**Comment by abrinke1** [comment]
EMTF prefers emtfStage2Digis for re-emulating 2016 data.  The reason OMTF prefers csctfDigis is that there were occasional MPC-EMTF transmission inefficiencies (linked to hard resets), which did not affect the MPC-OMTF transmission or the MPC-CSCTF transmission.  So the OMTF gets slightly better data-emulator agreement with csctfDigis.

Thanks,
Andrew

**Pull request merged**
