### PR TITLE
Propagate correlator developments to cms-l1t-offline

### PR DESCRIPTION
**Pull request by gpetruc**
This PR will synchronize the developments that had been merged to the correlator branch (p2l1pfp) to cms-l1t-offline.
It's still under testing and may need a few updates for open PRs in p2l1pfp that we may merge before this sync.

@cerminar

### CODE REVIEW

**Comment by gpetruc** [comment]
Hi @cecilecaillol @epalencia from my side this PR is ready for you to review.
Also, let me know if you would like me to prepare a rebased version of this to go to CMSSW master

**Comment by cbotta** [comment]
Hi @gpetruc @cerminar, could you please comment on the expected performance expected with this PR? 
The MC will likely happen in early fall in 12-5, but we weren't planning a new Menu validation after merging the new incoming PR. What do you think?

**Comment by gpetruc** [comment]
What I can say is:
 * PF muon efficiency will be significantly higher: this has essentially no downstream effect since nobody uses PF muons in the menu, and the second-order effects on jets & met are tiny
 * Emulation of the layer 1 barrel will be more accurate as we'll be running the bitwise accurate emulator for the track propagation & parameter conversion instead of the current floating point code: makes no visible difference in PF, but may reduce electron efficiency by a small amount

**Comment by gpetruc** [comment]
Just to clarify: we're not asking for this PR to go into this MC production, only for it to be integrated in the cms-l1t-offline (and potentially in CMSSW master to avoid complains about huge PRs when the cms-l1t-offline will be pushed to CMSSW in the future)

**Comment by epalencia** [comment]
Tagged as **l1t-phase2-v3.4.37**.

**Pull request merged**
