### PR TITLE
L1TCalo speedup

### PR DESCRIPTION
**Pull request by jimbrooke**
This is a proposed change to Layer1 calo that will significantly reduce processing time of Layer2 emulator.

I am making the PR so Layer1 team can see the proposal, and EG/Tau team can test it.  Please don't actually merge yet !

### CODE REVIEW

**Comment by SridharaDasu** [comment]
Dear Jim,

Thanks for taking care of this.  I was going to do exactly this.
The only concern is the dependency, which may be considered
backwards by some.

Perhaps, that dependency tree issue is best solved by moving 
L1Trigger/L1TCaloLayer1 to L1Trigger/L1TCalorimeter/L1TCaloLayer1
as was once proposed by Mike Mulhearn.

Regards,
Sridhara

**Comment by jimbrooke** [comment]
I have added one more commit to this branch to fix a mistake in the original PR.  Testing this I get identical results to l1t-integration-v8.0

Regarding the depdency, another option to make it cleaner is to move the caloTowerHash function to a class in DataFormats (which is probably it's proper place).  I'd also be fine with sub-dividing L1T/L1TCalorimeter into L1TCaloLayer1, L1TCaloLayer2, L1TCaloStage1.

Having said all that, if no-one objects to the current dependency I'd like to get this change into the integration branch asap.

**Comment by jimbrooke** [comment]
Also, should we switch the integration branch to use bitwise Layer1 by default?  This would be useful for people doing the object studies, but it would mean Layer 2 output is not valid in this branch (due to overcalibration).  @mulhearn what do you think about this?

**Comment by mulhearn** [comment]
I think it is fine to make this switch.  If people want stability, they have the tsg-tags.  And even if this gets sidetracked for other things urgently needed by TSG, we can just switch back before moving things into the tsg branch.

**Comment by mulhearn** [comment]
Or if you prefer, I can simply make tag vX-calolayer, with it turned on, then turn it back off for vX.

**Comment by jimbrooke** [comment]
any of these is fine with me!

**Comment by SridharaDasu** [comment]
Dear Jim and Mike,

I think DataFormats helper class is the correct location
for this bit of CaloTowerHash utility, to avoid complicated
dependency structure.  I don't know if that change at this
late stage of 8X development will cause grief for Mike.  If
so, I can fully understand not wanting to do that.  We have
enough drama in CMS life as is.  Do whatever is most convenient
that you can go forward with.

Regards,
Sridhara

**Comment by mulhearn** [comment]
Compiles.... Running new automated integration tester now... aaaaaaah...

**Comment by mulhearn** [comment]
this is available, with layer1 on by default, in l1t-integration-v9.0-layer1

**Pull request merged**
