### PR TITLE
Update Correlator to tag l1ct-125x-v1.16

### PR DESCRIPTION
**Pull request by gpetruc**
This is a small update of the correlator CMSSW code, with two new merged PRs from @cerminar:
 * https://github.com/p2l1pfp/cmssw/pull/108
 * https://github.com/p2l1pfp/cmssw/pull/109

The second has been requested by the GT team.

### CODE REVIEW

**Comment by aloeliger** [comment]
@cecilecaillol This was opened before I started in with L1 Offline software. Do we still need this open? Is there any reason this can't be merged? Does it need a central CMSSW PR?

**Comment by cerminar** [comment]
Hello, as far as I can tell, this PR is still needed. The central PR is linked above.
Having this integrated would be helpful for the GT and Correlator integration work.

**Comment by cecilecaillol** [comment]
@aloeliger This can be merged. We were waiting for the previous PR to be merged to cms-sw but it got delayed, no need to wait for it

**Comment by aloeliger** [comment]
@gpetruc As of this morning the earlier correlator tag (v1.14?) has been merged to CMSSW. Because this was used in the development of the GT emulator we need a PR for these commits to central CMSSW as soon as is practical. If additional commits are requested in the review of these things in central CMSSW, we would appreciate them being ported back here. Please also note that because significant changes had to be made to the correlator PR before it was merged, there may be merge conflicts. Let us know if any problems show up.

**Comment by gpetruc** [comment]
do you want the changes that went in cmssw for the older PR be propagated to cms-l1t-offline?

**Comment by aloeliger** [comment]
At this point I don't know. It may be simpler to just move to a fresh phase 2 integration branch when a new production happens. I need think about it and will let you know.

**Comment by gpetruc** [comment]
The PR to CMSSW master is now available: https://github.com/cms-sw/cmssw/pull/41613

**Comment by gpetruc** [comment]
Hello. 
Can this be merged now that it's merged in CMSSW?

**Comment by aloeliger** [comment]
Ahh, yes. Apologies, that slipped by.

**Comment by aloeliger** [comment]
tagged as `l1t-phase2-v62`

**Comment by gpetruc** [comment]
Thanks!

Il Gio 18 Mag 2023, 13:34 Andrew Loeliger ***@***.***> ha
scritto:

**Comment by epalencia** [comment]
Hi @gpetruc , isn't this commit https://github.com/cms-sw/cmssw/pull/41613/commits/5c09c285f7684d713676bc7026afc2aa04dc1089 missing here wrt the master PR?

**Comment by gpetruc** [comment]
Yes, intentionally - that commit changes things to make them more suitable
to the master branch.

**Pull request merged**
