### PR TITLE
EMTF emulator bugfixes to improve data-emulator agreement

### PR DESCRIPTION
**Pull request by abrinke1**
Down to 2% of unpacked tracks missing in re-emulation.  Still issues with discrepant mode and pT assignment, but better than before.  Also process RPC trigger primitives.

### CODE REVIEW

**Comment by bortigno** [comment]
@rekovic @mulhearn  can we merge this one? it is very important for the muon high pt debugging! thanks

**Comment by rekovic** [comment]
@abrinke1 
This does not compile.  Can you please fix it.

```
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_9_l1t_integration/src/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc:45:39: error: 'RPCDetId' does not name a type
   void EMTFHit::ImportRPCDetId( const RPCDetId& _detId) {
                                       ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_9_l1t_integration/src/L1Trigger/L1TMuonEndCap/src/EMTFHitTools.cc:45:55: error: no 'void l1t::EMTFHit::ImportRPCDetId(const int&)' member function declared in class 'l1t::EMTFHit'
   void EMTFHit::ImportRPCDetId( const RPCDetId& _detId) {
....
```

**Comment by abrinke1** [comment]
Strange ... it compiles just fine for me.  Maybe try clean-recompiling DataFormats/, then clean-recompiling L1Trigger/L1TMuonEndCap/?  I see that RPCDetId.h hasn't been touched in ages: https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_9/DataFormats/MuonDetId/interface/RPCDetId.h

**Comment by mulhearn** [comment]
No compile problems for me either.  Running integration tests then I will merge and make tag...

**Comment by abrinke1** [comment]
Actually, before you jump to do that ... I also saw the same compile error when I tried to compile this code in CMSSW_8_0_14.  Previously I was in CMSSW_8_0_9 and there was no problem.  I don't understand why this would be, but I don't want to break everything for anyone else.  Vladimir, what release were you running in?  And for both of you, what release do you use to process the latest data, which was taken in CMSSW_8_0_13_patch1?

**Comment by mulhearn** [comment]
It looks like it might also be breaking integration tests in 809.  Investigating...

**Comment by mulhearn** [comment]
It looks like the new RPCInput just needs the usual overrides when using standard sequences for re-emulating from unpacked RAW.

**Comment by mulhearn** [comment]
I fixed the problems with integration tests in 809.  I'm going to go ahead and make a tag with this included.  We can resolve any problems in ~8_0_14 separately.

**Comment by mulhearn** [comment]
Here's one more weird thing...  I see no effect when re-emulating ~1200 muons in our comparison tests.  What is expected size of effect?  I thought this was few percent effect we are fixing so I was expecting to see ~20 discrepancies...  or maybe do I need to configure something for update to have any effect?

**Comment by abrinke1** [comment]
Hmm ... that is rather strange.  Are you only looking at an eta
distribution?  Maybe try comparing pT or mode/quality, and see if anything
changes.  I would have expected ~20 discrepancies as well.  There's no new
config needed.

**Comment by abrinke1** [comment]
Also, regarding the compile error in 8_0_14 - probably unrelated to the version, you just need to git cms-addpkg DataFormats/L1TMuon and compile it, to get one of the changes.

**Pull request merged**
