### PR TITLE
uGMT muon extrapolation changes

### PR DESCRIPTION
**Pull request by thomreis**
Changed muon coordinate extrapolation LUTs to have 5 bit eta inmut and 7 bit pT input. 
The output width is now 4 bit for eta and phi and the shift has been changed to 0 for eta and 2 for phi.
The eta extrapolation to the vertex was found to be dependent on the detector side and the LUT result is added or subtracted depending on the side.
New optimised eta and phi extrapolation LUTs for these new format are added.

Performance of the new LUTs can be found here:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/extrapolation/muon_extrapolation_histos_5eta_7pt_4out_2outshiftphi_0outshifteta_20170118/

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic don't merge this yet. We want to check first if these changes are feasible in the FW. I made the PR already in case someone wants to try already.

**Comment by thomreis** [comment]
LUTs are here:
https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/commit/1f70ca9ee008f465f8823ad3c615010ca375698c

**Comment by thomreis** [comment]
@rekovic we found that the FW including these changes can be built. Therefore, please go ahead and merge this, including the corresponding LUTs.
Please merge PR https://github.com/cms-l1t-offline/cmssw/pull/462 before this one to keep the right order.

**Comment by rekovic** [comment]
@thomreis Can you please check and resolve the conflicts.

**Comment by thomreis** [comment]
@rekovic try now. But I don't see the LUTs from PR #462 in cms-l1t-offline/L1Trigger-L1TMuon.

**Comment by rekovic** [comment]
@thomreis 
Thanks.
>But I don't see the LUTs from PR #462 in cms-l1t-offline/L1Trigger-L1TMuon.

They should be there
https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/commit/1f70ca9ee008f465f8823ad3c615010ca375698c

**Comment by thomreis** [comment]
There should be a file named microgmt_luts/PhiExtrapolation_6eta_6pt_3out_3outshift_20170217.txt in cms-l1t-offline/L1Trigger-L1TMuon but I don't see it. Its the one from PR #462

**Comment by rekovic** [comment]
It should be there now
https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/commit/3bd07fc0b9413e1049d2e6c717114eaf1f49d236

**Comment by thomreis** [comment]
Looks good, yes. Thanks

**Pull request merged**
