### PR TITLE
Fix bugs in Phi conversion for Phase-2 GMT SAMuons

### PR DESCRIPTION
**Pull request by zhenbinwu**
#### PR description:

It turned out there were problems in the phi conversion from Phase-2 OMTF/EMTF to SAMuons

OMTF: Misunderstanding of Phase-1 local phi vs Phase-2 global phi. Now moved back to Phase-1 local phi conversion
EMTF: A wrong function was called. 

#### PR validation:

A small sample test shows recovery of the SA muon efficiency from OMTF/EMTF

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 2 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc
 - L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTFwdMuonTranslator.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR passes available unit tests!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b runtests`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation

I found a non-zero return code running the relval workflows for this PR!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`1`|
|command|`eval `scramv1 runtime -sh` && runTheMatrix.py --what upgrade -l 26834.78`|

**Comment by aloeliger** [comment]
@zhenbinwu I don't care about the formatting issue at this point frankly. Is this ready to go?

**Comment by zhenbinwu** [comment]
Hi @aloeliger, yes, I am changing this PR to draft as we are working with experts on this.

**Comment by aloeliger** [comment]
Okay. Then I am cutting `v7` without this, and `v8` can be discussed later.

**Comment by epalencia** [comment]
@zhenbinwu, can you please close this PR if included already in https://github.com/cms-l1t-offline/cmssw/pull/1247?

**Comment by zhenbinwu** [comment]
OK， close this PR

**Pull request closed without merging**
