### PR TITLE
uGT emulator code for hadronic shower triggers for Run-3

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

This PR is a first attempt to include the core code for the uGT emulator for hadronic shower triggers for Run-3. In previous PRs I introduced data formats for the CSC, EMTF and uGMT shower objects, and emulators for the CSC trigger, EMTF and uGMT. A new object MuonShower object is introduced in the L1TGlobal emulator and data format packages. This object is treated separately from the regular Muon object. The core code is currently switched off, i.e. the parameter that enables reading muon shower trigger bits from the L1T menu XML file is set to False. As such, there should be no differences in any workflow. The code is based on UTM lib 0.9.X (https://gitlab.cern.ch/cms-l1t-utm/utm), which was recently integrated into CMSSW_12_0_X (cms-sw/cmsdist#7337) and CMSSW_12_1_X (cms-sw/cmsdist#7281).

A few relevant presentations can be found here:

- https://indico.cern.ch/event/1032087/contributions/4334392/attachments/2239866/3798910/HadronicShowerTrigger_EXO_LL_L1DPG_6May2021.pdf
- https://indico.cern.ch/event/1032087/contributions/4334095/attachments/2241349/3800447/HLT_muon_shower_martin.pdf
- https://indico.cern.ch/event/1080450/contributions/4548741/attachments/2320995/3952292/MuonShower_Oct1_Martin.pdf

#### PR validation:

I tested the code on a private XML L1T menu, stripped from the regular trigger algorithms. 

Additional validation with scram b runtests and with WF 11634.0.
```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Fri Oct  1 15:25:09 2021-date Fri Oct  1 14:50:10 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

Before submitting your pull requests, make sure you followed this checklist:
- verify that the PR is really intended for the chosen branch
- verify that changes follow [CMS Naming, Coding, And Style Rules](http://cms-sw.github.io/cms_coding_rules.html)
- verify that the PR passes the basic test procedure suggested in the [CMSSW PR instructions](https://cms-sw.github.io/PRWorkflow.html)

### CODE REVIEW

**Comment by dildick** [comment]
I ran these tests on lxplus
```
scram b runtests
runTheMatrix.py -l limited -i all
```

```
>> Local Products Rules ..... started
>> Local Products Rules ..... done
>> Entering Package L1Trigger/CSCTriggerPrimitives
>> Creating project symlinks
>> Leaving Package L1Trigger/CSCTriggerPrimitives
>> Package L1Trigger/CSCTriggerPrimitives built
>> Tests for package L1Trigger/CSCTriggerPrimitives ran.
>> Entering Package L1Trigger/L1TGlobal
>> Entering Package DataFormats/L1Trigger
>> Entering Package DataFormats/L1TGlobal
------- copying files from src/L1Trigger/L1TGlobal/scripts -------
>> copied import_utm.pl
>> Leaving Package L1Trigger/L1TGlobal
>> Package L1Trigger/L1TGlobal built
>> Tests for package L1Trigger/L1TGlobal ran.
>> Entering Package L1Trigger/L1TMuon
>> Entering Package DataFormats/L1TMuon
>> Leaving Package L1Trigger/L1TMuon
>> Package L1Trigger/L1TMuon built
>> Tests for package L1Trigger/L1TMuon ran.
>> Entering Package L1Trigger/L1TMuonEndCap
>> Leaving Package L1Trigger/L1TMuonEndCap
>> Package L1Trigger/L1TMuonEndCap built
Creating test log file logs/slc7_amd64_gcc900/testing.log
Package L1Trigger/L1TMuonEndCap: Running test TestDebugTools
 
===== Test "TestDebugTools" ====
Running .

OK (1)

---> test TestDebugTools succeeded
TestTime:3
^^^^ End Test TestDebugTools ^^^^
Package L1Trigger/L1TMuonEndCap: Running test TestPhiMemoryImage
 
===== Test "TestPhiMemoryImage" ====
Running ....

OK (4)

---> test TestPhiMemoryImage succeeded
TestTime:2
^^^^ End Test TestPhiMemoryImage ^^^^
Package L1Trigger/L1TMuonEndCap: Running test TestTrackTools
 
===== Test "TestTrackTools" ====
Running ....

OK (4)

---> test TestTrackTools succeeded
TestTime:2
^^^^ End Test TestTrackTools ^^^^
>> Tests for package L1Trigger/L1TMuonEndCap ran.

4.22_RunCosmics2011A+RunCosmics2011A+RECOCOSD+ALCACOSD+SKIMCOSD+HARVESTDC Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:26:45 2021-date Wed Oct 13 18:26:40 2021; exit: 1 0 0 0 0
4.53_RunPhoton2012B+RunPhoton2012B+HLTD+RECODR1reHLT+HARVESTDR1reHLT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:26:45 2021-date Wed Oct 13 18:26:40 2021; exit: 1 0 0 0
5.1_TTbar+TTbarFS+HARVESTFS Step0-PASSED Step1-PASSED  - time date Wed Oct 13 18:36:16 2021-date Wed Oct 13 18:26:41 2021; exit: 0 0
7.3_CosmicsSPLoose_UP18+CosmicsSPLoose_UP18+DIGICOS_UP18+RECOCOS_UP18+ALCACOS_UP18+HARVESTCOS_UP18 Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Wed Oct 13 18:42:19 2021-date Wed Oct 13 18:26:41 2021; exit: 0 0 0 0 0
8.0_BeamHalo+BeamHaloINPUT+DIGICOS+RECOCOS+ALCABH+HARVESTCOS Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:26:48 2021-date Wed Oct 13 18:26:46 2021; exit: 1 0 0 0 0
9.0_Higgs200ChargedTaus+Higgs200ChargedTausINPUT+DIGI+RECO+HARVEST Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:26:48 2021-date Wed Oct 13 18:26:46 2021; exit: 1 0 0 0
25.0_TTbar+TTbarINPUT+DIGI+RECOAlCaCalo+HARVEST+ALCATT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:26:51 2021-date Wed Oct 13 18:26:49 2021; exit: 1 0 0 0 0
135.4_ZEE_13+ZEEFS_13+HARVESTUP15FS+MINIAODMCUP15FS Step0-PASSED Step1-PASSED Step2-PASSED  - time date Wed Oct 13 18:37:32 2021-date Wed Oct 13 18:26:49 2021; exit: 0 0 0
136.731_RunSinglePh2016B+RunSinglePh2016B+HLTDR2_2016+RECODR2_2016reHLT_skimSinglePh_HIPM+HARVESTDR2 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:26:53 2021-date Wed Oct 13 18:26:51 2021; exit: 1 0 0 0
136.7611_RunJetHT2016E_reminiaod+RunJetHT2016E_reminiaod+REMINIAOD_data2016_HIPM+HARVESTDR2_REMINIAOD_data2016_HIPM Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:26:55 2021-date Wed Oct 13 18:26:53 2021; exit: 1 0 0
136.793_RunDoubleEG2017C+RunDoubleEG2017C+HLTDR2_2017+RECODR2_2017reHLT_skimDoubleEG_Prompt+HARVEST2017 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:26:58 2021-date Wed Oct 13 18:26:56 2021; exit: 1 0 0 0
136.8311_RunJetHT2017F_reminiaod+RunJetHT2017F_reminiaod+REMINIAOD_data2017+HARVEST2017_REMINIAOD_data2017 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:00 2021-date Wed Oct 13 18:26:58 2021; exit: 1 0 0
136.8523_RunJetHT2018C_nanoULremini+RunJetHT2018C_nanoULremini+NANOEDM2018_106Xv2+HARVESTNANOAOD2018_106Xv2 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:04 2021-date Wed Oct 13 18:27:01 2021; exit: 1 0 0
136.874_RunEGamma2018C+RunEGamma2018C+HLTDR2_2018+RECODR2_2018reHLT_skimEGamma_Offline_L1TEgDQM+HARVEST2018_L1TEgDQM Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:27:06 2021-date Wed Oct 13 18:27:05 2021; exit: 1 0 0 0
136.88811_RunJetHT2018D_reminiaodUL+RunJetHT2018D_reminiaodUL+REMINIAOD_data2018UL+HARVEST2018_REMINIAOD_data2018UL Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:09 2021-date Wed Oct 13 18:27:07 2021; exit: 1 0 0
140.53_RunHI2011+RunHI2011+RECOHID11+HARVESTDHI Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:11 2021-date Wed Oct 13 18:27:10 2021; exit: 1 0 0
140.56_RunHI2018+RunHI2018+RECOHID18+HARVESTDHI18 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:14 2021-date Wed Oct 13 18:27:12 2021; exit: 1 0 0
158.01_HydjetQ_reminiaodPbPb2018_INPUT+HydjetQ_reminiaodPbPb2018_INPUT+REMINIAODHI2018PPRECOMB+HARVESTHI2018PPRECOMINIAOD Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:16 2021-date Wed Oct 13 18:27:15 2021; exit: 1 0 0
1306.0_SingleMuPt1_UP15+SingleMuPt1_UP15INPUT+DIGIUP15+RECOUP15+HARVESTUP15 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:27:19 2021-date Wed Oct 13 18:27:17 2021; exit: 1 0 0 0
1325.81_TTbar_13_106Xv1NanoAODINPUT+TTbar_13_106Xv1NanoAODINPUT+NANOEDMMC2017_106XMiniAODv1+HARVESTNANOAODMC2017_106XMiniAODv1 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN  - time date Wed Oct 13 18:27:22 2021-date Wed Oct 13 18:27:20 2021; exit: 1 0 0
1330.0_ZMM_13+ZMM_13INPUT+DIGIUP15+RECOUP15_L1TMuDQM+HARVESTUP15_L1TMuDQM+NANOUP15 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:27:24 2021-date Wed Oct 13 18:27:22 2021; exit: 1 0 0 0 0
101.0_SingleElectronE120EHCAL+SingleElectronE120EHCAL Step0-PASSED  - time date Wed Oct 13 18:30:59 2021-date Wed Oct 13 18:27:25 2021; exit: 0
312.0_Pyquen_ZeemumuJets_pt10_2760GeV_2021+Pyquen_ZeemumuJets_pt10_2760GeV_2021+DIGIHI2021MIX+RECOHI2021MIX+HARVESTHI2021PPRECO Step0-FAILED Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:35:07 2021-date Wed Oct 13 18:31:00 2021; exit: 23808 0 0 0
25202.0_TTbar_13+TTbar_13INPUT+DIGIUP15_PU25+RECOUP15_PU25+HARVESTUP15_PU25+NANOUP15_PU25 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:35:10 2021-date Wed Oct 13 18:35:08 2021; exit: 1 0 0 0 0
1000.0_RunMinBias2011A+RunMinBias2011A+TIER0+SKIMD+HARVESTDfst2+ALCASPLIT Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:35:13 2021-date Wed Oct 13 18:35:11 2021; exit: 1 0 0 0 0
1001.0_RunMinBias2011A+RunMinBias2011A+TIER0EXP+ALCAEXP+ALCAHARVDSIPIXELCALRUN1+ALCAHARVD1+ALCAHARVD2+ALCAHARVD3+ALCAHARVD4+ALCAHARVD5 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN Step6-NOTRUN Step7-NOTRUN Step8-NOTRUN  - time date Wed Oct 13 18:35:16 2021-date Wed Oct 13 18:35:14 2021; exit: 1 0 0 0 0 0 0 0 0
10024.0_TTbar_13+2017+TTbar_13TeV_TuneCUETP8M1_GenSimINPUT+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN  - time date Wed Oct 13 18:35:19 2021-date Wed Oct 13 18:35:17 2021; exit: 1 0 0 0 0 0
10042.0_ZMM_13+2017+ZMM_13TeV_TuneCUETP8M1_GenSimINPUT+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN  - time date Wed Oct 13 18:35:21 2021-date Wed Oct 13 18:35:19 2021; exit: 1 0 0 0 0 0
10224.0_TTbar_13+2017PU+TTbar_13TeV_TuneCUETP8M1_GenSimINPUT+DigiPU+RecoFakeHLTPU+HARVESTFakeHLTPU+Nano Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:35:23 2021-date Wed Oct 13 18:35:22 2021; exit: 1 0 0 0 0
10824.0_TTbar_13+2018+TTbar_13TeV_TuneCUETP8M1_GenSimINPUT+Digi+RecoFakeHLT+HARVESTFakeHLT+ALCA+Nano Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN Step5-NOTRUN  - time date Wed Oct 13 18:35:25 2021-date Wed Oct 13 18:35:23 2021; exit: 1 0 0 0 0 0
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:35:27 2021-date Wed Oct 13 18:35:26 2021; exit: 1 0 0 0 0
11634.911_TTbar_14TeV+2021_DD4hep+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-FAILED  - time date Wed Oct 13 19:26:28 2021-date Wed Oct 13 18:35:28 2021; exit: 0 0 0 0 35584
11634.912_TTbar_14TeV+2021_DD4hepDB+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-FAILED  - time date Wed Oct 13 19:24:14 2021-date Wed Oct 13 18:36:17 2021; exit: 0 0 0 0 35584
12434.0_TTbar_14TeV+2023+TTbar_14TeV_TuneCP5_GenSimINPUT+Digi+Reco+HARVEST+ALCA Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:37:34 2021-date Wed Oct 13 18:37:32 2021; exit: 1 0 0 0 0
23234.0_TTbar_14TeV+2026D49+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:37:36 2021-date Wed Oct 13 18:37:35 2021; exit: 1 0 0 0
28234.0_TTbar_14TeV+2026D60+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-PASSED Step1-PASSED Step2-FAILED Step3-NOTRUN  - time date Wed Oct 13 19:31:19 2021-date Wed Oct 13 18:37:36 2021; exit: 0 0 34304 0
34634.0_TTbar_14TeV+2026D76+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+DigiTrigger+RecoGlobal+HARVESTGlobal Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN  - time date Wed Oct 13 18:42:23 2021-date Wed Oct 13 18:42:20 2021; exit: 1 0 0 0
34834.999_TTbar_14TeV+2026D76PU_PMXS1S2PR+TTbar_14TeV_TuneCP5_GenSimHLBeamSpot14INPUT+PREMIX_PremixHLBeamSpot14PU+DigiTriggerPU+RecoGlobalPU+HARVESTGlobalPU Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:42:26 2021-date Wed Oct 13 18:42:23 2021; exit: 1 0 0 0 0
250202.181_TTbar_13UP18+TTbar_13UP18INPUT+PREMIXUP18_PU25+DIGIPRMXLOCALUP18_PU25+RECOPRMXUP18_PU25+HARVESTUP18_PU25 Step0-DAS_ERROR Step1-NOTRUN Step2-NOTRUN Step3-NOTRUN Step4-NOTRUN  - time date Wed Oct 13 18:42:28 2021-date Wed Oct 13 18:42:26 2021; exit: 1 0 0 0 0
7 6 4 3 1 0 0 0 0 tests passed, 32 0 1 0 2 0 0 0 0 failed
```

**Comment by dildick** [comment]
Lot of WFs did not run likely due to DAS errors

**Comment by dildick** [comment]
@Nik-Menendez When you get to producing results for rate with the L1T menu framework, please add the results here.

**Comment by dildick** [comment]
@rekovic Do you have any comments?

**Comment by dildick** [comment]
FYI @giovanni-mocellin

**Comment by jheikkil** [comment]
@rekovic, when can we expect to have these changes merged? The menu team would need this to be in the ntuple recipe to proceed for the trigger review. Thank you!

**Pull request merged**
