### PR TITLE
Omtfdev mk15 b

### PR DESCRIPTION
**Pull request by konec**
Remove RPC packing and unpacking by default, so no external file is needed.
Improve comments in AngleConverter, where CSC offsets computed from available geometry are fixed to that from MonteCarlo GlobalTag.

### CODE REVIEW

**Comment by thomreis** [comment]
Hi @konec 
The unpacked RPCs from the OMTF are used by the DQM [1] and possibly at other places as well. If they are not unpacked anymore the inputs for the DQM need to be changed too.

[1] https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_9_2_8/DQM/L1TMonitor/python/L1TStage2Emulator_cff.py#L69

**Comment by abrinke1** [comment]
@konec @thomreis @rekovic 
Sorry if I've missed some of the discussion on this, but is the only reason for disabling the RPC unpacking the dependence on an external file?  Is there no way to fix this external-file-dependence properly, e.g. by putting it in the L1Trigger/L1TMuon/data directory?  Or are there some complications I'm missing?  If there's an L1T offline software meeting tomorrow, maybe we can discuss it then.

**Comment by rekovic** [comment]
@konec 

I have requested that the payloads from RPCLinkMap.db are uploaded in DB,
which are
```
   0) RPCCPPFLinkMap_v1
   1) RPCDCCLinkMap_v1
   2) RPCLBLinkMap_v1
   3) RPCOMTFLinkMap_v1
   4) RPCTwinMuxLinkMap_v1
```

Would not having ```3) RPCOMTFLinkMap_v1``` solve the problem for your unpacker?

@gkaratha does need ```4) RPCTwinMuxLinkMap_v1``` for proper functioning of the new TwinMux emulator #612

**Comment by konec** [comment]
Please let me know when the RPCLinkMap.db  will be available in GlobalTag (which one).

**Comment by konec** [comment]
@thomreis @rekovic @abrinke1 
I understood that dependence from this map was preventing integration release to include it in cmssw release.

**Comment by thomreis** [comment]
I think it was more in the sense that since it was not there there were exceptions.

**Comment by rekovic** [comment]
@konec
Please leave the part of the PR with Improved comments in AngleConverter, where CSC offsets computed from available geometry are fixed to that from MonteCarlo GlobalTag.
The turning off of RPC unpacking you can remove.  Thanks.

**Comment by rekovic** [comment]
> I understood that dependence from this map was preventing integration release to include it in cmssw release.

We did not want more external data sitting in local directories.  The proper solution is DB.  
Will let you know when in GT.

**Pull request merged**
