### PR TITLE
uGMT and uGT muon packers for Run-3

### PR DESCRIPTION
**Pull request by dinyar**
This PR contains a fixed and extended Muon packer (for both uGT and uGMT).

I have made its configuration era dependent, setting a uGT or uGMT firmware version corresponding to the data taking period in question so compatibility with the unpacker is ensured.
I have also extended the packer to correctly generate the Run-3 muon format if called with the correct era.

Requires the changes to the muon data format from #838 to compile correctly.

Tested with [1], [2], [3], [4]. (Needed to comment out simCscTriggerPrimitiveDigis for the Run3 era with [4].)

@@panoskatsoulis, I can implement similar changes for the regional muon candidates, however I remember a student working on this. Let me know if I should proceed.
@rekovic, please let me know if this is fine or needs any changes.
@thomreis, if you have time could you have a second look at this?

[1] cmsDriver.py L1TEST --python_filename=l1t_test_comp2016.py --conditions=auto:run2_mc -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU
[2] cmsDriver.py L1TEST --python_filename=l1t_test_comp2017.py --conditions=106X_upgrade2018_realistic_v10 -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run2_2017 --mc --no_output --no_exec --filein=root://xrootd-cms.infn.it///store/relval/CMSSW_10_6_1/RelValZMM_13UP18/GEN-SIM-DIGI-RAW-HLTDEBUG/PUpmx25ns_102X_upgrade2018_realistic_v15_ul18hlt_premix_hs-v1/20000/0B9EEA09-CA68-EB44-BBBF-384726C38E5A.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_4 --custom_conditions=HcalChannelQuality_2018_v3.0_mc,HcalChannelQualityRcd,frontier://FrontierProd/CMS_CONDITIONS
[3] cmsDriver.py L1TEST --python_filename=l1t_test_comp2018.py --conditions=106X_upgrade2018_realistic_v10 -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run2_2018 --mc --no_output --no_exec --filein=root://xrootd-cms.infn.it///store/relval/CMSSW_10_6_1/RelValZMM_13UP18/GEN-SIM-DIGI-RAW-HLTDEBUG/PUpmx25ns_102X_upgrade2018_realistic_v15_ul18hlt_premix_hs-v1/20000/0B9EEA09-CA68-EB44-BBBF-384726C38E5A.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_4 --custom_conditions=HcalChannelQuality_2018_v3.0_mc,HcalChannelQualityRcd,frontier://FrontierProd/CMS_CONDITIONS
[4] cmsDriver.py L1TEST --python_filename=l1t_test_compRun3.py --conditions=106X_upgrade2018_realistic_v10 -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run3 --mc --no_output --no_exec --filein=root://xrootd-cms.infn.it///store/relval/CMSSW_10_6_1/RelValZMM_13UP18/GEN-SIM-DIGI-RAW-HLTDEBUG/PUpmx25ns_102X_upgrade2018_realistic_v15_ul18hlt_premix_hs-v1/20000/0B9EEA09-CA68-EB44-BBBF-384726C38E5A.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_4 --custom_conditions=HcalChannelQuality_2018_v3.0_mc,HcalChannelQualityRcd,frontier://FrontierProd/CMS_CONDITIONS

### CODE REVIEW

**Comment by dinyar** [comment]
I updated this PR with modified packers for the regional muon candidates as discussed with @panoskatsoulis. I've modified to GMT packer to take advantage of the changes, but haven't fully done the BMTF packer. For the moment the BMTF packer defaults to the Run-2 format.

To make this work for the BMTF packer too BMTFSetup.cc will still need to be updated analogously to GMTSetup.cc. I didn't want to do this as I wasn't sure if both the BMTF and KBMTF collections should somehow be packed. 

I cherry picked one commit from #768 because I'm still holding out hope we can get this merged too. It would allow significantly easier access to track addresses in the L1TNtuples.

**Comment by rekovic** [comment]
Hi @dinyar, after merging #838, there are conflict.  Can you please take a look.

**Comment by dinyar** [comment]
Hi @vladimir,

thanks for letting me know! I fixed the conficts and tested again locally. Should be fine to merge from my side.

Cheers,
Dinyar

**Comment by rekovic** [comment]
#838 merged and tagged as v104.0
#840 merged and tagged as v104.1

We will need to follow up with another PR to fix crashing in the ntuplization which is already present in the tag v104.0.

Here is an example to reproduce the crash problem.   

This workflow runs fine
```
cmsDriver.py L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root 
```

but adding the ntuplization at the end of the sequence crashes:
```
cmsDriver.py L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMUNoEventTree
```

**Comment by dinyar** [comment]
Hi Vladimir,

thanks for this and letting me know about the crash. I'll have a look and make a new PR to fix it.

Cheers,
Dinyar

**Comment by dinyar** [comment]
Hi @rekovic,

I tried after running `git cms-checkdeps -a` and this works. I'm not sure why it isn't needed for your first command, but I assume it's required due to the changes in the muon data format. Can you confirm?

Cheers,
Dinyar

**Pull request merged**
