### PR TITLE
HW description xml parsing

### PR DESCRIPTION
**Pull request by thomreis**
Update the XmlConfigReader to understand the latest scheme for the xml HW description format.

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic can this be merged soon and eventually go in a new o2o tag that @kkotov can use? The new xml format is deployed at P5 since yesterday and this PR includes the handling of it.

**Comment by rekovic** [comment]
@thomreis There are many conflicts if merging to l1t-integration-807.  Can you please make a separate PR for l1t-integration branch?

**Comment by thomreis** [comment]
@rekovic I was expecting conflicts when merging to the integration branch. But this PR is to the o2o-integration branch. Do you also want to get in sync with the normal integration branch?

**Comment by thomreis** [comment]
I have brought this branch up to date with the latest uGMT developments in the integration branch. The two remaining conflicts with l1t-integration-CMSSW_8_0_7 are from EMTF and uGT.

**Comment by rekovic** [comment]
@thomreis  Hi, it was my impression from

> @rekovic can this be merged soon and eventually go in a new o2o tag that @kkotov can use? The new xml format is deployed at P5 since yesterday and this PR includes the handling of it.

 that you needed this is the integration branch as well.  Is it not the case?  
If not, we then keep it in the O2O branch.   Thanks in any case.

**Comment by thomreis** [comment]
@rekovic no for the moment this is fine only in the O2O branch. @kkotov needs it there.
Merging it with the integration branch would mean merging the whole O2O with the integration branch. I leave it to you to decide when that shall be done. In any case the last merge should make that easier when it will happen.

**Comment by rekovic** [comment]
@thomreis   OK. Thanks. We leave it out of the l1t-integration branch, as originally intended.

**Comment by thomreis** [comment]
The last push also includes the commit from PR https://github.com/cms-l1t-offline/cmssw/pull/328

**Pull request merged**
