### PR TITLE
HI additional plots

### PR DESCRIPTION
**Pull request by vukasinmilosevic**
New plots of Asymmetry and Centrality variables for the HI run.

### CODE REVIEW

**Comment by vukasinmilosevic** [comment]
@davignon @thomreis @rekovic  FYI

**Comment by rekovic** [comment]
Thanks @vukasinmilosevic .
Can you please make this DQM PR straight to CMSSW master branch.

**Comment by vukasinmilosevic** [comment]
Hi, I did. It is under review at the moment.

**Comment by rekovic** [comment]
Thanks!  I see it 24835

**Comment by vukasinmilosevic** [comment]
Sorry, I should have linked it in my previous message!

**Comment by thomreis** [comment]
https://github.com/cms-sw/cmssw/pull/24835

Link to master PR for book keeping.

**Comment by thomreis** [comment]
Hi @vukasinmilosevic 
you can close this PR.

**Pull request closed without merging**
