### PR TITLE
L1 EG HI flags

### PR DESCRIPTION
**Pull request by tstreble**
This PR adds two new flags in caloParams to bypass specifically the L1EG shape ID and the ECAL fine-grain veto to test possible HI settings.
The default configuration is unchanged, with shape ID and FG veto enabled.

### CODE REVIEW

**Comment by tstreble** [comment]
HI people would like this feature to be available in CMSSW
@rekovic : How would you like to proceed for it to be merged?
Should I directly send a PR to CMSSW?

**Comment by rekovic** [comment]
HI @tstreble 
A l1t-integration tag will be provided soon (hopefully today).  That would enable the HI developers
to test.   Or do we prefer to push this to CMSSW urgently for some reason?
If not urgent, I would prefer to have it part of standard systematic PRs to CMSSW.

Best,
Vladimir

**Comment by ttrk** [comment]
Hi @rekovic 
There is no urgency at the moment.
For my info, can you comment how long the standard systematic PR to CMSSW will take ?
Thanks.

**Comment by rekovic** [comment]
@tstreble @ttrk 

I encounter a problem with this PR.  
I have cherry-picked the b582f21 (basically the content of this PR) on top of l1t-integration-CMSSW_10_1_5, and made a branch rekovic/l1t-integration-CMSSW_10_1_5-HI 
The test workflows (example [1]) crash in Module: L1TStage2Layer2Producer:simCaloStage2Digis.

You can reproduce the crash by using CMSSW_10_1_5 and
```
git cms-merge-topic -u rekovic:l1t-integration-v98.10-temp
```
and run [1]

[1]
```
cmsDriver.py L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root
```

Can you please take a look.

**Comment by tstreble** [comment]
Thanks for the report
I'm looking at it

**Comment by tstreble** [comment]
Hmm...
`git cms-merge-topic -u rekovic:l1t-integration-v98.10-temp`
fails with
`error: Server does not allow request for unadvertised object 4552e58ba2c4a72d45931d41b335ced92f5e15cc`
Investigating

**Comment by rekovic** [comment]
Try

```
git remote add rekovic git@github.com:rekovic/cmssw.git
git fetch rekovic l1t-integration-CMSSW_10_1_5-HI l1t-integration-v98.10-temp
```

**Comment by tstreble** [comment]
Ok I needed to add a default getter for the new parameters because the CaloParams is now read from the global tag and the new parameters are not set in that case.
https://github.com/cms-l1t-offline/cmssw/pull/675/files#diff-93d38342ecad5f5ff956ac5285dbda84R148

Considering those parameters are not (yet) included in the firmware, I'm not sure if I should as well update
https://github.com/tstreble/cmssw/blob/8075708b69c08fd55bb2e5c88086bc3f148c620f/L1TriggerConfig/L1TConfigProducers/src/CaloParamsHelperO2O.h
I guess there is somewhere a conversion done to change a CaloParamsHelperO2O object into a standard CaloParamsHelper, such that there is in principle no need to implement it for the O2O.
But in that case, are all the other getter methods in CaloParamsHelperO2O.h really needed?

**Comment by tstreble** [comment]
Adding also bypass flag for H/E following @bundocka 's suggestion

**Comment by rekovic** [comment]
this is now rebased in #708 and merged in `l1t-integration-CMSSW_10_1_5`.
Tagged as `l1t-integration-v99.0`.

**Pull request closed without merging**
