### PR TITLE
Revert NN tau variable mapping

### LINKED ISSUE #1237: P2GT Tau isolation broken in menu
See here:

https://github.com/cms-l1t-offline/cmssw/pull/1225#issuecomment-2031755976

> Hi there @Duchstf @haarigerharald @qvyz, it seems to me that this PR introduced this error:
> 
> ```bash
> ----- Begin Fatal Exception 02-Apr-2024 13:17:39 CEST-----------------------
> An exception of category 'StdException' occurred while
>    [0] Processing  Event run: 1 lumi: 133 event: 37796 stream: 2
>    [1] Running path 'pDoublePuppiTau52_52'
>    [2] Calling method for module L1GTDoubleObjectCond/'DoublePuppiTau5252'
> Exception Message:
> A std::exception was thrown.
> Object doesn't have iso
> ----- End Fatal Exception -----------
> ```
> 
> I took the current IB (from 1h ago, latest commit `8fd467b060c,  Merge pull request #1227 from gkaratha/fix_ht`)
> 
> Could you have a look into this?
> 
> p.s. I guess we would have caught this with the tests for the central CMSSW PR...

### PR DESCRIPTION
**Pull request by HaarigerHarald**
Fixes #1237

### CODE REVIEW

**Comment by artlbv** [comment]
I tested it and it worked fine.

Please merge this ASAP as others can't use the IB.. @aloeliger @epalencia

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR passes available unit tests!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b runtests`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation

I found a non-zero return code running the relval workflows for this PR!|    Info   |     Value    |
|:---------:|:------------:|
|return code|`1`|
|command|`eval `scramv1 runtime -sh` && runTheMatrix.py --what upgrade -l 26834.78`|

**Comment by aloeliger** [comment]
Hmm. The script output is wrong, but the return code is wrong. Let me check.

**Comment by aloeliger** [comment]
HLT overlap. Not this PR's issue.

**Comment by aloeliger** [comment]
@artlbv I am merging this PR.

@HaarigerHarald Could you please open a PR for this to CMSSW as soon as practical?

**Comment by artlbv** [comment]
thanks @aloeliger 

on 
> @HaarigerHarald Could you please open a PR for this to CMSSW as soon as practical?

this should be really included in the same PR as https://github.com/cms-l1t-offline/cmssw/pull/1225#issuecomment-2031755976 so more for @duchstf

**Comment by Duchstf** [comment]
@artlbv Hello, since it was #1225 was merged, how should I proceed? do I need to create a PR?

**Comment by artlbv** [comment]
@Duchstf actually you probably should not do anything.. the P2GT emulator has not been updated in central yet. the PR is on hold: https://github.com/cms-l1t-offline/cmssw/pull/1207

**Comment by aloeliger** [comment]
I really don't want to lose either of these PRs to forgetfulness because we were all so busy with other phase 2 things. We should either:

1.  Revert this and #1225 and immediately reopen a revert-revert to remind us that this is going to go in
2.  Merge this and #1225 in a mini-update to CMSSW immediately. 

This fork is only a convenience. Getting it in CMSSW is what actually matters.

**Comment by artlbv** [comment]
1. is the way to go..
2. will break the current P2GT emulator as it parses the Tau "isolation" for the ID: https://github.com/cms-sw/cmssw/blob/CMSSW_14_0_0_pre3/L1Trigger/Phase2L1GT/python/l1tGTMenu_lepSeeds_cff.py#L395 and fixing this will require the above P2GT PR in CMSSW

**Comment by HaarigerHarald** [comment]
Why not open a PR to central that basically includes both #1225 and #1238 ?

**Comment by aloeliger** [comment]
@HaarigerHarald @Duchstf Ping again on opening a PR to CMSSW combining #1225 and #1238. Please do not lose these changes.

**Comment by HaarigerHarald** [comment]
@Duchstf pls do it as it mostly concerns stuff in the correlator package. You can cherry-pick my commit into your branch and then just open a PR from it.

Edit: I opened a PR now

**Pull request merged**
