### PR TITLE
L1t emtf eff fixes

### PR DESCRIPTION
**Pull request by mulhearn**
This supercedes #274, but note the (2500) new data file deletion commit that will need to be reverted, just there no so this is easier to see whats going on...

### CODE REVIEW

**Comment by mulhearn** [comment]
This one I will complain about, for education purposes:

```
###EMTF emulator configuration
simEmtfDigis = cms.EDProducer("L1TMuonEndCapTrackProducer",
                              ## CSCInput = cms.InputTag('simCscTriggerPrimitiveDigis','MPCSORTED'),
                              ## isData = cms.bool(False)
                              CSCInput = cms.InputTag('csctfDigis'),
                              isData = cms.bool(True)
                              )
```

The simDigis configs are for production MC.  There are no unpacked csctf Digis in the production MC.  So this breaks.

In the standard workflows, like described here:  
 https://github.com/cms-l1t-offline/cmssw/issues/191
we use customizations to re-emulate over data.  You can't change the simDigis config for the purposes of your specific test and push that into the integration branch!

**Comment by mulhearn** [comment]
The need to change that input is handled properly already in the integration branch, here:

https://github.com/cms-l1t-offline/cmssw/blob/2b305223288386d36739767bf4fd85620a09df09/L1Trigger/Configuration/python/customiseReEmul.py#L73

**Comment by fwyzard** [comment]
Also, no `isData` settings, please...

.A

**Comment by mulhearn** [comment]
Just noticed that too ;-)

**Comment by mulhearn** [comment]
isData doesn't seem to actually be used anywhere?  I'm deleting it.

**Comment by mulhearn** [comment]
So, just to be clear,  this:

```
--- a/DataFormats/L1TMuon/src/EMTFHit.cc
+++ b/DataFormats/L1TMuon/src/EMTFHit.cc
@@ -36,7 +36,7 @@ namespace l1t {
     set_strip     ( _digi.getStrip()   );
     set_pattern   ( _digi.getPattern() );
     set_bend      ( _digi.getBend()    );
-    set_bx        ( _digi.getBX()      );
+    set_bx        ( _digi.getBX() - 6  ); // Standard for csctfDigis in data, simCscTriggerPrimitiveDigis in MC
     set_mpc_link  ( _digi.getMPCLink() );
     set_bx0       ( _digi.getBX0()     );
     set_sync_err  ( _digi.getSyncErr() );
```

works equally for data and MC, at least as we currently configure (using unpacked csc TPs for data reemulation, and sim CSC TP digis in MC?

**Comment by mulhearn** [comment]
Above issues all fixed and passing unit tests.  History cleanup up.  There is a separate PR with only the data format changes, but github seems slow today, it will be at branch:  emtf-luts-16_04_21

**Comment by mulhearn** [comment]
The PR with only changes to data area is #276.

**Comment by abrinke1** [comment]
Sorry for the simEmtfDigis issue - won't do it again.

"isData" was added by @mrcarver , for cms-l1t-offline use, I thought, but maybe it was actually for his private running.

The "set_bx" function in EMTFHit.cc is just for recording output for EMTF debugging / comparison with unpacked data at this point - it has no effect on the RegionalMuonCand sent to the uGMT emulator.  That said, this shift convention is accurate for unpacked CSCTF TPs in data (csctfDigis), and for sim CSC TPs in MC (simCscTriggerPrimitiveDigis), but _not_ for sim CSC TPs in data, as you stated.  We're working on this last point.

**Comment by mulhearn** [comment]
New data files are now (unused) in dev branch as l1t-integration-v40.4

Will test this PR on top of that and merge after some comparisons.

**Pull request merged**
