### PR TITLE
Heavy Ion update 2

### PR DESCRIPTION
**Pull request by bundocka**
-Swap out chunky sandwich for jet phi ring subtraction
-Update eg eta restriction
-Update centrality classes
-Update centrality saturation handling

### CODE REVIEW

**Comment by rekovic** [comment]
@bundocka 
Is L1Trigger/L1TCalorimeter/python/caloParams_2018_v1_4_cfi.py
 ready to be default for HI ?

**Comment by bundocka** [comment]
It should be now to the best of my knowledge with the LUT update from this afternoon

**Comment by rekovic** [comment]
So, this cfi would be used only in the offline expert level re-emulation.
DQM Online and Offline should pick up these params from the O2O-ed params in DB.

**Comment by rekovic** [comment]
Updated comment above.

**Comment by bundocka** [comment]
Correct, yes

**Comment by rekovic** [comment]
@bundocka 

Can this be closed ?  
We have integrated this in CMSSW, AFAIR.

**Comment by bundocka** [comment]
Yes, this PR was re-made and merged into CMSSW, in a number of separate PRs, so can be closed. Thanks

**Pull request closed without merging**
