### PR TITLE
Layer 2 CaloTower Unpacker bugfix

### PR DESCRIPTION
**Pull request by nsmith-**
40 frames, ieta 1-41, ieta 29 is not real
@matz-e @jimbrooke Please review and integrate

### CODE REVIEW

**Comment by jimbrooke** [comment]
Thanks Nick, we have been working on something similar.  However, the unpacker change needs to be synchronised with a fix to the Layer 2 emulator.  I think we have all the pieces, I'll make a new PR with all required changes tomorrow and have our team test it.

**Comment by nsmith-** [comment]
Something equivalent to this has been integrated, I understand?
If so, please close this.

**Comment by jimbrooke** [comment]
It hasn't been integrated yet - this is the PR 
https://github.com/cms-l1t-offline/cmssw/pull/216
Agree this can be closed when that one is integrated.

**Comment by nsmith-** [comment]
Appears fixed in #226

**Pull request closed without merging**
