### PR TITLE
uGMT intermediate muon unpacker

### PR DESCRIPTION
**Pull request by thomreis**
Unpacker for the intermediate muons of the uGMT

### CODE REVIEW

**Comment by thomreis** [comment]
@mulhearn currently there is only an unpacker but no corresponding packer. Would someone need one?

**Comment by bortigno** [comment]
maybe it is better to do it now rather than discover in a month from now that someone was using it :)

**Comment by thomreis** [comment]
If needed then a dummy would probably be sufficient. The RegionalMuonCand packer is also just a dummy at the moment and seems to cause no harm.

**Comment by mulhearn** [comment]
This is merged in v83.0

**Pull request closed without merging**
