### PR TITLE
Dasu updates for layer1

### PR DESCRIPTION
**Pull request by SridharaDasu**
We don't fully know if this will fix anything yet.  There were some, what I perceive are irrelevant changes, missing in the previous pull request. We get a decent looking plot for 260627 looking at 2000 events. Bhawna is going to try Jim's command.  

Note that this has few other changes we are working on, which should belong in here.  So, I kept them in. So, don't be alarmed by the larger looking changes.

### CODE REVIEW

**Comment by gomber** [comment]
So with Sridhara commit, I tested Jim recipe but I merged Sridhara version for 

cmsrel CMSSW_8_0_0_pre6
cd CMSSW_8_0_0_pre6/src
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git cms-merge-topic cms-l1t-offline:dasu-updates-for-layer1
scram b -j 8

cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --geometry=Extended2016,Extended2016Reco --conditions=auto:run2_data --no_output -n 10000 --data --filein=/store/data/Run2015D/SingleMuon/RAW/v1/000/260/627/00000/62834F8D-4C82-E511-8E4C-02163E013555.root

And here is the plot for the occupancy. So occupancy looks fine in HF.
[occ_10keventss.pdf](https://github.com/cms-l1t-offline/cmssw/files/152015/occ_10keventss.pdf)

**Comment by mulhearn** [comment]
This is mighty confusing... why do

```
mulhearn@lxplus067>git diff --name-only remotes/cms-l1t-offline/dasu-updates-for-layer1..remotes/cms-l1t-offline/l1t-integration-CMSSW_8_0_0_pre6
EventFilter/L1TXRawToDigi/plugins/BuildFile.xml
EventFilter/L1TXRawToDigi/plugins/L1TCaloLayer1RawToDigi.cc
EventFilter/L1TXRawToDigi/plugins/UCTCTP7RawData.h
EventFilter/L1TXRawToDigi/test/BuildFile.xml
EventFilter/L1TXRawToDigi/test/README
EventFilter/L1TXRawToDigi/test/testL1TCaloLayer1RawToDigi.py
EventFilter/L1TXRawToDigi/test/testUCTUnpacker.cpp
L1Trigger/L1TCaloLayer1/test/testL1TCaloLayer1.py
```

these changes fix the problem?  I don't think that test code uses any of this???!!

**Comment by gomber** [comment]
Which test code are you talking about mike?
I followed the cmsdriver command which Alex gave as mentioned previously with these changes, and it indeed fixed it..

**Comment by mulhearn** [comment]
I mean, I don't see how this:

```
cmsDriver.py l1Ntuple -s RAW2DIGI,L1Reco --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleRAWEMU --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --geometry=Extended2016,Extended2016Reco --conditions=auto:run2_data --no_output -n 10000 --data --filein=/store/data/Run2015D/SingleMuon/RAW/v1/000/260/627/00000/62834F8D-4C82-E511-8E4C-02163E013555.root
```

can be effected by these code changes...

**Comment by mulhearn** [comment]
(But maybe I misunderstand how these occupancy plots are generated...)

**Comment by gomber** [comment]
As mentioned by Sridhara in his commit that the HFTPGs in HCALDigis are added again as that change went away mysteriously in the last commit. So with that change, we expect to see better occupancy in HF region.

We use the output root file of cmsdriver command to obtain the occupancy plots, mainly I did in root 

L1CaloTowerTree->SetMarkerStyle(21)
 L1CaloTowerTree->Draw("L1CaloTower.iphi:L1CaloTower.ieta:L1CaloTower.iet", "L1CaloTower.iet>0", "COLZ")

**Comment by SridharaDasu** [comment]
Dear Mike,

When "re-emulating" on Run 260627, one uses the Layer-1 unpacker to 
get its input TPGs and then L1TCaloLayer1 to get L1CaloTower objects,
which are ultimately used in Layer-2.  Therefore, changes to our
Layer-1 emulator will make a difference if the workflow is setup as 
above.  

Regards,
Sridhara

**Comment by jimbrooke** [comment]
@SridharaDasu the command I sent actually starts from the HCAL readout digis and runs the HCAL TP, Layer 1 and Layer 2 emulators.  So the Layer 1 unpacker is not run.  And there don't appear to be any changes in this branch to the emulator.

@mulhearn is it possible the HEAD of l1t-integration has the changes required to fix the problem we are seeing, but tag l1t-integration-v7.0 does not ?  I'm not sure how to view tags in github.com, will have a look from the command line.

**Comment by jimbrooke** [comment]
I did the diff between this PR and the l1t-integration-v7.0 tag and I see the same as Mike (ie. no change to the code run by my command)

```
bash-4.1$ git diff --name-only cms-l1t-offline/dasu-updates-for-layer1 cms-l1t-offline/l1t-integration-v7.0
EventFilter/L1TXRawToDigi/plugins/BuildFile.xml
EventFilter/L1TXRawToDigi/plugins/L1TCaloLayer1RawToDigi.cc
EventFilter/L1TXRawToDigi/plugins/UCTCTP7RawData.h
EventFilter/L1TXRawToDigi/test/BuildFile.xml
EventFilter/L1TXRawToDigi/test/README
EventFilter/L1TXRawToDigi/test/testL1TCaloLayer1RawToDigi.py
EventFilter/L1TXRawToDigi/test/testUCTUnpacker.cpp
L1Trigger/L1TCaloLayer1/test/testL1TCaloLayer1.py
```

**Comment by jimbrooke** [comment]
I am now testing this PR using the recipe above, but since compilation takes _forever_ and the emulator in this mode is also rather slow, any help would be useful.  This is blocking calo trigger performance tuning.

**Comment by jimbrooke** [comment]
@gomber did you use precisely that recipe to run the test?  If so I think you are looking at the dummy Layer 1 module output.  You need to edit L1Trigger/L1TCalorimeter/python/simDigis_cff.py before running the cmsDriver command, as Mike describes here 
https://github.com/cms-l1t-offline/cmssw/issues/149#issuecomment-182118448
I am running with this and will report here when it finishes.

BTW, I recommend to process maximum 1k events right now, as the performance issue I mentioned here makes it very slow https://github.com/cms-l1t-offline/cmssw/issues/173

**Comment by gomber** [comment]
Thanks Jim for correcting me. As you said I didn't edit the smidgins file, so I will also run and let yu know what I obtain .

**Comment by jimbrooke** [comment]
What I get from Layer 1 emulator is here, still exhibits the old problem
http://jbrooke.web.cern.ch/jbrooke/l1trigger/toweretaphi_new.pdf

I also made the plot weighting by had and EM, in case this is informative
http://jbrooke.web.cern.ch/jbrooke/l1trigger/towerhad_new.pdf
http://jbrooke.web.cern.ch/jbrooke/l1trigger/towerem_new.pdf

**Comment by SridharaDasu** [comment]
We think we found the bug using nEta instead of nPhi in a few places :(  This did produce correct thing in our local tests using 260627.  Bhawna will do Jim's test in the morning and report here.

**Comment by gomber** [comment]
We did the Jim's test after fixing the eta index for HF.
Here is what I get from layer 1 emulator for 10K events.

occupancy_corrected_hf

**Comment by jimbrooke** [comment]
@gomber @SridharaDasu Thanks!  I see it, will verify this now.  @mulhearn can we get this in the integration branch?

Also, would it be possible to get the change to insert towers at a specific vector index?  We need to run over large samples for layer 2 calibration and Layer 2 is painfully slow right now.  If it would help, I can make a separate PR that @SridharaDasu and @gomber can review ?

**Comment by mulhearn** [comment]
I will update the integration branch to include this.

**Comment by mulhearn** [comment]
(Or rather, I will merge this PR, and make a tag, after testing)

**Comment by mulhearn** [comment]
It is in tag l1t-integration-v8.0

**Pull request merged**
