### PR TITLE
L1track jet emulator update (backport of PR40563)

### PR DESCRIPTION
**Pull request by epalencia**
This PR includes the updated trackjet emulation code. The new code has a different structure and uses common functions between emulator and simulation. This way we are sure that exactly the same code is run in both cases and the only difference is in the inputs. The code was presented in the GTT meeting:

- https://indico.cern.ch/event/1203796/
- https://indico.cern.ch/event/1211843/

Backport of https://github.com/cms-sw/cmssw/pull/40563: Had to modify `L1Trigger/TrackFindingTracklet/test/L1TrackNtupleMaker_cfg.py` to solve conflicts due to different geometry

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by gkaratha** [comment]
Hi @epalencia , 

I had a look and seems ok to me. In one glance I dont see any changes. Regarding the conflict, what was the issue? Thanks

Best,
George

**Comment by epalencia** [comment]
I'm closing this PR as it is superseded by https://github.com/cms-l1t-offline/cmssw/pull/1117

- as described in https://github.com/cms-sw/cmssw/issues/38594#issuecomment-1256251018, D88 is available in 12_5 and should be used, if possible.

**Pull request closed without merging**
