### PR TITLE
Add V29/AR Menu ntupler to 13X snapshot3

### PR DESCRIPTION
**Pull request by artlbv**
#### PR description:

This adds the menu ntupler modifications for the snapshot3/ Annual Review / V29 branch.
This is NOT indented to go to any IB or central cmssw!

This will make sharing/documenting the menu ntupler recipes easier.

### CODE REVIEW

**Comment by artlbv** [comment]
Hi @aloeliger , is there any reason you added the `do not merge` label?
This PR **is* intended for merging into the snapshot branch!

**Comment by aloeliger** [comment]
@artlbv 

> This is NOT indented to go to any IB or central cmssw!

Do you want this merged instead?

**Comment by artlbv** [comment]
I target this PR at the `cms-l1t-offline:Phase2_prototypeSnapshot_3_CMSSW_13_1` branch. 
Such that the corresponding menu ntupler is archived with the rest of the code.

**Comment by aloeliger** [comment]
Ahh. Okay. One second then, this can probably be merged after a quick check. Let me start that.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 13 files that did not meet formatting requirements:
 - DataFormats/L1TParticleFlow/interface/gt_datatypes.h
 - L1Trigger/DTTriggerPhase2/src/MPQualityEnhancerFilter.cc
 - L1Trigger/DTTriggerPhase2/src/MuonPathAssociator.cc
 - L1Trigger/DemonstratorTools/src/codecs_tkjets.cc
 - L1Trigger/L1CaloTrigger/plugins/Phase2L1CaloPFClusterEmulator.cc
 - L1Trigger/L1TNtuples/plugins/L1GenTreeProducer.cc
 - L1Trigger/L1TNtuples/plugins/L1PhaseIITreeStep1Producer.cc
 - L1Trigger/L1TNtuples/src/L1AnalysisPhaseIIStep1.cc
 - L1Trigger/L1TTrackMatch/interface/L1TkEtMissEmuAlgo.h
 - L1Trigger/L1TTrackMatch/plugins/L1TrackerEtMissEmulatorProducer.cc
 - L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker.cc
 - L1Trigger/Phase2L1ParticleFlow/plugins/L1NNTauProducer.cc
 - L1Trigger/VertexFinder/src/VertexFinder.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
As long as this compiles, I guess this is fine.

**Pull request merged**
