### PR TITLE
L1t integration v37.2 tau iso option 5 becomes default in Stage2Calo config

### PR DESCRIPTION
**Pull request by davignon**
@mulhearn @rekovic 
This PR concerns the default isolation Option for taus to be used for emulation in the MC campaign. It should be Option 5, and therefore the caloStage2Params config file has been changed accordingly.
Option 21 (which is no longer the default in v37.2) should still be used for the beginning of data taking.

Cheers,
- Olivier

### CODE REVIEW

**Comment by rekovic** [comment]
@davignon 

> Option 21 (which is no longer the default in v37.2) should still be used ...

What exactly did you mean?
Tau Option 21 is indeed the default for v37.2 ( in caloStage2Params_cfi.py.)

**Comment by davignon** [comment]
@rekovic 

Sorry for the confusion. What I meant is that when this PR we are discussing about will be merged, Option 21 will no longer be the default. Option 5 will.
Still, Option 21 is to be used if one wants to optimize a trigger menu for the beginning of the 2016 data taking (at lower lumi.)

**Comment by rekovic** [comment]
@davignon 
OK.  I imagined that this is what you meant, but wanted to remove possible misunderstanding.
Thanks!

**Comment by fwyzard** [comment]
Hi @rekovic , both for startup studies and for post-ICHEP studies there are differences to consider (RPC included in BMTF, new Layer1/Layer2 calibrations, etc.).

In CMSSW, we should definitely aim to have the default as close as possible to the post-ICHEP case, since the samples will be used for the whole year, and most of the luminosity will be taken with those conditions. Thus, please make "Option 5" the default in CMSSW 8.0.x and 8.1.x.

For studies, we should make both options available.
Could you make a tag "l1t-tsg-v5.1" , with "Option 5" as the only difference with respect to "l1t-tsg-v5" ?

**Comment by rekovic** [comment]
@davignon @fwyzard 

Tau Option-5 has been made default in l1t-tsg-v5.1 (also in the l1t-integration branch).
So this PR can be closed.

**Pull request closed without merging**
