### PR TITLE
CaloLayer1 packer

### PR DESCRIPTION
**Pull request by nsmith-**
Has not been tested in a standard sequence, can someone provide a `cmsDriver.py` command suitable to test?

### CODE REVIEW

**Comment by rekovic** [comment]
@nsmith- 
Good command for testing packer+unpacker is one of the L1T unit-tests (below).
The job starts form GEN-SIM, does the DIGI, L1T emulation, full packer, full unpacker, and a comparison of L1T RAW vs EMU as the last step (via customisation).

L1T unit-test command:

```
cmsDriver.py L1TEST --python_filename=l1t_test.py --conditions=auto:run2_mc -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU
```

**Comment by nsmith-** [comment]
Ok @rekovic this command you gave is successful now, and also I ran my own tests starting from cmsDriver and have full agreement between `sim->pack->unpack` and `sim` for CaloLayer1.

**Comment by nsmith-** [comment]
Moving the target branch to `l1t-integration-CMSSW_9_2_8`...

**Comment by nsmith-** [comment]
Ok @rekovic should be good to merge.

**Pull request merged**
