### PR TITLE
EMTF unpacker outputs CSCCorrelatedLCTDigiCollection

### PR DESCRIPTION
**Pull request by abrinke1**
EMTF unpacker outputs a CSCCorrelatedLCTDigiCollection, which can be fed into the EMTF emulator.

### CODE REVIEW

**Comment by mulhearn** [comment]
Nice!

**Comment by mulhearn** [comment]
This looks like just the ticket to validate our TP inputs.  And as bonus a "goto" removed that I can't believe went unnoticed into CMSSW ;-)

**Comment by rekovic** [comment]
@abrinke1 This does not compile. 

<pre>
>> Compiling  /afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_7_l1t_integration/src/EventFilter/L1TRawToDigi/src/implementations_stage2/EMTFBlockHeaders.cc 
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_7_l1t_integration/src/EventFilter/L1TRawToDigi/src/implementations_stage2/EMTFBlockME.cc: In member function 'virtual bool l1t::stage2::emtf::MEBlockUnpacker::unpack(const l1t::Block&, l1t::UnpackerCollections*)':
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_7_l1t_integration/src/EventFilter/L1TRawToDigi/src/implementations_stage2/EMTFBlockME.cc:141:33: error: '__gnu_cxx::__alloc_traits<std::allocator<l1t::EMTFOutput> >::value_type {aka class l1t::EMTFOutput}' has no member named 'PtrEventHeader'
  int _endcap = ((res->at(iOut)).PtrEventHeader()->Endcap() == 1) ? 1 : 2;
                                 ^
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_7_l1t_integration/src/EventFilter/L1TRawToDigi/src/implementations_stage2/EMTFBlockME.cc:145:26: error: '__gnu_cxx::__alloc_traits<std::allocator<l1t::EMTFOutput> >::value_type {aka class l1t::EMTFOutput}' has no member named 'PtrEventHeader'
          (res->at(iOut)).PtrEventHeader()->Sector() );
</pre>

 Can you please check .

**Comment by abrinke1** [comment]
Hi Vladimir,

Did you try scram b clean; scram b -j 6; in the DataFormats/L1TMuon/ directory, then recompiling?  PtrEventHeader should be there:
https://github.com/abrinke1/cmssw/blob/EMTF_Digis_802/DataFormats/L1TMuon/interface/EMTFOutput.h#L76

**Pull request merged**
