### PR TITLE
EMTF emulator input hit BX shift, small fix, format cleanup

### PR DESCRIPTION
**Pull request by abrinke1**
Add configurable variable to shift BX of input CSC trigger primitives
Small fix to theta assignment of a very select few hits
Edited emulator files to have standard tabbing and reduce empty lines (tested to give bit-wise identical performance)

### CODE REVIEW

**Comment by rekovic** [comment]
@abrinke1  This does not compile.  Can you please check

<pre>
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_9_l1t_integration/src/L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapTrackProducer.cc: In member function 'virtual void L1TMuonEndCapTrackProducer::produce(edm::Event&, const edm::EventSetup&)':
/afs/cern.ch/work/r/rekovic/private/relaeses/CMSSW_8_0_9_l1t_integration/src/L1Trigger/L1TMuonEndCap/plugins/L1TMuonEndCapTrackProducer.cc:88:16: error: 'class CSCCorrelatedLCTDigi' has no member named 'setBX'
       tmp_digi.setBX( tmp_digi.getBX() + std::max(bxShiftCSC, -1*tmp_digi.getBX()) );
                ^
config/SCRAM/GMake/Makefile.rules:1917: recipe for target 'tmp/slc6_amd64_gcc530/src/L1Trigger/L1TMuonEndCap/plugins/L1TriggerL1TMuonEndCapPlugins/L1TMuonEndCapTrackProducer.o' failed
</pre>

**Comment by rekovic** [comment]
@abrinke1 Could you please provide the fix in   1ce847a for the tag l1t-integration-v62.3 (i.e. HEAD of the integration branch CMSSW 809) ?

**Comment by abrinke1** [comment]
Hi Vlad,

Did you try clean compiling DataFormats/CSCDigi/ first?  I made changes to CSCCorrelatedLCTDigi.h in the commit "EMTF emulator configurable BX shift for input hits".

Also, I'm not quite sure what you mean by "provide the fix for tag l1t-integration-v62.3".  Does that mean you want a separate PR to l1t-integration-v62.3?  Do you want the new PR to have only this fix, and not the others in PR 339?

Cheers,
Andrew

**Comment by rekovic** [comment]
Hi @abrinke1 ,

Thanks.

> Did you try clean compiling DataFormats/CSCDigi/ first? I made changes to CSCCorrelatedLCTDigi.h in the commit "EMTF emulator configurable BX shift for input hits".

That fixed the compilation. Now running tests to check for the effect on DoubleMu rates.

> Also, I'm not quite sure what you mean by "provide the fix for tag l1t-integration-v62.3". Does that mean you want a separate PR to l1t-integration-v62.3? Do you want the new PR to have only this fix, and not the others in PR 339?

Yes. Exactly.  
If the fix in  1ce847a solves the problem of high rates in DoubleMu, it would be great to have a PR that does this fix only on top of l1t-integration-v62.3, so that it can be pushed into CMSSW easily and quickly.

**Comment by rekovic** [comment]
@abrinke1 

This PR (including all commits listed above) does NOT affect the DoubleMu count. 
See results of unit-tests when comparing this PR (aka v63.1 ) with v62.3 [here](http://rekovic.web.cern.ch/rekovic/cms/L1T/Stage2/l1t-integration/compare_test_l1t_integration_v63.1_vs_test_l1t_integration_v62.3/diff_menu_a_vs_menu_b.txt).

Plots and counts suggest that we have not solved the problem with high DoubleMu rates in the emulator, unfortunately.

**Comment by rekovic** [comment]
Updated previous comment with _NOT_

**Comment by abrinke1** [comment]
Hi Vlad,

Unfortunately that is what I expected.  The RegionalMuonCandBxCollection looked OK to me before, and it was not affected by the change.

Also, for the life of me I can't figure out how to make the PR to l1t-integration-v62.3.  I made a new branch: https://github.com/cms-l1t-offline/cmssw/tree/EMTF_sector_bugfix_v62.3

but when attempting to make a PR, constantly get stuck at the "Comparing changes" page, with no way I can see to actually make the pull request:
https://github.com/cms-l1t-offline/cmssw/compare/l1t-integration-v62.3...cms-l1t-offline:EMTF_sector_bugfix_v62.3

Not that it's urgent now, but I'd like to understand how to do this.

**Comment by rekovic** [comment]
@abrinke1 

Ok, there is no need for a separate PR just for that single commit as it does not solve our problem.

But to answer your question about the problem you are having with making the PR:
When you get to the page to create a PR, make sure that you select  cms-l1t-offline from the pull-down menu of "base fork: ". Then again, on the next page, chose l1t-integration-CMSSW_8_0_9 from the pull-down menu of "base", and you will end up [here](https://github.com/cms-l1t-offline/cmssw/compare/l1t-integration-CMSSW_8_0_9...cms-l1t-offline:EMTF_sector_bugfix_v62.3?expand=1).

**Pull request merged**
