### PR TITLE
Update Correlator code to l1ct-123x-v1.13 tag

### PR DESCRIPTION
**Pull request by gpetruc**
This is a cumulative update of correlator CMSSW code from the previously integrated tag [l1ct-123x-v1.6](https://github.com/p2l1pfp/cmssw/releases/tag/l1ct-123x-v1.6) to [l1ct-123x-v1.13](https://github.com/p2l1pfp/cmssw/releases/tag/l1ct-123x-v1.13)

Includes:
* https://github.com/p2l1pfp/cmssw/pull/92 by @thesps and @slaurila
*  https://github.com/p2l1pfp/cmssw/pull/94 by @thomreis and @cerminar (only adds a new feature to the emulator, doesn't change any of the existing emulated values)
* https://github.com/p2l1pfp/cmssw/pull/96 by @thesps
* https://github.com/p2l1pfp/cmssw/pull/97 by @drankincms
* https://github.com/p2l1pfp/cmssw/pull/98 by @drankincms (not used by default)
* https://github.com/p2l1pfp/cmssw/pull/100 by @thesps
* https://github.com/p2l1pfp/cmssw/pull/101 by @gpetruc (not used in production)
* https://github.com/p2l1pfp/cmssw/pull/105 by @gpetruc (not used in production)

I don't think we expect significant changes in physics performance for the existing correlator output products, and the btag performance should match what was in the DPS note.

### CODE REVIEW

**Comment by gpetruc** [comment]
I can also push a small update from https://github.com/p2l1pfp/cmssw/pull/107 that avoids the `#ifdef`s around the `make_unique` and should make the CMSSW reviewers happier

**Comment by artlbv** [comment]
Hi @drankincms @EmyrClement given that PR #1061 states:

> Simulated seeded cone puppi jets are removed, keeping only the collection produced by emulation

How does this affect e.g. the JEC and L1 b-tagging which were implemented for both emulated and simulated SC jets?

**Comment by EmyrClement** [comment]
I believe the JECs are only applied to the emulated SC jets (only "CorrectedEmulator" producers in the [Task](https://github.com/cms-l1t-offline/cmssw/blob/912d918fada6bc46e5276c5d0c7065bb2f2e5f53/L1Trigger/Phase2L1ParticleFlow/python/l1pfJetMet_cff.py#L35)),.

The b-tagging uses new collections of simulated/emulated SC jets (using inputs from extended tracking) [here](https://github.com/cms-l1t-offline/cmssw/blob/912d918fada6bc46e5276c5d0c7065bb2f2e5f53/L1Trigger/Phase2L1ParticleFlow/python/L1BJetProducer_cff.py#L6) and [here](https://github.com/cms-l1t-offline/cmssw/blob/912d918fada6bc46e5276c5d0c7065bb2f2e5f53/L1Trigger/Phase2L1ParticleFlow/python/L1BJetProducer_cff.py#L19).

So the two PRs shouldn't interfere with each other.  Part of the purpose of #1061 is to remove (or don't produce) collections that aren't used downstream, unless there's a good reason to e.g. they can't be quickly reproduced from the MC, or are new so it's useful to have the simulated collections as well as the emulated collection.  So we may not want to include some of the new objects here e.g. simulated SC jets using extended tracking inputs.

**Comment by EmyrClement** [comment]
@gpetruc just to confirm only [the JECs emulation](https://github.com/p2l1pfp/cmssw/pull/92) for seeded cone jets and [update of deregonizer inputs emulation](https://github.com/p2l1pfp/cmssw/pull/100) could have an effect on existing outputs?  The other affect new products or add new features/support?

**Comment by cbotta** [comment]
@EmyrClement @gpetruc : few questions related to "The b-tagging uses new collections of simulated/emulated SC jets (using inputs from extended tracking)". 1) Is it correct that this means we are running PF+PUPPI twice, once with standard tracks and once with extended tracks? 2) Are the extended tracks used in input the 'prompt' tracks from the 5-par-fit, or really the enlarged collection that extend to displaced tracks? 3) Whatever is the answer, is the 'extended' collection of tracks used in input saved in the event content? 4) How well do we know if running PF+PUPPI with extended tracks is okay latency/resources wise?

**Comment by gpetruc** [comment]
@drankincms may answer better

> @EmyrClement @gpetruc : few questions related to "The b-tagging uses new collections of simulated/emulated SC jets (using inputs from extended tracking)".
> 1) Is it correct that this means we are running PF+PUPPI twice, once with standard tracks and once with extended tracks?

yes

> 2) Are the extended tracks used in input the 'prompt' tracks from the 5-par-fit, or really the enlarged collection that extend to displaced tracks? 

the enlarged collection with also displaced tracks, but some cuts are applied to them

> 3) Whatever is the answer, is the 'extended' collection of tracks used in input saved in the event content? 

I think so

> 4) How well do we know if running PF+PUPPI with extended tracks is okay latency/resources wise?

in this setup, the maximum input object multiplicities are not changed, and so latency and resources are unchanged as well (however, one would have to redo the study of the truncations to see if it's fine to not change the maximum multiplicities)

**Comment by dsrankin** [comment]
Giovanni's answers are all correct here, just to add: the cuts are here (https://github.com/p2l1pfp/cmssw/blob/correlator_pr_l1ct_123x_v1p13/L1Trigger/Phase2L1ParticleFlow/python/pfTracksFromL1Tracks_cfi.py#L32-L34) and they restrict to tracks within 1cm in dx & dy as was done for the b-tag DPS note. This means the track multiplicities shouldn't change too much, but indeed this is something that should be confirmed.

**Comment by cecilecaillol** [comment]
@gpetruc Could you move this PR to the new rebased branch phase2-l1t-integration-1252patch1?

**Comment by gpetruc** [comment]
Ok, will do but in january

**Comment by gpetruc** [comment]
Replaced by #1063

**Pull request closed without merging**
