### PR TITLE
uGMT unpacker upgrade to support new MP7 zero suppression

### PR DESCRIPTION
**Pull request by thomreis**
The MP7 will change the zero suppression to support ZS per BX instead of only per block of all BX in the read out.
This requires a change of the unpackers to handle the new structure in the RAW data.

An additional header per BX was added in the RAW data (see https://twiki.cern.ch/twiki/pub/CMS/MP7ZeroSuppression/mp7_zs_payload_formats.pdf).

This PR upgrades the uGMT unpacker to handle the new format.
Backwards compatibility with 2016 and early 2017 data format is maintained and tested with 64M ZeroBias events + 1.49M SingleMuon ZMu skim events of 2017 data (100% agreement with result of old unpacker).

### CODE REVIEW

**Comment by thomreis** [comment]
@rekovic do not merge this one yet. Some FW changes make more commits necessary and retesting.

**Comment by thomreis** [comment]
Retested with 1.4M SingleMuon ZMu skim events from 2017C and 42M ZeroBias events from 2017C. 100% agreement. @rekovic this could be merged.

**Comment by thomreis** [comment]
Retested. Still 100% agreement.

**Comment by rekovic** [comment]
rebased to 928 and merged as l1t-integration-v96.29

**Pull request closed without merging**
