### PR TITLE
Fixing the x3 missing in multiple scattering LUTs

### PR DESCRIPTION
**Pull request by aloeliger**
Add final muon PR to prototype.

### CODE REVIEW

**Comment by zhenbinwu** [comment]
Hi Andrew. Since this is the last PR for the AR, I would suggest we rush it in for the menu team. 

In term of the code, I believe it doesn't pass the cms code-format. It would be easier if you or I make another small fix/PR after you merge this one. Thanks

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 3 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc
 - L1Trigger/Phase2L1GMT/interface/TPSLUTs.h
 - L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTFwdMuonTranslator.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR passes available unit tests!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b runtests`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation

I found a non-zero return code running the relval workflows for this PR!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`1`|
|command|`eval `scramv1 runtime -sh` && runTheMatrix.py --what upgrade -l 26834.78`|

**Comment by aloeliger** [comment]
@zhenbinwu We're not going to dig too deep into this PR, and just merge it. Either you or @bachtis should open this PR up to central CMSSW as soon as possible and we will deal with any wrath of build bot and software conveners there. 

I think this should be the last thing required for `v9`, so I am immediately going to tag and cut that release.

**Comment by zhenbinwu** [comment]
Sounds good. I will add all the recent PRs to the https://github.com/cms-sw/cmssw/pull/44498.

**Pull request merged**
