### PR TITLE
Add Kalman BMTF muon info and sequence into L1T NTuple

### PR DESCRIPTION
**Pull request by abrinke1**
Added compressed BMTF muon displaced pT and dXY into L1UpgradeBmtfMuon branch.
Added un-compressed BMTF muon properties into new L1UpgradeBmtfOutput branch.

Test can be run with the following command:
cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=data.py -n 100 --no_output --era=Run2_2018 --data --conditions=103X_dataRun2_Prompt_v3 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAWKalmanMuon --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMUKalmanMuon --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_4 --filein=file:/eos/cms/store/data/Run2018D/SingleMuon/RAW-RECO/ZMu-PromptReco-v2/000/321/457/00000/60D23B7B-C7A5-E811-B14B-FA163EF4F4A1.root

@rekovic , @bachtis , @panoskatsoulis, @gkaratha , @dinyar , @weishi , @jalimena , @mcitron , @aescalante, @valuev please take a look.

### CODE REVIEW

**Comment by abrinke1** [comment]
@rekovic have you had a chance to look at this?

Thanks,
Andrew

**Comment by rekovic** [comment]
This indeed should be revived and PRed into central CMSSW.

**Comment by abrinke1** [comment]
Hi @rekovic , so you would prefer a PR directly to central CMSSW?  Which branch?  Since most studies are done in the l1t-integration branch, we'd want the changes there too.

**Comment by rekovic** [comment]
@abrinke1 
OK. For L1T development please use `l1t-integration-CMSSW_11_0_2`

If scouting people need this code centrally for some reason urgently, it has to go into development 11_1_X.  If not, once Dinyar's PR #836 is merged, we can merge this in central CMSSW.

**Pull request closed without merging**
