### PR TITLE
[DT Emulator] First cleaned version AMv2 with SL2

### PR DESCRIPTION
**Pull request by jfernan2**
#### PR description:

This PR integrates the new version (v2) of the Analytical Method for the Phase-2 DT Emulator.

It has been presented in the DT Upgrade (trigger primitives and test systems)[1] and in the Level-1 Muon DPG meeting [2].

Needs data files from PR https://github.com/cms-data/L1Trigger-DTTriggerPhase2/pull/3

Credits of the code to @jaimeleonh [3], SL2 emulation addition from [4] 

#### PR validation:

The software goes hand by hand with the developments being implemented in the firmware. In links [1] and [2] are presented performance results with the new AMv2 algorithm :
* In simulation with the emulator
* Comparing emulator and firmware in the laboratory
* Similar (or even improved) performance w.r.t. previous AM version (v1, already in CMSSW)

[1] https://indico.cern.ch/event/1262475/contributions/5308462/attachments/2607937/4505149/230309_NewAM_DTUpgrade_JLH.pdf
[2] https://indico.cern.ch/event/1263362/contributions/5305755/attachments/2607489/4504221/230308_NewAM_L1MuonDPG_JLH.pdf

[3] https://github.com/jaimeleonh/cmssw/tree/AM_12_4_2_new_fitter
[4] https://github.com/jfernan2/cmssw/tree/AM_12_4_2_new_fitter_withThetas

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1CaloTrigger/plugins/L1EGammaCrystalsEmulatorProducer.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by epalencia** [comment]
Thanks @jfernan2 for porting this PR to 13_3 (https://github.com/cms-l1t-offline/cmssw/pull/1166). I'm closing this one.

**Pull request closed without merging**
