### PR TITLE
More updates to Tau NN [14_0_0_pre3]

### PR DESCRIPTION
**Pull request by Duchstf**
#### PR description:

This PR is to update some fixes in the Tau NN that was merged in  #43639. In particular, the input types were changed to `ap_fixed<16,6>` which introduced in-consistency in performance in CMSSW as compared to python simulation.

#### PR validation:

- Codes compiled, and formatted. 
- Performance was checked by making various performance plots:

 
image

### CODE REVIEW

**Comment by EmyrClement** [comment]
For reference, here's the same matching efficiency plot before this PR.

image

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by Duchstf** [comment]
Hmm I don't think this `L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc` is related to any changes I made.

**Comment by epalencia** [comment]
Yes, that is correct. Do not worry about it.

**Comment by aloeliger** [comment]
@epalencia I don't think I have any review here. Would you be okay with just merging this and starting the PR to CMSSW?

**Comment by aloeliger** [comment]
@Duchstf This is being merged to provide validation material for the menu team. If there is no PR open to main CMSSW for this PR, please do so immediately. @epalencia FYI.

**Pull request merged**
