### PR TITLE
Use unpacked EMTF digis as input to EMTF emulation

### PR DESCRIPTION
**Pull request by abrinke1**

### CODE REVIEW

**Comment by rekovic** [comment]
@abrinke1  @bortigno @mrcarver 
Applying this PR (which switches from using unpacked CSCTP to unpacked EMTF as inputs to simEmtf) makes a large impact on the re-emulated 2016 muons
http://rekovic.web.cern.ch/rekovic/cms/L1T/Stage2/l1t-integration/compare_test_l1t_integration_v78.0_vs_test_l1t_integration_v77.0/
Is such a large change understood and expected?

**Comment by bortigno** [comment]
running Tuples in 8_0_16 with #395 solution from Andrea I have a 90% success rates on the Express stream (only unpacked). I launched now in the same area a production of ntuples re-emulated to see if porting the code to 8_0_16 could fix the issue.

**Comment by bortigno** [comment]
it should not - may I suggest that before merging someone shows the agreement of the two collections in one run where the CSCTF was still in? for this maybe the best if to have #377 done. work on it today

**Comment by bortigno** [comment]
tag for testing prepared by vlad: cms-l1t-offline:issue-391-l1t-integration-emtfUnpacked. which is v77+PR391

**Comment by mulhearn** [comment]
Is there any movement on this?  I too see unexpected discrepancy when making the shift.
To reproduce, use CMSSW_8_0_17, and branch debug-EMTF-PR-391-CMSSW_8_0_17.
Then, after compiling, do:

```
perl L1Trigger/L1TCommon/scripts/testL1T.pl --fast --delete
<watch log file as instructed and wait until finished>
cp -r /afs/cern.ch/user/m/mulhearn/public/compare/l1t-integration-v75.0 .
perl L1Trigger/L1TCommon/scripts/testL1T.pl --fast --compare2=.:./l1t-integration-v75.0/
```

(You can repeat without the --fast option in both steps to get more stats, and with --slow for even more stats.)

**Comment by mulhearn** [comment]
Actually, in my case, the discrepancies don't see to look very large.  Running now with more stats then I'll post comparison plots.

**Comment by abrinke1** [comment]
Remember not to use runs 276831 - 276834, which are missing the
csctfDigis.  Also, EMTF was missing some LCTs in runs 277932 - 278092, so
try to avoid those.

https://twiki.cern.ch/twiki/bin/view/CMS/L1KnownIssues

Cheers,
Andrew

**Comment by mulhearn** [comment]
I see large discrepancies when I run over e.g. Run 271336.

**Comment by mulhearn** [comment]
Effect is quite large:  http://mulhearn.web.cern.ch/mulhearn/plots/compare_emtf_vs_l1t-integration-v75.0/

**Comment by abrinke1** [comment]
Hi Mike,

Am I reading that run number correctly: 271336?  That's ancient history!
The unpacked emtfDigis have only been really reliable since run 276215, as
documented here:

https://twiki.cern.ch/twiki/bin/view/CMS/L1KnownIssues

How come you don't have that page memorized :)  That makes me think ... do
we need some condition (O2O?) in the L1TNtuple code to use csctfDigis for
re-emulation before run 276215, and emtfStage2Digis after?

Best,
Andrew

**Comment by mulhearn** [comment]
Have to think, but having this easily configurable via customization might be sufficient...

**Comment by thomreis** [comment]
@mulhearn @abrinke1 what is the status of this PR? We are still using csctfDigis as input for the EMTF emulator and this prevents us most likely from getting good data to emulator agreement for the dead sectors of the detector. Can it be merged at some point?

**Comment by rekovic** [comment]
@thomreis  Can merge, but we need to make sure that the changes in the EMTF muons are understood.  From the thread, I don't see this.  The last time I looked (https://github.com/cms-l1t-offline/cmssw/pull/391#issuecomment-238205291)  the changes were huge and not understood. 
It would be good if we could run tests with locally merging this PR and check data/emul for EMTF.

**Comment by thomreis** [comment]
With csctfDigis we see differences between data and emulator. If with emtfDigis we are closer to the data I would say we expect differences when switching to them. Perhaps we can run ntuples with emtfDigis on a recent run and compare the agreement to data.

**Comment by abrinke1** [comment]
The only discrepancies noted in this thread were understood and commented on: runs 276831 - 276834 are missing the csctfDigis, and in runs before 276215 (July 2) the emtfStage2Digis are not 100% reliable.  For the past few months, the difference between LCTs in the csctfDigis collection and the emtfStage2Digis collection have been at the ~0.2% level in most chambers.  Some chambers have EMTF-specific problems in transmitting LCTs - here it is important to use emtfStage2Digis.  (csctfDigis cause the data/emulator discrepancy around phi = 0.8 here [1])  The difference from changing to emtfStage2Digis will be small, and will be in the right direction (i.e. closer to data).

[1] https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281613-282037_singleMuon_i87p1/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi_over_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi.png

**Comment by thomreis** [comment]
I made data/emulator comparisons with Len's ntuples using the
emtfStage2Digis as input for the EMTF emulator. I had ntuples for run
281693 available. If we need others we have to produce more ntuples.

With emtfStage2Digis the data/emulator agreement is much better than
with csctfDigis in the areas with dead chambers. However, the efficiency
of the emulator is overall a bit lower than in data.

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin0_absEtaMax2.4_ptmin24.eta_over_probe_absEtaMin0_absEtaMax2.4_ptmin24.eta.png

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.24_absEtaMax2.4_ptmin0.5.pt_over_probe_absEtaMin1.24_absEtaMax2.4_ptmin0.5.pt_xMax100.png

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi_over_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi.png

EMTF eta regions:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.2_absEtaMax1.55_ptmin24.phi_over_probe_absEtaMin1.2_absEtaMax1.55_ptmin24.phi.png

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.55_absEtaMax1.85_ptmin24.phi_over_probe_absEtaMin1.55_absEtaMax1.85_ptmin24.phi.png

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.85_absEtaMax2.4_ptmin24.phi_over_probe_absEtaMin1.85_absEtaMax2.4_ptmin24.phi.png

A direct comparison between efficiencies from emtfStage2Digis and
csctfDigis shows a higher efficiency for csctfDigis also in phi regions
other than the ones with the bad chambers.

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF_vs_281693_singleMuon_i87p1_csctf/comp_emu_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.24_absEtaMax2.4_ptmin40.phi_over_emu_probe_absEtaMin1.24_absEtaMax2.4_ptmin40.phi.png

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_unpackedEMTF_vs_281693_singleMuon_i87p1_csctf/comp_emu_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin0_absEtaMax2.4_ptmin40.eta_over_emu_probe_absEtaMin0_absEtaMax2.4_ptmin40.eta.png

If you can't see the plots check if you are logged in in CERN SSO and a member of the cms-members e-group

**Comment by thomreis** [comment]
For comparison this is the data/emulator comparison when using csctfDigis

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2016_281693_singleMuon_i87p1_csctf/dataEmul_best_l1_muon_qualMin12_ptmin18_dr0.5_matched_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi_over_probe_absEtaMin1.24_absEtaMax2.4_ptmin24.phi.png

**Comment by rekovic** [comment]
Thanks @thomreis and @abrinke1.

Changes from this PR are picked and merged in l1t-integration-CMSSW_8_0_19.
Tagged as l1t-integration-v87.2

Will close this PR.

**Pull request closed without merging**
