### PR TITLE
uGT emul  correlations with overlap removal

### PR DESCRIPTION
**Pull request by rekovic**
New features: xml menu parser and GT emulator of correlation conditions with overlap removal.

**New:**
- classes:
  - CorrelationWithOverlapRemovalTemplate
  - CorrWithOverlapRemovalCondition
- condition type:
  - Type2corWithOverlapRemoval 
- condition category
   - condCondCorrelationWithOverlapRemoval

**Parser logic:**
- From XML menu, with help of UTM library, store all the relevant information in CorrelationWithOverlapRemovalTemplate.

**Emulator logic:**
   - Define 3 GtConditionCategories: (1st & 2nd correlation legs, and overlap-removal leg)
   - Loop leg1: over all objects of 1st correlation leg.
     - Loop leg3: over all objects of overlap-removal leg.
     - If leg1 object matched with any overlap object, next leg1 object.
     - Loop leg2: over all object of 2nd correlation leg.
       - Loop leg3: over all objects of overlap-removal leg.
       - If leg2 object matched with any overlap object, next leg2 object.
       - If any correlation cut pass, save leg1-leg2 object combination.

Emulation of indexing of objects also implemented.

Note: Need updated UTM library.

### CODE REVIEW

**Review by tmatsush — COMMENTED** [review]
The following changes are needed to handle the overlap removal logic correctly when both deltaPhi and deltaEta are required as definition of overlap:

https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1081
to
overlapRemovalMatchLeg1 = true;
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1742
to 
overlapRemovalMatchLeg2 = true;

then remove the following lines
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1098
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1127
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1162
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1760
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1788
https://github.com/rekovic/cmssw/blob/816566aa7fbe791e7f6724bc06a96ee4317ad312/L1Trigger/L1TGlobal/src/CorrWithOverlapRemovalCondtion.cc#L1822

**Comment by rekovic** [comment]
Emulation of overlap removal from the correlation conditions is achieved.

Using a test xml file, suitable for overlap removal in correlation conditions:
`
/afs/cern.ch/user/r/rekovic/public/forL1TStage2/l1t-integration/overlap-removal/xml/test_indexing_overlap_removal_v1.xml` , and `Xerces31` development UTM library
the following emulation results are obtained with 10 events of `PhaseIFall16 VBFToTauTau GEN-SIM`:

<pre>
 L1T menu Name   : test menu
 L1T menu Version: 0.5
 L1T menu Comment:  : processed with UTM under development

    Bit                  Algorithm Name                  Init    PScd  Final   PS Factor     Masked    Veto
============================================================================================================
       0                               L1_SingleMu5         1      1      1         1          1        0
       1                       L1_SingleMu5_2ndLead         0      0      0         1          1        0
       2                               L1_SingleEG5         7      7      7         1          1        0
       3                       L1_SingleEG5_2ndLead         1      1      1         1          1        0
       4                             L1_SingleTau20        10     10     10         1          1        0
       5                     L1_SingleTau20_2ndLead         6      6      6         1          1        0
       6                             L1_SingleJet90         5      5      5         1          1        0
       7                     L1_SingleJet90_2ndLead         3      3      3         1          1        0
     100                             L1_Mt15t15_100         4      4      4         1          1        0
     101              L1_Mt15t15_100_rmovlp_JET1000         4      4      4         1          1        0
     102               L1_Mt15t15_100_rmovlp_JET100         0      0      0         1          1        0
     103          L1_Mt15t15_100_rmovlp_JET100_Lead         2      2      2         1          1        0
     200                             L1_Mt20t20_100         4      4      4         1          1        0
     201              L1_Mt20t20_100_rmovlp_JET1000         4      4      4         1          1        0
     202               L1_Mt20t20_100_rmovlp_JET100         0      0      0         1          1        0
     203          L1_Mt20t20_100_rmovlp_JET100_Lead         2      2      2         1          1        0
     301          L1_t20t20_dR_Min0p2_rmovlp_JET100         3      3      3         1          1        0
     302     L1_t20t20_dR_Min0p2_rmovlp_JET100_Lead         7      7      7         1          1        0
                                                      Final OR Count = 10
===========================================================================================================
</pre>

**Comment by rekovic** [comment]
@tmatsush Thanks for the comments above.  They are not addressed, as the logic of combining overlap removal cuts is done with bitwise operations.

**Comment by rekovic** [comment]
The above short test of L1T emulation is done with 10 events of PhaseIFall16 VBFToTauTau GEN-SIM.
(Updated the comment above.)

**Comment by rekovic** [comment]
replace with cleaner https://github.com/cms-l1t-offline/cmssw/pull/502

**Pull request closed without merging**
