### PR TITLE
uGMT loads LUTs from condFormat

### PR DESCRIPTION
**Pull request by thomreis**
In the uGMT emulator LUTs are now loaded from the condFormat l1t::LUT object instead of from a file.

### CODE REVIEW

**Comment by thomreis** [comment]
@mulhearn , @rekovic could you have a look at this PR please. This is essential for configuring the uGMT from the o2o.

**Comment by thomreis** [comment]
I have added the fix for the handling of the increased EMTF hwPhi range that was discussed in the meeting today to this.

**Comment by mulhearn** [comment]
OK, we are going to start a dedicated o2o integration branch, however, because these changes can't go in develop branch as they'll slow merging with CMSSW for ~806 timescale.

**Comment by thomreis** [comment]
You can leave out the commits https://github.com/cms-l1t-offline/cmssw/pull/246/commits/64bb61ef2e8b07c15a1d7c66f5547f9e6de1c7e6 and https://github.com/cms-l1t-offline/cmssw/pull/246/commits/c3cb35ccd2db516d37b7f77720a9c2634c69e4eb since these are the only ones that are directly related to o2o. The rest is just using differently what is already in the conditions format.

**Comment by thomreis** [comment]
@rekovic what is the status of this PR? What prevents if from being merged?

**Comment by thomreis** [comment]
This PR is superseded by https://github.com/cms-l1t-offline/cmssw/pull/296 which has all commits except 64bb61ef2e8b07c15a1d7c66f5547f9e6de1c7e6 and c3cb35ccd2db516d37b7f77720a9c2634c69e4eb which will go in the O2O branch.

**Pull request closed without merging**
