### PR TITLE
Change tracker HT jet selection

### PR DESCRIPTION
**Pull request by cgsavard**
This PR changes the jet selection that goes into tracker HT. These cuts were studied as part of a larger L1 track jet study and were found to outperform the current HT jet selection cuts (seen in slide 7 [here](https://indico.cern.ch/event/1340389/contributions/5642800/attachments/2741793/4769440/GTT_trkjet_27_10_23.pdf)).

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
HI @cgsavard Could you open a PR for these changes up to CMSSW?

@epalencia This looks simple enough to just merge here, I am going to go ahead and do that.

**Comment by epalencia** [comment]
Tagged as `phase2-l1t-1330pre3_v3`.

**Comment by aloeliger** [comment]
While I am thinking about it, @mcepeda and @artlbv I want you to be aware that this has been merged and will be available from v3 onwards since it affects jet definition somewhere.

**Comment by artlbv** [comment]
hi there, thanks for referencing us!

Is there a plan to present this algorithm updates to the L1 DPG? 
I see some points (from the linked slides) that probably should be discussed, e.g. the rate increase, the energy scaling etc.
I would also like to ask you to include the "online-offline scalings" that you obtain with the menu tools for the new/alternative HT definitions -> you should already get these plots when you did the trigger turnon curves.

Thanks! Artur

**Comment by cgsavard** [comment]
Hi @artlbv, I do not currently have plans to show this to the L1 DPG, but certainly can if they would like to see this. 

The GTT group is in favor of not actually applying a scaling and instead including one more plot in the menu plots that compare the puppi, calo, and tracker HT at the same rate. This is because the scaling is an estimation whereas the rate is a physical limitation so is a more fair comparison. It sounded like the menu team was willing to do this last we chatted with them (I believe Cristina was the one we talked briefly with but could be mistaken). Therefore the scaling portion should actually be ignored in the presentation linked.

I do have an updated menu plot for HT that I didn't show in the presentation linked that I will include below showing the improvement before (first plot) and after (second plot) the HT definition change.
image
image

**Comment by cgsavard** [comment]
@aloeliger I can definitely include a PR with this change in central CMSSW, but think I should wait for the track selection changes to also be made to l1t-offline and make the changes at the same time in CMSSW (seen in slide 6 [here](https://indico.cern.ch/event/1340389/contributions/5642800/attachments/2741793/4769440/GTT_trkjet_27_10_23.pdf)). The reason this was not done in this PR is because there are other PRs open right now that make changes to the same track jet files I would need to change to make the track selection changes. I will open another PR as soon as the current PRs are done and then open one into central CMSSW.

**Pull request merged**
