### PR TITLE
Update uGT code to read prescales from db

### PR DESCRIPTION
**Pull request by apana**

### CODE REVIEW

**Comment by rmanzoni** [comment]
hi @apana, 

I do need to use this tool, can you provide a working recipe to use this already?

I tried to:
* merge it on top of the latest 90X, didn't merge properly (a minor amount of force does it though)
* merge it on top of l1t-integration-v91.7, compiles, but gives poisoned plugin at runtime

While it's true things could be made massaged, it's true also it's not an optimal approach.

Thanks

**Comment by rekovic** [comment]
After resolving conflicts, a version of this is merged in l1t-integration-CMSSW_9_0_0_pre2 and tagged as l1t-integration-v91.11

**Comment by rekovic** [comment]
@rmanzoni 

Try tag l1t-integration-v91.11.
Try the provided test configuration file which uses a GlobalTag, in this case `90X_dataRun2_v0`
<pre>
cmsRun L1Trigger/L1TGlobal/test/runGTSummary.py
</pre>

**Comment by rmanzoni** [comment]
hi @rekovic 

I followed this installation recipe
```
cmsrel CMSSW_9_0_0_pre2
cmsenv
git cms-init
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git 
git fetch cms-l1t-offline
git cms-merge-topic -u cms-l1t-offline:l1t-integration-v91.11
```

and compiled, but it gets stuck at 

```
/afs/cern.ch/work/m/manzoni/diTau2015/L1prescales/CMSSW_9_0_0_pre2/src/L1Trigger/L1TMuonEndCap/src/PrimitiveConverter.cc: In member function 'std::vector<ConvertedHit> PrimitiveConverter::convert(std::vector<L1TMuon::TriggerPrimitive>, int)':
/afs/cern.ch/work/m/manzoni/diTau2015/L1prescales/CMSSW_9_0_0_pre2/src/L1Trigger/L1TMuonEndCap/src/PrimitiveConverter.cc:263:26: error: 'LogDebug' was not declared in this scope
  LogDebug("L1TMuonEndCap") << "\n*********************************************************************" << std::endl;
                          ^
/afs/cern.ch/work/m/manzoni/diTau2015/L1prescales/CMSSW_9_0_0_pre2/src/L1Trigger/L1TMuonEndCap/src/PrimitiveConverter.cc:400:26: error: 'LogDebug' was not declared in this scope
  LogDebug("L1TMuonEndCap") << "\n#####################################################################" << std::endl;
                          ^
```

**Comment by rekovic** [comment]
Sorry about that, there was a missing include statement, so easy fix.

Please retry with v91.11.1.

**Comment by rmanzoni** [comment]
thanks Vladimir, this works.

Can I ask also:
1. is there a back port to 80X?
2. is there an example of accessing to the L1 PS not event by event, but rather LS by LS, e.g. in the beginLumi method of the analyser?

The reason of these questions is that I need to have the L1 PS information in my analysis ntuples, which are bound to be produced in 80X, so option 1. would serve the scope directly. But if option1. is not in the plans, I thought I could use
```
cmsRun L1Trigger/L1TGlobal/test/runGTSummary.py
```
in such a way to produce a table of L1 PS by LS which I can then access however I like.
In this case, it' be way more convenient to access PS on a single LS base, rather than for each event.

Or maybe you know of a third and more obvious way to accomplish my goal.

Thanks

**Comment by rekovic** [comment]
@rmanzoni 

We can provide a backport of this functionality to 80x.
Indeed, this info should be accessed at the LumSection, no need to do it on per-Event basis.

Will follow up here with news on developments.

**Comment by fwyzard** [comment]
Hi Riccardo,

On 14 February 2017 at 15:12, Riccardo Manzoni <notifications@github.com>
wrote:

> is there an example of accessing to the L1 PS not event by event, but
> rather LS by LS, e.g. in the beginLumi method of the analyser?


while the prescale index should change only from LS to LS, technically it
is accessible only from the event data (from the uGT digis).

What we used to do is to set a flag in the beginLumi method, and the check
the prescale index in the first event of each lumisection.

.A

**Pull request closed without merging**
