### PR TITLE
Fix of track address mismatch between KBMTF and uGMT emulators and unpackers

### PR DESCRIPTION
**Pull request by dinyar**
Hi @rekovic,

this PR changes how KBMTF fills its track address fields and how uGMT emulator uses them. In firmware there are four fields for track addresses, three of them with 4 bit width and one with 2 bit width. For legacy BMTF the shorter field was used for the station 1 data, while for KBMTF we use the shorter one for the station 4 data. The KBMTF emulator puts the data for station 4 into the field labeled station 0 (etc.) and currently also the uGMT ghost busting logic expects this. I think this will be confusing in the long run. It's also inconsistent with what the unpacker is now doing and would lead to mismatches when we run at P5.

I have pinged @bachtis and @panoskatsoulis about this, please wait for their ok before merging.

Cheers,
Dinyar

### CODE REVIEW

**Comment by bachtis** [comment]
@rekovic  please don not merge this- it will break everything. Starting a discussion with @dinyar offline on this

**Comment by bachtis** [comment]
@rekovic We cleared that out . This is reasdy to go on my side. @dinyar I guess our only thing to worry about is what in the emulator is station 1 should be called station 1   and no station 4 . Which is fine for us

**Comment by dinyar** [comment]
Hi @rekovic,

Could you please merge this and submit it to central CMSSW together with the changes in #838 and #840? We need these for displaced muon propagation to the uGT.

Cheers,
Dinyar

**Comment by dinyar** [comment]
Hi @rekovic,

these changes together with the ones in #838 and #840 would be really good to have in CMSSW for the next MWGR. Apart from needing to be tested in general we'd like to propagate the displaced muon information to the uGT and to the scouting system as soon as possible, but we're blocked until the changes in the unpacker land.

Cheers,
Dinyar

**Pull request merged**
