### PR TITLE
Update HGC TP version to v3.10.2

### PR DESCRIPTION
**Pull request by cerminar**
Among the most relevant changes:

   * change TC selection thresholds in FE concentrator from 1.5 to 1.3MIPT
   * update EG ID selection to recover efficiency with new V9 geometry (and adapted to new TC selection)
   * fix a bug in cluster seeding at high eta -> reduce artificial cluster splitting in this region 

For reference, the performance of this new version for the EG trigger in terms of efficiency, rate and turn-on scaling is demonstrated in:

https://indico.cern.ch/event/832387/contributions/3487566/attachments/1872777/3087049/19-07-02_EndcapPerf_L1TEGP2.pdf

@gpetruc @jbsauvan you might want to follow this.

### CODE REVIEW

**Comment by rekovic** [comment]
@cerminar 
I understood from @gpetruc that this PR "as is" gives a slightly worse performance than what currently implemented.  Can either of you confirm that you are OK if we hold this PR and not merge it till you see that the performance is improved.  Thanks.

**Comment by cerminar** [comment]
Hello @rekovic, 
there is indeed a slight degradation of the TP performance @ PU200 however we need to keep using the most up-to-date TP version, I see no alternative.
In particular, this is the version that has been used to tune the new EG ID. we need to start using it for rate evaluation.

**Comment by gpetruc** [comment]
Is all or part of the HGC changes already in the 10_6_1_patch2 branch?
(that new branch is rebase and not a merge, so one can't just merge this PR into that branch)

**Comment by jbsauvan** [comment]
The HGC developments have recently been rebased on top of 10_6_1_patch2:
https://github.com/PFCal-dev/cmssw/tree/hgc-tpg-CMSSW_10_6_1_patch2

**Pull request closed without merging**
