### PR TITLE
Triplet emulator 14 0 0 pre3

### PR DESCRIPTION
**Pull request by gkaratha**
Triplet emulator to CMSSW 14! after some tries and help from @aloeliger . Original PR: gtt triplet emulator #1190 

Best,
George

### CODE REVIEW

**Comment by aloeliger** [comment]
@gkaratha Thanks for this. Would you please immediately open a PR for central CMSSW as well? We are likely going to merge this ASAP to begin getting the menu team something for validation.

If there are required data externals, please open a PR for those, or let us know that the data directory is missing, ASAP as well.

**Comment by gkaratha** [comment]
Dear @aloeliger ,

I already made a PR to the central cmssw.

**Comment by aloeliger** [comment]
@gkaratha Any data externals necessary?

**Comment by gkaratha** [comment]
not sure what that is. You mean files under data folder? If yes, no none

Best,
george


________________________________

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by gkaratha** [comment]
"L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc" is not one of my files. Not pushed from my PR (not sure why is reported here)

**Comment by aloeliger** [comment]
@gkaratha To start providing the menu team validation material, we are going to merge this PR immediately. I can see that a CMSSW PR is already open, thank you for that. @epalencia FYI.

**Pull request merged**
