### PR TITLE
E2E NNVtx: A L1T Phase 2 Vertexing algorithm using End to End NN (CMSSW14)

### PR DESCRIPTION
**Pull request by BenjaminRS**
#### PR description:

This PR holds the E2E NNVtx code for P2 L1T Primary Vertex Reconstruction. The work has been presented many times over the years including in:
https://cds.cern.ch/record/2792619?ln=en
https://cds.cern.ch/record/2814727?ln=en
And most recently: https://indico.cern.ch/event/1356822/#58-update-on-e2e-nnvtx

It should be noted that this is not a "full" emulation of the NNs but uses bit accurate inputs to a tensorflow session. Once the hls4ml emulation is complete for cmssw we can update the code.

This PR has been ported to be on top of CMSSW14 (from https://github.com/cms-l1t-offline/cmssw/pull/1191) and the model files are now going into cms-data: https://github.com/cms-data/L1Trigger-VertexFinder/pull/1 and https://github.com/cms-data/L1Trigger-L1TTrackMatch/pull/1

#### PR validation:

Previously under https://github.com/cms-l1t-offline/cmssw/pull/1191 the following validations were performed:
This PR passes the following checks: 
 scram b
scram b code-format 
scram b code-checks
scram b runtests
runTheMatrix.py -l limited -i all --ibeos
time cmsRun L1Trigger/L1TTrackMatch/test/L1TrackObjectNtupleMaker_cfg.py

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This PR will need to be ported to master once complete here.

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@epalencia Since this has been reviewed already, any objections to just merging this and starting the PR to CMSSW already?

**Comment by aloeliger** [comment]
@BenjaminRS This is being merged to provide validation material for the menu team. If there is no PR open to main CMSSW for this PR, please do so immediately. @epalencia FYI.

**Pull request merged**
