### PR TITLE
L1 Phase2 EG development

### PR DESCRIPTION
**Pull request by cerminar**
The PR implements some of the changes presented [EG Phase2 talk @ CIEMAT workshop](https://indico.cern.ch/event/791517/contributions/3341340/attachments/1818880/2975405/19-03-25_EGPerf_L1TWkshp_v1.pdf).

1. Brem recovery and cluster merging (will need further tuning once EG ID will be tuned for new geometry)
2. Hadron energy cleaning for HGC clusters passing EG ID.
3. Equip electron track matching producer to implement cuts on track quality: # of stubs and chi2
   
**NOTE I:** Point (1) and (2) will go in EG objects with `hwQual == 3` 

**NOTE II**: Since this version `hwQual > 2` will result in duplicated clusters, please require equality i.e `hwQual == 2` or `hwQual ==  3`.

**NOTE III**: the default configurations in the `process.L1simulation_step` have not yet been changed....stay tuned.

In parallel (but not very relevant for the menu performance studies) some of the EG analysis code is pushed in the integration branch to ease maintenance.

### CODE REVIEW

**Comment by rekovic** [comment]
@cerminar Thanks.

> NOTE III: the default configurations in the process.L1simulation_step have not yet been changed....stay tuned.

What changes do you have in mind?  Changing of some InputTag, or introducing a hwQual cut value for `L1TkElectronsHGC`, or something else ?

**Comment by cerminar** [comment]
Hello @rekovic I would like to change the quality criteria for the tracks used for the isolation in the endcaps (as presented in Madrid).

**Comment by rekovic** [comment]
@cerminar 
I see.
Have you settled on the track criteria for the iso, i.e. should we wait for the changes, which I presume would be just configuration changes, or should we merge this as is and use it in the Menu? At least non-iso part will be the same in any case?

**Comment by cerminar** [comment]
Commit will arrive in the next minutes.

**Comment by cerminar** [comment]
@rekovic I think I am now happy and this PR is ready from my point of view.

**Pull request merged**
