### PR TITLE
Pull Request for L1 Track Jets code and Displaced Jet DataFormat 

### PR DESCRIPTION
**Pull request by rekovic**
This replaces https://github.com/cms-l1t-offline/cmssw/pull/738
which was made to the wrong branch.

### CODE REVIEW

**Comment by rekovic** [comment]
@rpatelCERN 

These huge files do not seem to be used.  Can you please remove them?
```
L1Trigger/TwoLayerJets/python/Log0
L1Trigger/TwoLayerJets/python/Log1
L1Trigger/TwoLayerJets/python/Log2
```

**Comment by rekovic** [comment]
@rpatelCERN  

There is an already available `L1TrackerJets` module  from
```
L1Trigger/L1TTrackMatch/python/L1TrackerJetProducer_cfi.py
```
which we are currently using in the sequence ?  

Is `TwoLayerJets` from
```
L1Trigger/TwoLayerJets/python/TwoLayerJets_cfi.py
``` 
meant to replace it ? Or should both be ran ? 
Which on is supposed to be tested for the eff and rates and potentially go into the menu ?


`L1TrackerEtMiss` is still the same module name and its configuration changed, which is fine.

**Comment by rekovic** [comment]
Also, when running in the sequence, there are error messages

```
%MSG-e L1TrackerEtMissProducer:  L1TrackerEtMissProducer:L1TrackerEtMiss  26-Feb-2019 10:29:40 CET Run: 1 Event: 1777

Warning: VertexCollection not found in the event. Exit
%MSG
```
Please fix.

**Comment by rpatelCERN** [comment]
Hey Vladimir, 

So this package
`L1Trigger/TwoLayerJets/python/TwoLayerJets_cfi.py `
includes the two layer track jets that we are developing firmware for. 
This package:
`L1Trigger/L1TTrackMatch/python/L1TrackerJetProducer_cfi.py`
only runs the fastejt algo over an input collection of TTTracks. 
The tracker jets for menu comparisons would be from the collection made by TwoLayerJets


I have a few commits that would fix the vertex collection error and also  prevent some memory leaks in the TrackJet code. I will try to have these commit soon. 

-Rishi

**Comment by rekovic** [comment]
@rpatelCERN 
What about the TrackerHT?
Do you plan to update/provide the calibrated jets which are used to compute TrackerHT and is the final object TrackerHT going to be updated ?

**Comment by rekovic** [comment]
@rpatelCERN 
Can you please provide TrackerHT which is computed with calibrated TrackerJets with
|eta| < 2.4 and TrackerJet pT >30 GeV, to be able to compare to the PF HT.
Thanks

**Comment by rekovic** [comment]
Attention @bundocka.

**Comment by rekovic** [comment]
Also Attention @skinnari.

**Comment by rpatelCERN** [comment]
Hey Vladimir, 

For the track jets we only account for the charged part of the jet from L1 Tracks, and currently do not calibrate for the neutrals.  We did not plan on calibrating them.

The turn on for the track jets and the PF Jets at the same L1 Rate are used to compare performance. 

I updated the MHT module to read in the Track Jets and output an object of type L1TkEtMissParticle. 

According to the dataformat here: DataFormats/L1TrackTrigger/interface/L1TkEtMissParticle.h  
This object stores both the MHT and the HT and has separate call functions to access each value. So the same module L1TkHTMissProducer.cc should compute both. I am running checks through my ntuples to check for any mishaps, but don't expect to make any new commits to this pull request if all checks pass.

**Comment by rpatelCERN** [comment]
Hey Vladimir, 

These are my last commits fixing a few things in the python files. And adding an NPs stubs requirement for track quality in the two layer jets. Would you be able to merge these commits?

-Rishi

**Comment by rekovic** [comment]
@rpatelCERN Thanks.

**Comment by rekovic** [comment]
@rpatelCERN 

You should not have removed `L1TkCaloHTMissVtx`by these two lines 
[line 14](https://github.com/cms-l1t-offline/cmssw/pull/744/files#diff-ca844a5277aae680a464ae1d0d4d7a11L14)
[line 15](https://github.com/cms-l1t-offline/cmssw/pull/744/files#diff-ca844a5277aae680a464ae1d0d4d7a11L15)

This is fixed and also added `TwoLayerJets` module,  in the integration branch tag `l1t-phase2-v2.17.14.1`,

**Comment by rekovic** [comment]
@rpatelCERN 

Let me summarize here what is my understanding what is to be used from this PR.  Please correct or add if anything is missing.

 * We have the standard TrackerMET instance ` L1TrackerEtMiss` which is calculated with L1TTracks
```
 L1TrackerEtMiss = cms.EDProducer('L1TrackerEtMissProducer',
     L1TrackInputTag = cms.InputTag("TTTracksFromTracklet", "Level1TTTracks"),
```

 * There are two different producers for Tracker Jets.
1. "L1TrackerJetProducer"  instantiated as
    `L1TrackerJets = cms.EDProducer("L1TrackerJetProducer" `
1. "TwoLayerJets"  instantiated as 
`TwoLayerJets = cms.EDProducer('TwoLayerJets',`

 * The 1st one is designed for **Stand Alone Jets**.
 * The 2nd one is designed for **HTM** and **HTT** and it is used as input for L1TkHTMissProducer, which is instantiated as
 `L1TrackerHTMiss = cms.EDProducer("L1TkHTMissProducer",` with 
  `    minJetPt = 5 GeV`

The same L1TkHTMissProducer stores in its product both the HTM and  HTT values, acessible via EtMiss( ) and EtTotal( ).
In the menu we are interested in HTT performance evaluated against offline HTT calculated with offline  jets Pt > 30 & |eta| < 2.4, the above `L1TrackerHTMiss` instance of this module should nevertheless be used as is, and `minJetPt = 5 GeV` value left as is.

**Comment by rekovic** [comment]
Updated comment above,  to use `L1TrackerHTMiss`module instance 'as is' for `HTT`.

**Comment by rpatelCERN** [comment]
Hey Vladimir, 

For 1. and 2. you are correct. The first module in 1. was a placeholder that just takes an input collection of tracks and clusters them with the FAST Jet algo. 2. is the track jets we intend to use at L1 and it is the algorithm that will be on the TSA board. The one in 2.) will indeed be used for HT and MHT, BUT you should NOT change the minJetPt cut this is the online value for computing HT/MHT. 

For the menu, I have been in contact with Cristina, she will derive the online / offline scaling for these values using genMHT and genHT. It is already done for the PF, and the ones for TkJets will be larger but this will give the same turn on plots I showed for a fixed L1 Rate. I confirmed this with Cristina as well. Does this make sense?

-Rishi

**Comment by mcepeda** [comment]
Hi Rishi,

Sorry to ask for confirmation on a point: we should move to "TwoLayerJets" for everything (jets and HT), and we can phase out the older Fast Jet version.

(Ie in Vlad's post "The 1st one is designed for Stand Alone Jets." is not correct, for Standalone Tracker Jets we also need to move to the newer algorithm)

Or do you mean we only need to be looking at HTT/MHT and not try to do pure Jet seeds?

Thanks,

Maria

**Comment by rpatelCERN** [comment]
Hey Maria, 

Yes that is correct. The Fast Jet version is not intended to be used for the L1 Menu in 1. I commit that a while ago just as a place holder for Stand alone track jets and to do cross-checks with the TwoLayer Jets which is what were developing for use in the L1 menu. For the L1 Seeds please use the TwoLayer Jets. I have already included them as the input collection for L1TkHTMissProducer for HTMiss and HT. So I think you can use the edm objects produced by this module for the online TkHT and TkMHT. 

-Rishi

**Comment by rekovic** [comment]
@rpatelCERN 
Thanks Rishi.
So TwoLayerJets is to be used as StandAlone Jet seed, and not the L1TrackerJets.  
Clear.

**Pull request merged**
