### PR TITLE
GMT: Add ap_data type for GT interface

### PR DESCRIPTION
**Pull request by zhenbinwu**
#### PR description:

As requested by GT team, we added data type as ap_data for the standalone muon and tracker muon, for the GT emulator. 

#### PR validation:

The new ap_data type preserve the same info as int type.

### CODE REVIEW

**Comment by HaarigerHarald** [comment]
Great! Could you maybe also change your z0 scale to be on the same one that GTT and correlator uses (i.e. lsb = 0.5 mm)?

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 3 files that did not meet formatting requirements:
 - DataFormats/L1TMuonPhase2/interface/Constants.h
 - DataFormats/L1TMuonPhase2/interface/SAMuon.h
 - DataFormats/L1TMuonPhase2/interface/TrackerMuon.h

Please run `scram b code-format` to auto-apply code formatting

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code check issues!

**Comment by aloeliger** [comment]
@zhenbinwu Thanks for this PR. Is there anything that makes this PR incomplete? i.e. is it waiting on other emulator elements, configurations, or further/previous elements in the L1 chain?

**Comment by zhenbinwu** [comment]
@HaarigerHarald Ok, I have updated the z0/d0 LSB & range for the tracker muon and standalone muon. We should propagate this to the interface doc.

@aloeliger  This PR adds a type converter for the GT emulator output. Once the GT team verifies this work, I think it is OK to merge. No other elements waiting.

**Comment by aloeliger** [comment]
Okay. If this PR is independent from anything else, is there anything that would prevent it from going in central CMSSW?

**Comment by HaarigerHarald** [comment]
@zhenbinwu just for my understanding the GMT track matching algorithm was already internally using the GTT scale? Cause I see the only thing that changed was the scales for conversion to physical values but the whole internal logic of how the hardware values are handled stayed the same.

**Comment by zhenbinwu** [comment]
@HaarigerHarald For tracker muon, we used ap_int type internally in the emulator and then convert to integer. To keep this PR clean, I add another conversion to ap_int type.

For the Standalone muon, we are using the phase 1 uGMT muons as a temporary solution. We used the physical values and convert them to HW value, based upon the target LSB. I think that is what you saw in this PR.

**Comment by HaarigerHarald** [comment]
@zhenbinwu I think I found what I was worried about at: https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1252patch1/L1Trigger/Phase2L1GMT/plugins/TrackConverter.h#L59

Meaning the internal representation also changes if you change your constants. Ok, looks good to me. Thanks

**Comment by zhenbinwu** [comment]
@HaarigerHarald Mm.. this part of the code is historical. I think the Z0 LSB is still updated. But I do agree using TrackWord will be better for future. We will coordinate in the firmware to make sure this is propagated consistently.  

Maybe in next update of the GMT emulator. Don't see a stop sign for this PR.

**Comment by aloeliger** [comment]
@zhenbinwu If this PR is independent from anything else, is there anything that would prevent it from going in central CMSSW? Are there any disruptions to Phase 1 functioning present here? It doesn't look like it to my eyes, but I'd like to hear confirmation. I noticed you are changing data formats here with checksums in CMSSW. It doesn't look like anything should break backwards compatibility, but I wanted to confirm with you that you had checked that.

**Comment by zhenbinwu** [comment]
@aloeliger This PR is independent. Nothing prevent it from going to central CMSSW and no disruption to Phase 1. We noticed a minor bug in the code and fix it as well. Thanks

**Comment by HaarigerHarald** [comment]
@zhenbinwu a9910c6e3cfd91e24f0601de16d25065a07a4e49 gives me an error when compiling CMSSW

> error: cannot convert 'const std::vector<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >, std::allocator<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> > > >' to 'const edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >&'

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR failed.

The following is the stderr of the compilation attempt:
```
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc: In constructor 'L1PhaseIITreeProducer::L1PhaseIITreeProducer(const edm::ParameterSet&)':
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:189:78: warning: 'edm::EDAnalyzer::EDAnalyzer()' is deprecated [-Wdeprecated-declarations]
  189 | L1PhaseIITreeProducer::L1PhaseIITreeProducer(const edm::ParameterSet& iConfig) {
      |                                                                              ^
In file included from /nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:25:
/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-patch/CMSSW_12_5_2_patch1/src/FWCore/Framework/interface/EDAnalyzer.h:43:20: note: declared here
   43 |     CMS_DEPRECATED EDAnalyzer();
      |                    ^~~~~~~~~~
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc: In member function 'virtual void L1PhaseIITreeProducer::analyze(const edm::Event&, const edm::EventSetup&)':
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/L1TNtuples/plugins/L1PhaseIITreeProducer.cc:370:9: warning: unused variable 'Z0' [-Wunused-variable]
  370 |   float Z0 = *z0Puppi;
      |         ^~
In file included from /nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/Phase2L1GMT/plugins/Node.h:6,
                 from /nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTProducer.cc:11:
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/Phase2L1GMT/plugins/TrackMuonMatchAlgorithm.h: In member function 'std::vector<l1t::TrackerMuon> Phase2L1GMT::TrackMuonMatchAlgorithm::convert(std::vector<Phase2L1GMT::PreTrackMatchedMuon>&, uint)':
/nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/Phase2L1GMT/plugins/TrackMuonMatchAlgorithm.h:108:35: error: cannot convert 'const std::vector<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >, std::allocator<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> > > >' to 'const edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >&'
  108 |         muon.setMuonRef(mu.muonRef());
      |                         ~~~~~~~~~~^~
      |                                   |
      |                                   const std::vector<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >, std::allocator<edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> > > >
In file included from /nfs_scratch/aloeliger/pr_1079/new/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1TGMTProducer.cc:10:
/nfs_scratch/aloeliger/pr_1079/new/src/DataFormats/L1TMuonPhase2/interface/TrackerMuon.h:44:72: note:   initializing argument 1 of 'void l1t::TrackerMuon::setMuonRef(const edm::Ref<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand, edm::refhelper::FindUsingAdvance<BXVector<l1t::RegionalMuonCand>, l1t::RegionalMuonCand> >&)'
   44 |     void setMuonRef(const edm::Ref<l1t::RegionalMuonCandBxCollection>& p) { muRef_ = p; }
      |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
gmake: *** [config/SCRAM/GMake/Makefile.rules:1712: tmp/slc7_amd64_gcc10/src/L1Trigger/Phase2L1GMT/plugins/Phase2L1GMTPlugins/Phase2L1TGMTProducer.cc.o] Error 1
gmake: *** Waiting for unfinished jobs....

```
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`2`|
|command|`cmsenv && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code check issues!

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!

**Comment by aloeliger** [comment]
@zhenbinwu Could you fix these compilation issues?

**Comment by zhenbinwu** [comment]
Ok, this compilation issue should be fixed. Local tests seem working fine.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code check issues!

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no files with code format issues!

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR passes available unit tests!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`cmsenv && scram b runtests`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

This PR does not change the EDM content of testing ntuples.

**Comment by aloeliger** [comment]
@zhenbinwu I think we're good on this from our side. Could you please squash these commits and open a PR to central CMSSW with these changes? (From this branch if possible and it wouldn't bring in extra commits, in a separate one that we could easily keep synchronized if not)

**Comment by aloeliger** [comment]
@zhenbinwu Just wanted to ping you again for squashing these commits and opening a PR to central CMSSW.

**Comment by zhenbinwu** [comment]
@aloeliger Thanks for the reminder. I missed your last message indeed.

Santi is using the changes from this PR. Once his tests are OK, I will make a PR to the central CMSSW. Thanks

**Comment by mcepeda** [comment]
@zhenbinwu  - jumping in... Santi is away with little connection until Monday. I have his code and I am following up with his low pt muon studies in his place, but since this PR is one of the really important ones for the P2GT work (we need muons), it would be great if you could the PR to central CMSSW for this part already.

**Comment by aloeliger** [comment]
And if you would please, squash it first.

**Comment by zhenbinwu** [comment]
@aloeliger  @mcepeda OK, squash the commits as requested.

Problematic with rebasing CMSSW/master. I made a fresh commit and PR to CMSSW master at #https://github.com/cms-sw/cmssw/pull/41277. I think we can close this PR.

**Comment by aloeliger** [comment]
We'll merge this when the central CMSSW PR is merged (or if there is urgent need for it in the IB)

**Comment by aloeliger** [comment]
Technically this is merged in central CMSSW, however @zhenbinwu  you have removed a previous class definition: https://github.com/cms-l1t-offline/cmssw/pull/1079/files#diff-c5f6f91f69e9ddc51c01c33bb7a065de94f611c3653ee6cc66b474ea771a6626L11-L12. You are not supposed to do this. ORP will demand a fix immediately and I will prepare it. I will also be opening a PR to this branch containing it. Before we can merge this branch, this fix will need to be integrated.

**Comment by zhenbinwu** [comment]
OK. Should I make another commit to the CMSSW PR? What is the procedure?

**Comment by aloeliger** [comment]
I will prepare the fix for central CMSSW. I will also open a PR to your branch here. Please pull that in then this can be merged.

**Comment by aloeliger** [comment]
@zhenbinwu Please merge https://github.com/zhenbinwu/cmssw/pull/1 and then we can merge this PR.

**Comment by aloeliger** [comment]
Tagged as l1t-phase2-v57

**Pull request merged**
