### PR TITLE
Add track address to RegionalMuonCand constructors

### PR DESCRIPTION
**Pull request by thomreis**
Add track address to RegionalMuonCand constructors.

### CODE REVIEW

**Comment by abrinke1** [comment]
+1

**Comment by thomreis** [comment]
Hi @rekovic could we get this in CMSSW soon to improve the DQM agreement?

**Comment by thomreis** [comment]
These changes are already merged in 9_4_x with https://github.com/cms-sw/cmssw/pull/20944

**Comment by rekovic** [comment]
This is already in CMSSW.
But will merge this into the integration as well.

**Comment by thomreis** [comment]
Closing this since the integration branch moves to the 94 release.

**Pull request closed without merging**
