### PR TITLE
Phase2 l1jets 10 5 x

### PR DESCRIPTION
**Pull request by truggles**
Setting up for L1CaloJets PR.  This builds Jets from the L1EG producer output of L1EG + unclustered ECAL + HCAL energy in the barrel and HGCal towers at higher eta and uses HF digis as well.

Outputs are a collections of BXVector<l1t::Jet> and a more detailed collection for studies and calibration.

The example scripts such as `L1Trigger/L1CaloTrigger/python/test_L1CaloJets_cfg.py` are running fine with reprocessing HGCal on 10_4 MTD samples.

To clarify, the calibrations for these caloJets are currently based on 93X samples without reprocessing the HGCal TPs.  It would be good to still integrate them into the L1Menu workflow to work out kinks while updated calibrations are produced.

### CODE REVIEW

**Comment by truggles** [comment]
This PR is ready to merge from my side.  Please let me know if there are concerns @rekovic

**Comment by rekovic** [comment]
Hi @truggles 

We see very poor efficiency in the barrel , on the order of 20%.   
The EndCap  efficiency is on the order of 80%,.
Can you please provide look into this and provide a fix.

Also, do you plan to provide us with CaloJetHT?  
If so, can you do it with the calibrated jets, with |eta| < 2.4 and CaloJet pT > 30 GeV.  Thanks.

What about CaloMET ?  Do you plan to provide this?

Attention @bundock and @skinnari.

**Comment by truggles** [comment]
Hi @rekovic,

I also see poor performance when applying the 93X calibrations to the 10_4_X samples even in the barrel region.  I am working on updating the calibrations based on running the code exactly as done in `L1Trigger/L1TCommon/test/reprocess_test_10_4_0_mtd5.py`

I did not plan on creating CaloJetHT.  I know @bundock mentioned CaloMET in the past.

**Comment by truggles** [comment]
Please refer to #747 for updated calibrations

**Pull request merged**
