### PR TITLE
L1t dqm cmssw 8 0 3

### PR DESCRIPTION
**Pull request by EsmaeelEskandari**

### CODE REVIEW

**Comment by swang373** [comment]
Hi @EsmaeelEskandari ,

I'll give this a test within the day.

**Comment by EsmaeelEskandari** [comment]
Thanks @swang373.

**Comment by EsmaeelEskandari** [comment]
Just as you know, the omtf is not needed to be tested and I commented it out.

**Comment by swang373** [comment]
@EsmaeelEskandari 
The code compiles and runs without a problem within a fresh CMSSW_8_0_3 release. The only thing that I've caught is that there is a massive overflow for the bmtf_hwGlobalPhi histogram, which you can see [here](https://swang373.web.cern.ch/swang373/bmtf_hwGlobalPhi.png). Should we adjust the range of that histogram?

**Comment by swang373** [comment]
Hi @EsmaeelEskandari ,
Please adjust the histogram range for bmtf_hwGlobalPhi and I'll merge in this pull request ASAP.

**Comment by swang373** [comment]
Hi @EsmaeelEskandari,
I'll merge in the request and update the global phi range.

**Pull request merged**
