### PR TITLE
Emulator fixes, unpacker updates and EtSum enum change

### PR DESCRIPTION
**Pull request by bundocka**
Summary:
- Fix to jet emulator: now find jets with seed up to kHFEnd (ieta=41)
- Changed EtSum enums "2" -> "HF", e.g. kMissingEt2 -> kMissingEtHF
- Added calo tower filter (temporary alternative until fix for validation event filter)
- Fix to demux eta to handle properly eta=29
- New MP and demux sums with and without HF added to emulator, unpacker and histos added to analyser 
- Fix to cosine coefficients used for calculating x- and y- components of Et and Ht
- Corrected use of kHFEnd to mpEta(kHFEnd) throughout emulator
- Updated jet sorting to use accumulated sort
- Update to JEC eta compression LUT to remove entry at eta=29, emulator now uses mpEta to retrieve value from LUT
- Updated MP7 buffer capture formatting to include extra sums in MP output

### CODE REVIEW

**Comment by rekovic** [comment]
@bundocka 

There are less emulated EtSum types than unpacked.

In a single event, taking BX=0, below are the BxVector<EtSum> types from EMULATOR (A column) and from EMUL+PACK+UNPACK (B column):

```
L1T COMPARISON :  EtSum type: A = 0    EtSum type: B = 0
L1T COMPARISON :  EtSum type: A = 11   EtSum type: B = 16
L1T COMPARISON :  EtSum type: A = 1    EtSum type: B = 11
L1T COMPARISON :  EtSum type: A = 12   EtSum type: B = 1
L1T COMPARISON :  EtSum type: A = 2    EtSum type: B = 12
L1T COMPARISON :  EtSum type: A = 13   EtSum type: B = 2
L1T COMPARISON :  EtSum type: A = 3    EtSum type: B = 13
L1T COMPARISON :  EtSum type: A = 14   EtSum type: B = 3
L1T COMPARISON :  EtSum type: A = 8    EtSum type: B = 14
L1T COMPARISON :  EtSum type: A = 20   EtSum type: B = 8
L1T COMPARISON :                       EtSum type: B = 20
```

I see that the emulator does not contain type 16 (corresponding to [kTotalEtEm](https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_9/DataFormats/L1Trigger/interface/EtSum.h#L37) at the 2nd position, while the unpacker does.  The rest of the EtSum types found 
their orders in the BxVector<EtSum> are the same in vector coming from EMUL and vector from EMUL+PACK+UNPACK.

When emulating and filling EtSums [in demux algorithm](https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_9/L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2DemuxSumsAlgoFirmwareImp1.cc#L134-L154) we are not emulating nor storing [kTotalEtEm](https://github.com/cms-l1t-offline/cmssw/blob/l1t-integration-CMSSW_8_0_9/DataFormats/L1Trigger/interface/EtSum.h#L37).
However, we do unpack them.

Is there a reason for this?

**Comment by rekovic** [comment]
@jimbrooke The above comment might be of interest to you.

**Comment by bundocka** [comment]
Hi Vladmir, 

We haven’t yet added the TotalEtEm to the emulator. This will come sometime this week, 
with some other emulator fixes, in separate pull requests :)

Cheers,
Aaron

**Comment by rekovic** [comment]
@bundocka 

OK.  
I will add a dummy place holder for TotalEtEm to be stored in EtSum vector
to be stored at index=1.   This should be replaced when the emulator for TotalEtEm is available.

**Comment by rekovic** [comment]
@bundocka 

On a slightly different note, but still regarding EtSums, when comparing EMUL (A) vs EMUL+PACK+UNPCK (B) there is a disagreement for EtSum types 11, 12, 13, and 14:

```
kMinBiasHFP0
kMinBiasHFM0
kMinBiasHFP1
kMinBiasHFM1
```

as can be seen in the print out below, the disagreement is always due to `pt`:

<pre>
L1T COMPARISON :  EtSum type: A = 12 vs B = 12
COMPARISON FAILURE:
A:  pt = 1e-06 eta = 0 phi = 0
B:  pt = 0 eta = 0 phi = 0
COMPARISON FAILURE:
A:  hwPt = 0 hwEta = 0 hwPhi = 0
B:  hwPt = 0 hwEta = 0 hwPhi = 0
COMPARISON FAILURE:
A:  hwQual = 0 hwIso = 0
B:  hwQual = 0 hwIso = 0
L1T COMPARISON FAILURE:  for type 12
L1T COMPARISON :  EtSum type: A = 2 vs B = 2
L1T COMPARISON :  EtSum type: A = 13 vs B = 13
COMPARISON FAILURE:
A:  pt = 1e-06 eta = 0 phi = 0
B:  pt = 0 eta = 0 phi = 0
COMPARISON FAILURE:
A:  hwPt = 0 hwEta = 0 hwPhi = 0
B:  hwPt = 0 hwEta = 0 hwPhi = 0
COMPARISON FAILURE:
A:  hwQual = 0 hwIso = 0
B:  hwQual = 0 hwIso = 0
L1T COMPARISON FAILURE:  for type 13
L1T COMPARISON :  EtSum type: A = 3 vs B = 3
L1T COMPARISON :  EtSum type: A = 14 vs B = 14
COMPARISON FAILURE:
A:  pt = 1e-06 eta = 0 phi = 0
B:  pt = 0 eta = 0 phi = 0
COMPARISON FAILURE:
A:  hwPt = 0 hwEta = 0 hwPhi = 0
B:  hwPt = 0 hwEta = 0 hwPhi = 0
COMPARISON FAILURE:
A:  hwQual = 0 hwIso = 0
B:  hwQual = 0 hwIso = 0
L1T COMPARISON FAILURE:  for type 14
</pre>

Is there a reason why  emulator sets pt to 1e-06 instead of 0 or is this a bug?

**Comment by rekovic** [comment]
> I will add a dummy place holder for TotalEtEm to be stored in EtSum vector
> to be stored at index=1. This should be replaced when the emulator for TotalEtEm is available.

Available and tagged as l1t-integration-v70.2

**Comment by bundocka** [comment]
Hi Vladmir, 

There is a fix to the min bias emulation in PR #381:

Apologies, I’ve started working in 8_0_12 and sent the PR to 8_0_9.

I’ll make another pull request from 8_0_9.

Cheers,
Aaron

**Pull request merged**
