### PR TITLE
Phase 2 add emulated Displaced Track HT(Miss) to GTT emulation buffers to GlobalTrigger

### PR DESCRIPTION
**Pull request by NJManganelli**
#### PR description:

This PR adds the GTT Displaced Track HT(Miss) word into the emulation buffers for GTT to GlobalTrigger (the buffers encoding jets, sums, vertices, etc. and eventually mesons, taus, isolated tracks...)

This is not time-sensitive, as Prompt and Displaced HT are not currently in GTT F/W

see also
https://github.com/cms-l1t-offline/cmssw/pull/1227

#### PR validation:

scram b code-checks
scram b code-format
scram b
cmsRun createFirmwareInputFiles_cfg.py maxEvents=200 format=APx inputFiles=... inserts displaced HT word into GTT buffers for OutputToGlobalTrigger

#### If this PR is a backport please specify the original PR and why you need to backport that PR. If this PR will be backported please specify to which release cycle the backport is meant for:

This will need a forward-port to master

### CODE REVIEW

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@NJManganelli As with the other PRs, we can merge this immediately. I will suggest here (again) that this is bundled with the other PRs in a PR to master.

**Pull request merged**
