### PR TITLE
Correlator Layer-2 : support emulation of with TMUX18 input + GT interface tweaks

### PR DESCRIPTION
**Pull request by cerminar**
#### PR description:

The PR introduces the following changes:
- support pattern file creation for Correlator Layer-2 e/gamma boards with TMUX18 Layer-1 inputs.
- tweak the GT interface, renaming the `isolation` and `quality` methods of HW GT object according to the new convention.
- set the charge of non-valid HW GT electron objects to 0.
- address precision of the `z0` parameter in TkElectron to have the same precision as in HW

### CODE REVIEW

**Comment by epalencia** [comment]
@cerminar , is this PR superseding https://github.com/cms-l1t-offline/cmssw/pull/1199?

**Comment by cerminar** [comment]
@epalencia , yes it is superseding #1199. I will close it as soon as I move the firmware CI to the new CMSSW branch. It should be done tomorrow.

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

Attempts to compile this PR succeeded!

|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -j 8`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found no issues with the code checks!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-checks && scram b -k -j 8 code-checks`|

I found no issues with the headers!
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 check-headers`|

**Comment by triggerDoctor** [comment]
Hello, I'm triggerDoctor. @aloeliger is testing this script for L1T offline software validation.

I found 1 files that did not meet formatting requirements:
 - L1Trigger/L1TMuon/src/MicroGMTConfiguration.cc

Please run `scram b code-format` to auto-apply code formatting
|    Info   |     Value    |
|:---------:|:------------:|
|return code|`0`|
|command|`eval `scramv1 runtime -sh` && scram b -k -j 8 code-format-all`|

**Comment by aloeliger** [comment]
@epalencia I have no review here. Would you be okay with just merging this and starting the PR to CMSSW?

**Comment by aloeliger** [comment]
@cerminar This is being merged to provide validation material for the menu team. If there is no PR open to main CMSSW for this PR, please do so immediately. @epalencia FYI.

**Pull request merged**
