### PR TITLE
Bmtf unpacker 8 0 7

### PR DESCRIPTION
**Pull request by eparadas**
It contains all the latest changes. Please merge it.

Thanks,
Vangelis

### CODE REVIEW

**Comment by akalinow** [comment]
@rekovic has reported crashes from the OMTF when reading data with this PR code.
I have found out that all DT digis in 1000 events have sector number equal to -1.
I suspect problem with unpacking sector number. @eparadas can you have look?
I was using following cmsDriver setup:

cmsDriver.py L1TEST --python_filename=l1t_test.py -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=80X_dataRun2_v13 -n 1000 --data --no_exec --no_output --filein=/store/data/Run2016A/ZeroBias1/RAW/v1/000/271/336/00000/00963A5A-BF0A-E611-A657-02163E0141FB.root --geometry=Extended2016,Extended2016Reco --customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by eparadas** [comment]
@akalinow by the cmsDriver I cannot what is going wrong with the code. Can you please put in your public area the BMTFUnpackerInputs.cc that you have? You should be able to find it under EventFilter/L1TRawToDigi/src/
It seems very strange to me that you have the -1 value. Also, can you let me know what is the name of the collection that contains the DT digis in the resulting root file?

**Comment by akalinow** [comment]
@eparadas the collections I use are following input collections:

cms.InputTag("bmtfDigis","PhiDigis")
cms.InputTag("bmtfDigis","TheDigis")

The code I have used comes from test-newBmtfUnpack-l1t-integration-CMSSW_8_0_7 branch:

https://github.com/cms-l1t-offline/cmssw/tree/test-newBmtfUnpack-l1t-integration-CMSSW_8_0_7

I make my printout in the following way:

 for (const auto digiIt: *dtPhDigis->getContainer()) {
    std::cout<<"code: "<<digiIt.code()<<" sector: "<<digiIt.scNum()<<std::endl;

**Comment by eparadas** [comment]
@akalinow it looks ok both the code you have for the unpacker and the way you access it. So let's do this: put in a public directory the code you have so that I can have a full look on that and also give me the Run number and the files you processed on order to analyze them as well.

**Comment by akalinow** [comment]
@eparadas please find the tar of my src area, and the l1t_test.py I use for running the test on my public area at CERN: /afs/cern.ch/user/a/akalinow/public

**Comment by eparadas** [comment]
@akalinow so the problem is that the run you are trying to analyze is a bit old and we had a slightly different version of the unpacker. I added a few lines and from now on it is compatible with any run (either new or old). Please check out again and let me know if it runs properly or not.

**Comment by akalinow** [comment]
@eparadas @rekovic I can confirm that the test runs now fine. Thank you.

**Pull request merged**
