### PR TITLE
EMTF BIG emulator update - attempt #2

### PR DESCRIPTION
**Pull request by abrinke1**
Port of PR 527 to CMSSW_9_2_0 
https://github.com/cms-l1t-offline/cmssw/pull/527

All comments addressed, should run out of the box.

### CODE REVIEW

**Comment by rekovic** [comment]
@abrinke1 
This PR does not compile.  Please check
<pre>
tmp/slc6_amd64_gcc530/src/L1Trigger/L1TMuon/src/L1TriggerL1TMuon/RegionalMuonRawDigiTranslator.o: In function `l1t::RegionalMuonRawDigiTranslator::fillRegionalMuonCand(l1t::RegionalMuonCand&, unsigned int, unsigned int, int, l1t::tftype)':
RegionalMuonRawDigiTranslator.cc:(.text+0x267): undefined reference to `l1t::RegionalMuonCand::setTFIdentifiers(int, l1t::tftype)'
collect2: error: ld returned 1 exit status
config/SCRAM/GMake/Makefile.rules:2017: recipe for target 'tmp/slc6_amd64_gcc530/src/L1Trigger/L1TMuon/src/L1TriggerL1TMuon/libL1TriggerL1TMuon.so' failed
gmake: *** [tmp/slc6_amd64_gcc530/src/L1Trigger/L1TMuon/src/L1TriggerL1TMuon/libL1TriggerL1TMuon.so] Error 1
gmake: *** [There are compilation/build errors. Please see the detail log above.] Error 2
</pre>

**Comment by abrinke1** [comment]
I assume the error is coming from the following line: 
https://github.com/abrinke1/cmssw/blob/EMTF_May_2017_merge/L1Trigger/L1TMuon/src/RegionalMuonRawDigiTranslator.cc#L77

I can't imagine anything being wrong here, and the base code for "setTFIdentifiers" is here:
https://github.com/abrinke1/cmssw/blob/EMTF_May_2017_merge/DataFormats/L1TMuon/interface/RegionalMuonCand.h

Neither of these files is changed in my PR.  Can you try the following?

cd DataFormats/L1TMuon; scram b clean; scram b -j 6
cd ../../L1Trigger/L1TMuon; scram b clean; scram b -j 6
cd ../../; scram b -j 6

I often find that the l1t-offline code fails to compile the first time, but re-compiles fine.

Thanks,
Andrew

**Comment by fwyzard** [comment]
> I often find that the l1t-offline code fails to compile the first time,
but re-compiles fine.

That usually means there is some real problem somewhere...

Ciao,
.Andrea

**Comment by abrinke1** [comment]
Perhaps; but I usually encounter this when I check out the code, before making any modifications.  So I'm not sure how to debug transient compile errors that are not part of my code.

**Comment by abrinke1** [comment]
(Not of course ruling out that there is still a bug in my code, but re-compiling should help locate it if it's there.)

**Comment by rekovic** [comment]
@abrinke1 
git cms-addpkg of DataFormats/L1TMuon solved the problem.

**Comment by fwyzard** [comment]
> (Not of course ruling out that there is still a bug in my code, but
re-compiling should help locate it if it's there.)


Sure, I didn't mean a bug in your code, but maybe already in the branch, or
in how it is merged.

.A

**Comment by rekovic** [comment]
@abrinke1 
Code compiles now, however, the unit-tests fail.  
An example of failing test:
<verbabim>
L1TEST --python_filename=l1t_test.py -s RAW2DIGI --era=Run2_2016  \
--customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW2015 \
--customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU \
--conditions=auto:run2_data -n 10 --data --no_exec --no_output \
--filein=/store/data/Run2015D/MuonEG/RAW/v1/000/256/677/00000/4A874FB5-585D-E511-A3D8-02163E0143B5.root \
--geometry=Extended2016,Extended2016Reco \
--customise=L1Trigger/Configuration/customiseReEmul.L1TEventSetupForHF1x1TPs \
--customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary \
--customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput
</verbatim>

Errors

<pre>
%MSG
----- Begin Fatal Exception 26-May-2017 17:35:08 CEST-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='emtfForestsDB'
Exception Message:
Unable to find plugin 'L1TMuonEndCapForestRcd@NewProxy' in category 'CondProxyFactory'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------
----- Begin Fatal Exception 26-May-2017 17:35:08 CEST-----------------------
An exception of category 'PluginNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing ESSource: class=PoolDBESSource label='emtfForestsDB'
Exception Message:
Unable to find plugin 'L1TMuonEndCapForestRcd@NewProxy' in category 'CondProxyFactory'. Please check spelling of name.
----- End Fatal Exception -------------------------------------------------
</pre>

**Comment by thomreis** [comment]
I had no problem compiling and running. I did not run from 2015 data though.

**Comment by abrinke1** [comment]
2015 data?!?  For one, EMTF did not exist in 2015 ... don't know if that causes any problems.  I guess if you're re-emulating from RAW, it should still run.

@kkotov the error has to do with "Forests" and "Cond" objects - can you take a look?

Thanks,
Andrew

**Comment by rekovic** [comment]
@abrinke1 
Yes, ReEmulating from RAW needs to run.
Emulating from DIGI has same problems.

@kkotov 
I already pinged you on #532 to rebase.

**Comment by kkotov** [comment]
You don't really need #532 for that one to run. The error suggests that this line had no effect:
https://github.com/abrinke1/cmssw/blob/EMTF_May_2017_merge/CondCore/L1TPlugins/src/UpgradeRecords2.cc#L21
I don't know how this is possible.

**Comment by abrinke1** [comment]
Hi @rekovic 

What is the "L1TEST" unit test?  Can I run it?  I don't see it referenced anywhere on the twikis:
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions
https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TOfflineDev

When I try to run the lines you pasted, I get the following error: "L1TEST: Command not found."

When I replace "L1TEST --python_filename=l1t_test.py" with "cmsDriver.py l1Ntuple", a config file "l1Ntuple_RAW2DIGI.py" is created, and I can run it.  The resulting L1Ntuple.root output file contains EMTF muons in the l1UpgradeTfMuonEmuTree (L1UpgradeEmtfMuon), which also appear in the l1UpgradeEmuTree (L1Upgrade).

If the error you're seeing is unrelated to Khristian's PR (as @kkotov seems to think), I'd rather figure out the problem within this PR (if there is one) and move on from there, instead of pulling in a new set of code first.

Cheers,
Andrew

**Comment by kkotov** [comment]
@abrinke1 , Vladimir gave us a list of arguments to the cmsDriver.py . L1TEST is a mode of running the cmsDriver. I tried it yesterday and it worked like a clockwork for this PR. So I don't know what went wrong in Vladimir's setup. I suspect he didn't install new CondCore/L1TPlugins locally.

**Comment by thomreis** [comment]
@abrinke1 The efficiency plots do not look good at all. Not sure where this comes from, but to be sure it has nothing to do with my setup I'll check it again.

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_v3/?match=absEtaMin1.24*

**Comment by thomreis** [comment]
The efficiency plots from yesterday contained a mix of configuration for 2016 and 2017 and should be ignored.
New efficiency plots with fixed configurations can be found here:

2016:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2016/?match=absEtaMin1.24*
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2016/?match=*.eta*

2017:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017/?match=absEtaMin1.24*
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017/?match=*.eta*

**Comment by abrinke1** [comment]
Added commits that should fix the 2016 re-emulation and the pT inefficiency in 2017 for |eta| < 1.85 that @thomreis saw.  The following configuration settings should be used for 2016 and 2017:

## 2016
process.emtfForestsDB.toGet = cms.VPSet(
    cms.PSet(
        record = cms.string("L1TMuonEndCapForestRcd"),
        tag = cms.string("L1TMuonEndCapForest_static_2016_mc")
        )
    )

process.simEmtfDigis.Era                       = cms.string('Run2_2016')
process.simEmtfDigis.RPCEnable                 = cms.bool(False)
process.simEmtfDigis.spTBParams16.ThetaWindow  = cms.int32(4)
process.simEmtfDigis.spPCParams16.FixME11Edges = cms.bool(False)
process.simEmtfDigis.spPAParams16.BugGMTPhi    = cms.bool(True)
process.simEmtfDigis.spPAParams16.BugNegPt     = cms.bool(True)

## 2017
process.emtfForestsDB.toGet = cms.VPSet(
    cms.PSet(
        record = cms.string("L1TMuonEndCapForestRcd"),
        tag = cms.string("L1TMuonEndCapForest_static_Sq_20170523_mc")
        )
    )

process.simEmtfDigis.Era                       = cms.string('Run2_2017')
process.simEmtfDigis.RPCEnable                 = cms.bool(True)
process.simEmtfDigis.spTBParams16.ThetaWindow  = cms.int32(8)
process.simEmtfDigis.spPCParams16.FixME11Edges = cms.bool(True)
process.simEmtfDigis.spPAParams16.BugGMTPhi    = cms.bool(False)
process.simEmtfDigis.spPAParams16.BugNegPt     = cms.bool(False)

**Comment by thomreis** [comment]
Efficiency plots for the 2017 configuration after https://github.com/cms-l1t-offline/cmssw/pull/542/commits/6da4fcdd764a1489ef3d7c4d4c617da39b22d938 can be found here:

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017_v2/?match=absEtaMin1.24*
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017_v2/?match=*.eta*

**Comment by abrinke1** [comment]
@thomreis This is great!  We're now seeing the expected behavior, including better SingleMu efficiency in the 1.2 < |eta| < 1.85 region (with RPC coverage): 

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017_v2/dataEmul_best_l1_muon_qualMin12_ptmin12_dr0.5_matched_probe_absEtaMin0_absEtaMax2.4_ptmin16.eta_over_probe_absEtaMin0_absEtaMax2.4_ptmin16.eta.png

@rekovic @thomreis Can we maybe sit down together briefly to discuss implementing the proper "Era" and data / MC re-emulation settings in the L1T Ntuplizer?  I think that's the last piece before this can go in.  I'd be free right after lunch, for example.

Thanks a bunch,
Andrew

**Comment by rekovic** [comment]
@abrinke1 @thomreis 
Good to see the efficiency back at expected level.

Sure, let's meet after lunch at 14h on skype.

**Comment by abrinke1** [comment]
Unfortunately merging PR #532 from @kkotov leading to unexpected behavior ... will need to hash it out on Monday or Tuesday.  I found the bug affecting the 2016 re-emulation, which is connected to the proper loading of primitive conversion conditions, i.e. O2O / CondFormats related stuff.

**Comment by abrinke1** [comment]
Merged PR #532, and added all the appropriate switches for O2O / CondFormats in the emulator.  Should now run out of the box on 2016/2016 data/MC, emulating with 2017 settings.  To emulate with 2016 settings, use the configuration below.

@thomreis Can you try running it? (yet again)

@kkotov There's one line I'd like to change in fakeEmtfParams_cff.py, which is this:
tag = cms.string("L1TMuonEndCapForest_static_Sq_20170523_mc")
This should be updated to the new v7 MC tag, whenever you can make it.

@bortigno @rekovic I modified L1Trigger/Configuration/python/customiseReEmul.py to switch OMTF from csctfDigis to emtfStage2Digis in 2017.  Take a look and see if you'd prefer it done differently.

@all, I didn't have time yet to move the data/emtf_luts folder, but I can do that if everything else checks out.

Thanks much,
Andrew 


## *** 2016 ***                                                                                                                                                                   
## From python/fakeEmtfParams_cff.py                                                                                                                                              
process.emtfParams.PtAssignVersion = cms.int32(5)
process.emtfParams.FirmwareVersion = cms.int32(49999) ## Settings as of end-of-year 2016                                                                                          
process.emtfParams.PrimConvVersion = cms.int32(0)
process.emtfForestsDB.toGet = cms.VPSet(
    cms.PSet(
        record = cms.string("L1TMuonEndCapForestRcd"),
        tag = cms.string("L1TMuonEndCapForest_static_2016_mc")
	)
    )

## From python/simEmtfDigis_cfi.py                                                                                                                                                
process.simEmtfDigis.RPCEnable                 = cms.bool(False)
process.simEmtfDigis.spTBParams16.ThetaWindow  = cms.int32(4)
process.simEmtfDigis.spPCParams16.FixME11Edges = cms.bool(False)
process.simEmtfDigis.spPAParams16.PtLUTVersion = cms.int32(5)
process.simEmtfDigis.spPAParams16.BugGMTPhi    = cms.bool(True)

**Comment by thomreis** [comment]
@abrinke1 should the printouts be silenced?
```
Getting PC LUT version from ConditionHelper
Configured with condition_helper_.get_pc_lut_version() = 1
Getting PC LUT version from ConditionHelper
coord_lut_path = L1Trigger/L1TMuonEndCap/data/emtf_luts/ph_lut_v2/
Getting pT LUT version from ConditionHelper
Configured with condition_helper_.get_pt_lut_version() = 7
Getting pT LUT version from ConditionHelper
Getting pT LUT version from ConditionHelper
Loaded forest for mode 3 with boostWeight_ = 0.245911
  * ptLUTVersion_ = 7
Loaded forest for mode 5 with boostWeight_ = 0.245132
  * ptLUTVersion_ = 7
```

**Comment by thomreis** [comment]
I get exceptions on the grid and locally:

```
Begin processing the 3347th record. Run 284036, Event 359759690, LumiSection 206 at 08-Jun-2017 12:29:17.611 CEST
----- Begin Fatal Exception 08-Jun-2017 12:29:17 CEST-----------------------
An exception of category 'StdException' occurred while
   [0] Processing  Event run: 284036 lumi: 206 event: 359759690 stream: 0
   [1] Running path 'L1TReEmulPath'
   [2] Calling method for module L1TGlobalProducer/'simGtStage2Digis'
Exception Message:
A std::exception was thrown.
vector::_M_range_check: __n (which is 18446744073709551612) >= this->size() (which is 256)
----- End Fatal Exception -------------------------------------------------
```
This happens with the 2017 and the 2016 configuration. I guess it is not related to the new EMTF emulator, since it comes from the GT emulator. There could be a problem with the integration tag 95.9

**Comment by thomreis** [comment]
Confirmed. The exception happens with vanilla integration tag 95.9 already.

**Comment by kkotov** [comment]
@abrinke1 Here are the new conditions:
https://cms-conddb.cern.ch/cmsDbBrowser/list/Prod/tags/L1TMuonEndCapForest_static_Sq_20170608_v7_mc

**Comment by abrinke1** [comment]
@rekovic What do I need to do to get permission to commit to / branch off /
PR to L1Trigger-L1TMuon?  Getting the following message:
Permission to cms-l1t-offline/L1Trigger-L1TMuon.git denied to abrinke1.

**Comment by thomreis** [comment]
I made the efficiency plots for run 284036 again with the latest commits included. Looks good in general. The 2016 emulator configuration matches well the 2016 data and the 2017 emulator shows higher efficiency for most of the time.

2017 configuration:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017_v3/?match=*.eta*
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2017_v3/?match=absEtaMin1.24*

2016 configuration:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2016_v3/?match=*.eta*
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/tagAndProbe/2017_284036_zmu_new_EMTF_2016_v3/?match=absEtaMin1.24*

**Comment by jiafulow** [comment]
Hi Thomas,

The emulator has a [function](https://github.com/abrinke1/cmssw/blob/bfab85e0/L1Trigger/L1TMuonEndCap/src/SectorProcessor.cc#L89) that adjusts the settings based on the firmware version as supplied by the Conditions (when running on real data). If you are trying to run the 2017 configuration on 2016 data, I think you have to override the firmware version to pretend that it's 2017 data, by appending this at the end:

```
process.emtfParams.FirmwareVersion = cms.int32(50000) ## version >= 50000 for 2017 data
```

But I don't expect this to be a big effect.

**Comment by thomreis** [comment]
Hi @jiafulow,
this is not what I understood from what @abrinke1 wrote above. In your code it says that this is for 2017 data, but I run on 2016 data here.
If I don't do it I get the following lines printed:
```
Getting firmware version from ConditionHelper
Running configure_by_fw_version with version 123456
```

**Comment by jiafulow** [comment]
From Andrew,

> Should now run out of the box on 2016/2016 data/MC, emulating with 2017 settings. To emulate with 2016 settings, use the configuration below.

But I think it's more correct to say:

- The default settings are now 2017 configuration. The emulator will work out of the box on 2017 data. It will also work on any MC, because MC doesn't use Conditions.
- Applying the extra configuration in his comment reverts the emulator to 2016 configuration. It will work on 2016 data, and any MC.

For running the 2017 configuration on 2016 data, I think we have to fake the firmware version so that the emulator treats it as 2017 data. If the Conditions says that the firmware version is <50000, the emulator still treats it as 2016 data. If >50000, treats it as 2017 data. If '123456', treats it as MC basically (which is actually fine if you want to run 2017 config on 2016 data).

But this is not super important. Let's wait for Andrew's comment first.

**Comment by thomreis** [comment]
The efficiencies on 2016 data with the default configuration (v123456) are exactly that same as with the FW version set to 50000.

**Comment by thomreis** [comment]
Rate comparisons on 2016 high PU run. LS 56-69. Single muon quality
Blue line: unpacked 2016 data
Red line: emulated rate with new EMTF emulator in 2017 configuration.

https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/rates/ZeroBiasBunchTrainsX_i95p11_LS56to69_newEMTF2017/?match=*comp*

Overall ~15% reduction @ 25 GeV threshold, with 30% reduction for EMTF only.

**Comment by abrinke1** [comment]
At long last, the new EMTF emulator should be *READY*.  Nothing functional has changed since @thomreis last ran it, so it should be ready for @rekovic to pull.  This PR incorporates all the necessary changes from @kkotov EMTF O2O PR #532 - I think that one can be closed.  My PR to L1Trigger-L1TMuon should be pulled in at the same time:
https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/pull/6

If you want to see the full history of commits over the last few weeks, it's here:
https://github.com/abrinke1/cmssw/commits/EMTF_May_2017_merge

@jiafulow the story with CondFormats and O2O is a bit complicated, but for most offline L1T emulation scenarios for studies, the data global tag (and thus the true firmware number) will be ignored, and the parameters from python/fakeEmtfParams_cff.py (or manual modifications to these) will be used instead.  For the Global Tag settings to override fakeEmtfParams, you have to explicitly include this line in your "cmsRun" python config:
process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

@all, let me know if you have any questions.

**Comment by abrinke1** [comment]
At long last, the new EMTF emulator should be *READY*.  Nothing functional has changed since @thomreis last ran it, so it should be ready for @rekovic to pull.  This PR incorporates all the necessary changes from @kkotov EMTF O2O PR #532 - I think that one can be closed.  My PR to L1Trigger-L1TMuon should be pulled in at the same time:
https://github.com/cms-l1t-offline/L1Trigger-L1TMuon/pull/6

If you want to see the full history of commits over the last few weeks, it's here:
https://github.com/abrinke1/cmssw/commits/EMTF_May_2017_merge

@jiafulow the story with CondFormats and O2O is a bit complicated, but for most offline L1T emulation scenarios for studies, the data global tag (and thus the true firmware number) will be ignored, and the parameters from python/fakeEmtfParams_cff.py (or manual modifications to these) will be used instead.  For the Global Tag settings to override fakeEmtfParams, you have to explicitly include this line in your "cmsRun" python config:
process.es_prefer_GlobalTag = cms.ESPrefer("PoolDBESSource","GlobalTag")

@all, let me know if you have any questions.  S.D.G.

**Comment by abrinke1** [comment]
@rekovic is there any reason this can't be pulled?  This emulator will provide a much better description of the data we're currently taking for rate and efficiency studies.

Cheers,
Andrew

**Comment by thomreis** [comment]
Data vs. emulator rate comparison plots with 2017 data can be found here:
https://treis.web.cern.ch/treis/cms/l1_muon_upgrade/rates/2017_296966-296977_ZeroBias_Run2017A_i95p11_newEMTF2017/?match=comp*emtf*

**Comment by thomreis** [comment]
@abrinke1 I think this needs a rebase.

**Comment by abrinke1** [comment]
@rekovic made the last PR to 1t-integration-CMSSW_9_2_0 three hours ago, so I assume he's still working through the PRs.  It would be nice to get this in soon though - it's been ready for 6 days, with no conflicts.  Also, it's important for ongoing L1T menu studies, which for now are still using the emulation from last year.

If it's still in CMSSW_9_2_0, it shouldn't need a rebase, right?

**Comment by rekovic** [comment]
@abrinke1 You don't need to rebase the PR. Conflict are being solved locally before merging.

**Comment by abrinke1** [comment]
Great!  Thanks all for the cross-checks and the help!

**Pull request merged**
