### PR TITLE
E/G and Tau changes for O2O

### PR DESCRIPTION
**Pull request by davignon**
@kkotov @rekovic @mulhearn @tstreble @jbsauvan @bundocka 

Dear all,

This PR concern E/G and Tau changes for the O2O.
With Khristian we decided to apply the changes to the l1t-integration branch before he picks them for the O2O.
All the changes are transparent to the user and fully consistent. The emulator gives the same results as before.

Summary of changes:
- Update of E/G and Tau parameters in config files (L1TCaloStage2ParamsESProducer.cc, caloStage2Params_2016*.py, caloParams_cfi.py).
- Update of Clustering, E/G and Tau emulators (Stage2Layer2ClusterAlgorithmFirmwareImp1.cc,Stage2Layer2TauAlgorithmFirmwareImp1.cc, Stage2Layer2EGammaAlgorithmFirmwareImp1.cc).
- Update of LUTs for E/G and Tau.

Please consider merging.

Cheers,
- Olivier

### CODE REVIEW

**Comment by davignon** [comment]
@kkotov @rekovic @mulhearn 
Sorry to bother you on this, but could please have a look and integrate?
Thanks a lot!

**Comment by kkotov** [comment]
@davignon , according to @bundocka 's last year studies your PR has solved most (all?) of the issues with data/re-emulation comparison using configuration from the O2O. Now it is up to @rekovic or @mulhearn to integrate your changes. As far as I know, Vladimir is going to be back from his vacations some time after the Orthodox Christmas (i.e. this week, I guess). I'll follow this work up with him once he is back to his office.

P.S. I think we may start moving on to the 9_0_X. I hope your changes are agnostic to the boost -> c++11 migration and should rebase with no conflicts.

**Comment by rekovic** [comment]
@davignon 

I don't see any EG objects, with these test jobs

<pre>
cmsDriver.py L1TEST --python_filename=l1t_test.py --conditions=auto:run2_mc -s DIGI,L1,DIGI2RAW,RAW2DIGI -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/Configuration/customiseUtils.L1TStage2ComparisonRAWvsEMU --customise=L1Trigger/Configuration/customiseUtils.L1TGtStage2ComparisonRAWvsEMU
</pre>

and

<pre>
cmsDriver.py --python_filename=l1t_test.py -s RAW2DIGI --era=Run2_2016 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMU --customise=L1Trigger/Configuration/customiseUtils.L1TTurnOffUnpackStage2GtGmtAndCalo --conditions=auto:run2_data -n 100 --data --no_exec --no_output --filein=/store/data/Run2016H/HLTPhysics3/RAW/v1/000/281/602/00000/0E71643D-BF82-E611-8593-02163E011B19.root --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalMenuXML
</pre>

or this one 

<pre>
cmsDriver.py L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --no_exec --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMUNoEventTree --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput
</pre>

**Comment by rekovic** [comment]
@davignon  ping.
Can you please look into this (see my comment above, we loose all EG objects in the tests above).

**Comment by davignon** [comment]
@rekovic 
I did see the E/G objects in the branch I created from l1t-integration-v89.12, even after the changes I made.
Were they any other changes that might have affected the E/G in the tag you are using for the tests?
Thanks.

**Comment by rekovic** [comment]
@davignon 

This branch (checked out alone) fails to report EG objects in the following test, which checks for presence of L1T objects:
`
cmsDriver.py auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output  --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-test/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMUNoEventTree  --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput`

The l1t-integration branch with tag l1t-integration-v89.12 (on which the development is based) does pass the above test.

Can you please check. 

<pre>
scramv1 p -n CMSSW_8_0_24_test_l1t_PR446 CMSSW CMSSW_8_0_24
cd CMSSW_8_0_24_test_l1t_PR446/src/
cmsenv
git cms-init 
git remote add cms-l1t-offline git@github.com:cms-l1t-offline/cmssw.git
git fetch cms-l1t-offline
git chk -b l1t-integration-CMSSW_8_0_24
git cms-merge-topic -u cms-l1t-offline:l1t-integration-v89.12
scramv1 b -j 8
# do the test

# now merge this branch
git checkout -b davignon-l1t-integration-v89.12-ForO2O l1t-integration-CMSSW_8_0_24
git pull https://github.com/davignon/cmssw.git l1t-integration-v89.12-ForO2O
scramv1 b -j 8
# do the test
</pre>

**Comment by davignon** [comment]
@rekovic 

I tried running your command straight out 89.12 (without the changes from this PR) and the command gives:
`
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/bin/slc6_amd64_gcc530/cmsDriver.py", line 55, in <module>
    run()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/bin/slc6_amd64_gcc530/cmsDriver.py", line 11, in run
    options = OptionsFromCommandLine()
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/python/Configuration/Applications/cmsDriverOptions.py", line 33, in OptionsFromCommandLine
    options=OptionsFromItems(sys.argv[1:])
  File "/cvmfs/cms.cern.ch/slc6_amd64_gcc530/cms/cmssw/CMSSW_8_0_24/python/Configuration/Applications/cmsDriverOptions.py", line 53, in OptionsFromItems
    possible+="\nauto:"+k+" -> "+autoCond.autoCond[k]
TypeError: cannot concatenate 'str' and 'tuple' objects
`
I could not find a way arround this problem.

I tried with my own test command:
`cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=l1Ntuple_RAW_wRECO.py -n 100 --no_output --era=Run2_2016 --data --conditions=80X_dataRun2_Prompt_v15 --filein=/store/data/Run2016H/SingleMuon/RAW-RECO/MuTau-PromptReco-v2/000/282/092/00001/8EEE6185-FB8A-E611-9E65-02163E0117FE.root --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloStage2Params_v2_2`

Before the changes from this PR, I see electrons in the emuTree. After applying the changes and compiling, I still see them. Without being able to run your command, I cannot confirm/infirm what you are seeing, though my changes yield 100% agreement w.r.t. out-of-the-box 89.12.

Please let me know how to proceed!

Cheers,
- Olivier

**Comment by rekovic** [comment]
@davignon  Just to understand, have you tried the recipe listed here https://github.com/cms-l1t-offline/cmssw/pull/446#issuecomment-274830714 ?

**Comment by davignon** [comment]
@rekovic Yes I have, and it gives me the error message.

**Comment by rekovic** [comment]
@davignon 

Sorry, there was a missing part `--conditions=` in the cmsDriver.py command above.
Here is a corrected version, working command:
`
cmsDriver.py L1TEST --conditions=auto:run2_mc -s DIGI,L1 --datatier GEN-SIM-RAW -n 5 --era Run2_2016 --mc --no_output --filein=root://eoscms//eos/cms/store/group/dpg_trigger/comm_trigger/L1Trigger/rekovic/unit-est/input//store/relval/CMSSW_7_6_0/RelValProdTTbar/GEN-SIM/76X_mcRun1_realistic_v10-v1/00000/08F44119-9C7F-E511-85C3-0025905B85A2.root --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleEMUNoEventTree --customise=L1Trigger/Configuration/customiseUtils.L1TGlobalSimDigisSummary --customise=L1Trigger/Configuration/customiseUtils.L1TAddInfoOutput
`

**Comment by davignon** [comment]
@rekovic @bundocka 

I confirm that the electrons were gone with your command (my command differed in the sense that it specified the caloStage2Params to be used).
It seems I had forgotten to adapt caloStage2Params_2016_v3_3_1_cfi.py (the default one, used in your command).
I've pushed the changes and I now see electrons again in all cases :-)

Cheers,
- Olivier

**Comment by rekovic** [comment]
cherry-picked and tagged as l1t-integration-v91.4.

**Pull request closed without merging**
