### PR TITLE
Fixes to EMTF emulator

### PR DESCRIPTION
**Pull request by abrinke1**
Retrieved tracks in high-eta region, fixed problems with pT assignment, synchronized objects between emulator and unpacker.

When I run "git diff --name-only cms-l1t-offline/l1t-integration-CMSSW_8_0_2" I see changes (which I did not make) in the log file attached.  I'm not sure whether these represent reversions to older versions, or advances to the latest commits.  Let me know if anything is out of order in the PR.  For me, everything compiles.

Cheers,
Andrew

[log.txt](https://github.com/cms-l1t-offline/cmssw/files/236170/log.txt)

### CODE REVIEW

**Comment by mulhearn** [comment]
How do you guys conflict resolve when you merge? At 763fb0d4aa755c17b30ee96780709974dd602ecc it looks to me like @mrcarver  maybe copied wholesale directories, blowing away other peoples changes, and thats why you are now seeing these unexpected diffs...  is that what happened?

I think I can clean up the mess by cherry-picking the non-merge commits.  But you guys will have to recheck the final product to see that it still behaves as you want it to.  I can run some bitwise comparisons of your version and mine as well.

**Comment by mulhearn** [comment]
I may have spoke too soon...  sorry if so.  Let me look more at this more.  I'm fairly certain I can work this.

**Comment by abrinke1** [comment]
Actually, in the log file, these two changes are understood:
DataFormats/L1TMuon/src/classes.h
DataFormats/L1TMuon/src/classes_def.xml

**Comment by mulhearn** [comment]
Pretty sure I spoke too soon ;-) sorry!  Checking..

**Comment by mulhearn** [comment]
Let's move over to #275

**Pull request closed without merging**
