### PR TITLE
EMTF station 2-3-4 track promotion in all sectors

### PR DESCRIPTION
**Pull request by abrinke1**
Firmware change made at P5 as of July 29th.

### CODE REVIEW

**Comment by jiafulow** [comment]
Hi Andrew,

The logic implemented in the firmware is 

```
case 7:   quality = (theta <= 50 ? 12 : 8);  break;
```

If you use that, there should be no need to change line 84. AND and OR are used for bit manipulation, I would prefer to keep them.

**Comment by abrinke1** [comment]
Hi Jia Fu,

If that's the case, Alex must leave out the "quality |= (mode & 3)" line for mode 7 - because what I see in the DQM is most mode 7 tracks with quality == 12, and some with quality == 11.  This is nice, actually, because no other EMTF tracks have quality == 12, so mode 7 tracks are unambiguous in the uGMT.  I'm planning to make a later update with this as a configurable switch anyway.  If you take a look at the latest FW and tell me now he gets to mode 7 --> quality 12, we can code it up that way.

Best,
Andrew

**Comment by jiafulow** [comment]
I see. I just checked again. What I said in the previous comment is wrong. Actually he just overwrites the `quality` after line 84 with 

```
// correction for fixing two dead ME1/1 chambers, according to Andrew's message from 2017-07-05
// promote mode 7 tracks to quality 12 in low theta area
if (mode == 7 && theta <= 50)  quality = 12;
```

Comment is taken from his firmware. I'll send you the link to his firmware.

**Comment by abrinke1** [comment]
@rekovic Can we pull this in - it's super simple.

**Comment by abrinke1** [comment]
Superseded by PR #604 , which makes the station 2-3-4 track promotion configurable, and dependent on FW version.

**Pull request closed without merging**
