### PR TITLE
Hadronic shower trigger emulator for Run-3

### PR DESCRIPTION
**Pull request by dildick**
#### PR description:

In Run-3 we would like to include a counter in the CSC trigger sensitive to hadronic showers. They can indicate the decay of a long-lived particle in the muon endcap system and have the potential of increasing sensitivity in physics searches by a factor 20. 

This PR introduces `CSCShowerDigi` object and producer in the trigger. They can either be "loose", "nominal", or "tight", depending on how many hits were recorded in a chamber. The `CSCShowerDigi` are produced in addition to the regular CSC trigger primitives and are sent to the EMTF. They are therefore of type `CSCDetIdCSCShowerDigiMuonDigiCollection_simCscTriggerPrimitiveDigis__`. 

The trigger data has already been upgraded to include additional bits for hadronic showers (see [DN-20-016](https://gitlab.cern.ch/tdr/notes/DN-20-016/blob/master/temp/DN-20-016_temp.pdf)). 

For the CSC->MPC->EMTF path, 4 `HMT` bits per chamber per BX have been allocated. In the EMTF sector processors we're planning a simple logic block that checks the presence of a shower (e.g. one nominal shower, or two loose showers).  For the EMTF->uGMT 3x2 bits are available per BX per trigger sector. In our current design we would use 1 or 2 bits. Those object are 
`l1t::RegionalMuonShower` and `l1t::Muon`.

Additional documentation in [DN-20-033](https://gitlab.cern.ch/tdr/notes/DN-20-033/blob/master/temp/DN-20-033_temp.pdf) and in [this presentation](https://indico.cern.ch/event/1006558/contributions/4227898/attachments/2187396/3696178/HadronicShowerTrigger_20210204.pdf).

#### PR validation:

Tested with H->2s->4b/4d samples  below
https://cmsweb.cern.ch/das/request?view=list&limit=50&instance=prod%2Fglobal&input=%2FHTo2LongLivedTo4b*%2FRun3Winter20DRPremixMiniAOD-110X_mcRun3_2021_realistic_v6-v2%2FGEN-SIM-RAW

Also tested with WF 11634.0.

```
11634.0_TTbar_14TeV+2021+TTbar_14TeV_TuneCP5_GenSim+Digi+Reco+HARVEST+ALCA Step0-PASSED Step1-PASSED Step2-PASSED Step3-PASSED Step4-PASSED  - time date Thu Feb 11 11:30:07 2021-date Thu Feb 11 10:42:32 2021; exit: 0 0 0 0 0
1 1 1 1 1 tests passed, 0 0 0 0 0 failed
```

To setup:
```
cmsrel CMSSW_11_2_0
cd CMSSW_11_2_0/src/
cmsenv
git cms-init
git cms-rebase-topic dildick:from-CMSSW_11_2_0-offline-hadronic-shower-trigger
git clone -b for-CMSSW_11_1_X-muon-shower git@github.com:gem-sw/GEMCode.git
scram b

# use input file
# then /store/mc/Run3Winter20DRPremixMiniAOD/HTo2LongLivedTo4b_MH-1000_MFF-450_CTau-100000mm_TuneCP5_14TeV_pythia8/GEN-SIM-RAW/110X_mcRun3_2021_realistic_v\
6-v2/10000/132B0128-FF59-DB4A-A3AD-AF4D8B4D21D2.root
cmsRun GEMCode/GEMValidation/test/step2_RAW2DIGI_ReL1_Run3_HST.py
```

#### if this PR is a backport please specify the original PR and why you need to backport that PR:

N/A

@tahuang1991

### CODE REVIEW

**Comment by eyigitba** [comment]
Hi @dildick , thanks a lot for this! I only went reviewed the EMTF parts for now, I'll go over the rest soon. I have a question/comment about it. Is there a reason to keep this attached to the `L1TMuonEndcapTrackProducer` (I don't remember if we discussed this before)? We can create a new producer within `L1TMuonEndCap` and keep the two producers separate. We'll need to call the two producers together whenever we're emulating EMTF of course (which will lead to some more changes), but I feel like this will keep things simpler in the code.

**Comment by dildick** [comment]
Hi @eyigitba , this is something new you bring up. @jiafulow hadn't suggested it so far. I assumed the shower producer should resided within the EMTF object producer. In principle we can separate it

**Comment by eyigitba** [comment]
I'm not opposed to leaving it in there. I also don't know if this can cause other problems (maybe @jiafulow knows better). I just thought this way we don't really have to change the structure of the EMTF track producer chain.

**Comment by dildick** [comment]
@eyigitba I think you have a good point. Cleanly separating the code will prevent unwanted mistakes in the code. I'll make an update soon.

**Comment by jiafulow** [comment]
I think Efe made a good suggestion, and I tend to agree. The problem is that there's no clear guidelines, so I don't know what's the correct way either. The opposite argument would be that each of BMTF/OMTF/EMTF only has one producer. Introducing a new producer means having to update a lot of the existing "chains" (maybe that's fine).

**Comment by dildick** [comment]
It's really not that bad. I need to update the `simDigis_cff` in `L1TMuon` and an `EventContent` configuration to get it running on MC. For data, or re-emulation a few more changes may be needed. But it's not a showstopper.

**Comment by eyigitba** [comment]
Yes we should keep this in mind and re-check data and re-emul workflows as well. In the end it doesn't sound too complicated. We just need to add `simEmtfShowers` whenever we use `simEmtfDigis` basically. However I also don't know if there are some rules such as one producer per TF.

Thanks @dildick for doing it this quickly!

**Comment by dildick** [comment]
A standard test 11634.0 results in this weird error. It does not seem related to any changes I made. 

@rekovic Do you know what is going on here?

```
----- Begin Fatal Exception 05-Mar-2021 11:11:36 CST-----------------------
An exception of category 'DictionaryNotFound' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=L1TRawToDigi label='hltGtStage2Digis'
   [2] Calling ProductRegistryHelper::addToRegistry, checking dictionaries for produced types
Exception Message:
No data dictionary found for the following classes:

  BXVector<l1t::EGamma>
  BXVector<l1t::EtSum>
  BXVector<l1t::Jet>
  BXVector<l1t::Muon>
  BXVector<l1t::Tau>
  edm::Wrapper<BXVector<l1t::EGamma> >
  edm::Wrapper<BXVector<l1t::EtSum> >
  edm::Wrapper<BXVector<l1t::Jet> >
  edm::Wrapper<BXVector<l1t::Muon> >
  edm::Wrapper<BXVector<l1t::Tau> >

Most likely each dictionary was never generated, but it may
be that it was generated in the wrong package. Please add
(or move) the specification '<class name="whatever"/>' to
the appropriate classes_def.xml file along with any other
information needed there. For example, if this class has any
transient members, you need to specify them in classes_def.xml.
Also include the class header in classes.h

A type listed above might or might not be the same as a
type declared by a producer module with the function 'produces'.
Instead it might be the type of a data member, base class,
wrapped type, or other object needed by a produced type. Below
is some additional information which lists the types declared
to be produced by a producer module that are associated with
the types whose dictionaries were not found:

  BXVector<l1t::EGamma>
  BXVector<l1t::EtSum>
  BXVector<l1t::Jet>
  BXVector<l1t::Muon>
  BXVector<l1t::Tau>

----- End Fatal Exception -------------------------------------------------
```

**Comment by dildick** [comment]
Well, WF 12434.0 seems like a better choice. That one is running

**Comment by dildick** [comment]
And here they are:
```
CSCDetIdCSCShowerDigiMuonDigiCollection_simCscTriggerPrimitiveDigis__HLT. 324.6 302
l1tRegionalMuonShowerBXVector_simEmtfShowers_EMTF_HLT. 316.4 273.4
l1tMuonShowerBXVector_simGmtShowerDigis__HLT. 296.6 256.7
```

**Comment by dildick** [comment]
I'm looking into packing the EMTF showers into the RAW data. It seems I need to extend the object with a link, so I can insert the 2 bits per shower in the right place.

**Comment by dildick** [comment]
@dinyar My last commit is a first stab at packing and unpacking the showers

**Comment by dildick** [comment]
@rekovic Do you have any comments so far?

**Comment by dildick** [comment]
My last commits also write out Anode showers (produced in the ALCT board)
```
CSCDetIdCSCShowerDigiMuonDigiCollection_simCscTriggerPrimitiveDigis_Anode_HLT. 331.6 309.2
CSCDetIdCSCShowerDigiMuonDigiCollection_simCscTriggerPrimitiveDigis__HLT. 324.6 302
l1tRegionalMuonShowerBXVector_simEmtfShowers_EMTF_HLT. 316.4 273.4
l1tMuonShowerBXVector_simGmtShowerDigis__HLT. 296.6 256.7
```

**Comment by dildick** [comment]
This PR now superseded by #899

**Pull request closed without merging**
