### PR TITLE
Jet saturation fix & caloStage2Params_2016_v3_1_cfi for new SK

### PR DESCRIPTION
**Pull request by bundocka**
- Jet emulator now saturates a jet to 0xFFFF if jet seed is saturated at 0x1FF
  - Recovers HF jet efficiency with new JEC
- New calo params: caloStage2Params_2016_v3_1_cfi
  - Updated EG iso, Tau Iso and calibration for use with new SK working point 16/16
- Added new function to L1TSettingsToCaloStage2Params_v3_1 for use with cmsDriver

### CODE REVIEW

**Comment by kreczko** [comment]
In line [173 of L1Trigger/L1TCalorimeter/src/firmware/Stage2Layer2JetAlgorithmFirmwareImp1.cc](https://github.com/cms-l1t-offline/cmssw/pull/412/files#diff-3a91229e2ba90803a101c11046824903R173):
Would it make sense to change `65535` to either `std::numeric_limits<unsigned short>::max()` or `USHRT_MAX` (from `<climits>`) for better readability?

Also, in line 575++, could you change 

``` c++
if(jetPtCorr < 0xFFFF)
  jet->setHwPt(jetPtCorr);
else
  jet->setHwPt(0xFFFF);
```

to 

``` c++
if(jetPtCorr < 0xFFFF) {
  jet->setHwPt(jetPtCorr);
} else {
  jet->setHwPt(0xFFFF);
}
```

since it is less error-prone?

**Comment by rekovic** [comment]
Merged into default branch l1t-integration-CMSSW_8_0_19,
plus caloStage2Params_2016_v3_1_cfi conditions are turned on in hackConditions.

This i tagged as <pre>l1t-integration-v86.0</pre>

@bundocka, @davignon  This is of interest to you.

**Comment by bundocka** [comment]
Hi Vladmir,

May I suggest that we only update the caloParams in the hackConditions 
once that parameter/calibration set has been put online? Otherwise we end 
up with the problem where people run ntuples with the default offline config 
that is different to the online config. 

Cheers,
Aaron

**Comment by bundocka** [comment]
@rekovic

Not sure if this got through, added tag

May I suggest that we only update the caloParams in the hackConditions 
once that parameter/calibration set has been put online? Otherwise we end 
up with the problem where people run ntuples with the default offline config 
that is different to the online config. 

Cheers,
Aaron

**Comment by fwyzard** [comment]
We do want the new Calo calibrations in the 8.0.x release for MC production
*now".

If L1 needs to have different settings for MC and for other use cases, like
making the ntuples for the validation of data, I guess it should just be a
matter of using the right settings in the private jobs, either as cnsDriver
options or settings whatever is needed in the python files. If you do need
to have different settings in git, I would advice to keep different
branches for MC and for the ntuples.

Eventually, all settings and calibrations for real data should be migrated
to the EventSetup and O2O.

Ciao,
.Andrea

**Comment by rekovic** [comment]
@bundocka The latest tag is documented in [twiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideL1TStage2Instructions).  Use of customisation commands has been constantly in use in L1 ntuples production by @bortigno and @apana, and the latest one is documented there as well.

**Comment by bundocka** [comment]
Ok, sure, I’ll keep an eye on that twiki and make sure it is kept up to date with what is online, such that anyone 
wanting to emulate the calo trigger uses the correct settings.

The reason I suggested this is that a month or so ago Len made a set of ntuples that used the default calo config 
in hackConditions, which Vladmir had changed from the online params v2_2, to a test config v3_0_inconsistent, that 
should never have been used for anything other than deriving Layer 2 calibrations, and this led to some confusion. 

As long as people are aware that they may need to use the customisation and the twiki is kept up to date with what 
is online then this of course won’t be a problem.

Cheers,
Aaron

**Pull request closed without merging**
