### PR TITLE
Fix mva ntuple variable

### PR DESCRIPTION
**Pull request by cgsavard**
#### PR description:

The ntuple was filling the track mva variable with -99 as a default until the mva variable was ready to be used. I have now replaced the -99 to the actual mva variable. This is a very minor change.

#### PR validation:

I have checked that this works correctly when running the ntuple. I also ran the basic formatting checks after the changes were made.

### CODE REVIEW

**Comment by aperloff** [comment]
Shouldn't [this line](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TrackTrigger/interface/TTTrack.h#L446) also be:
```c++
double mvaQuality = theTrkMVA1_;
```
which means the [function declaration for `setTrackWord`](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h#L231-L241) needs to be:
```c++
  void setTrackWord(unsigned int valid,
                    const GlobalVector& momentum,
                    const GlobalPoint& POCA,
                    double rInv,
                    double chi2RPhi,  // would be total chisq if chi2Z is zero
                    double chi2RZ,
                    double bendChi2,
                    unsigned int hitPattern,
                    double mvaQuality,
                    unsigned int mvaOther,
                    unsigned int sector);
```
Then the [implementation](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TrackTrigger/src/TTTrack_TrackWord.cc#L88) needs to change to:
```c++
  qualityMVA_t mvaQuality_ = getBin(mvaQuality, mvaQualityBins);
```
with the `mvaQualityBins` defined somewhere around [here](https://github.com/cms-l1t-offline/cmssw/blob/phase2-l1t-integration-1230pre4/DataFormats/L1TrackTrigger/interface/TTTrack_TrackWord.h#L99-L105).

This will make it so that the TTTrack_TrackWord (emulation) also has the mvaQuality value set, not just the floating point (simulation) track.

**Comment by cgsavard** [comment]
Eventually this will need to be done, yes, but the bins for the mva have not yet been set so this is still just a temporary placeholder until that is done.

**Comment by aperloff** [comment]
Okay, then let's merge this in for now and handle the other changes later, in a separate PR.

**Comment by epalencia** [comment]
Tagged as **l1t-phase2-v3.4.47**.

**Pull request merged**
