### PR TITLE
Update & cleanup correlator layer 1 code

### PR DESCRIPTION
**Pull request by gpetruc**
* Updates the correlator layer 1 emulation in l1ctLayer1_cff:
   * update HGCal cluster ID tune (@VourMa) & EM energy intepretation (@schhibra)
   * use the correct input multiplicities for the different input objects (@gpetruc, @drankincms), with ideal regionizer (full regionizer emulator is also included, but not active by default)
   * update the e/gamma emulator (@cerminar)
   * switch to the PV emulator as input
 * Remove stuff in the old layer 1 emulator that was not running in production (old bitwise emulators, old dump files)
 * Add the seeded cone jets emulator (@thesps)

### CODE REVIEW

**Comment by gpetruc** [comment]
Hi @rekovic @cecilecaillol,

The PR is mostly ready, the only thing that still needs updating is the cuts on the multiplicity of input objects used in e/&gamma; reconstruction in the barrel (@cerminar is running some tests).

While most of the changes are internal to the L1Trigger/Phase2ParticleFlow package, I made a few changes to the SimL1Emulator file:
 * I added the new correlator emulators to the task, though I did not change the consumer modules (e.g. jets, met) to use them
 * As the new emulator uses the emulated vertex as input, I added the Vertex emulator to the sequence, and the L1GTTInputProducer needed to produce inputs for it
 * I fixed the InputTag for the L1TrackerEtMiss module, matching what was suggested in https://github.com/cms-l1t-offline/cmssw/pull/898#discussion_r633667786
 * I uncommented the tkGlobalMuons in the L1TkObjectProducers_cff because SimL1Emulator now uses them (maybe that was missed in #904 ? )

**Comment by rekovic** [comment]
@gpetruc  Thanks!.  Please let us know when ready.  

> 
* I added the new correlator emulators to the task, though I did not change the consumer modules (e.g. jets, met) to use them
As the new emulator uses the emulated vertex as input, I added the Vertex emulator to the sequence, and the L1GTTInputProducer needed to produce inputs for it
* I fixed the InputTag for the L1TrackerEtMiss module, matching what was suggested in #898 (comment)
* I uncommented the tkGlobalMuons in the L1TkObjectProducers_cff because SimL1Emulator now uses them (maybe that was missed in #904 ? )
>

This needs a bit of arrangement.  I prefer to adjust the Phase-2 sequence: (add Vertex emulator to the sequence and the L1GTT input producer, uncomment tkGlobalMuons in the L1TkObjectProducers_cff) in the integration branch before I merge your PR (in case of need for revert).  So you will see a change in your PR by the changes underneath so you might need to do a final change of your PR when ready with possible update in e/gamma barrel that you mentioned.

**Comment by gpetruc** [comment]
Hi @rekovic , from our side the PR is ready. 
If you prefer to do the other changes in the integration branch independently, go ahead and then let me know when done so I can rebase this PR on top of that. BTW, if you do so, perhaps you could also scram b code-format & commit, as there's code from some other PRs that didn't pass that step and got integrated.
Giovanni

**Comment by rekovic** [comment]
hi @gpetruc . This PR is merged and tagged as  l1t-phase2-v3.3.30

**Pull request merged**
