### PR TITLE
uGT Code for MinBias Triggers

### PR DESCRIPTION
**Pull request by blwiner**
These are the changes for the MinBias Triggers for the uGT.  

Important Notes:
- This change depends on new enumerations in the external utm library
- There are changes to DataFormats

### CODE REVIEW

**Comment by mulhearn** [comment]
Data formats changes that don't require a new class version, because they don't change class data, only enums or accessors, are no problem.  So these DataFormat changes are no problem!  Good!

**Comment by mulhearn** [comment]
That new UTM library is a bit of a complication.  Can we get this code to work in some crippled fashion, with enum defined ourselves, using old library, for merging into the integration branch?  I guess as is this won't even compile unless you update UTM library manually?

**Comment by mulhearn** [comment]
I guess these are our guys:

```
            condition.getType() == esConditionType::MinBiasHFP0 ||
            condition.getType() == esConditionType::MinBiasHFM0 ||
            condition.getType() == esConditionType::MinBiasHFP1 ||
            condition.getType() == esConditionType::MinBiasHFM1 )
```

So I am proposing:

```
   //LOCAL enum definition until UTM library is updated to version ?
   enum {LOCAL_MinBiasHFPO=?, LOCAL_MinBiasHFMO=?,...}
   //...
            condition.getType() == LOCAL_MinBiasHFP0 ||
   //...
```

**Comment by mulhearn** [comment]
Otherwise, this has to go in directly to CMSSW when UTM library is in a nightly.  Dev branch will be on 807 for awhile.

**Comment by fwyzard** [comment]
One possibility would be, once the new UTM library is available in an integration build, to add to the instructions for the integration branch something like

```
scram setup /cvmfs/cms.cern.ch/$SCRAM_ARCH/cms/cmssw-tool-conf/33.0-giojec4/tools/selected/utm.xml
cmsenv
```

to pick the new version.

**Comment by mulhearn** [comment]
Ah, did not know that trick.  But will that be available in places where IBs are not available?  Some of our developers use their own Tier3s...

**Comment by fwyzard** [comment]
Well, you do need to have access to the library somehow.

If the site install releases locally, they would need to install a recent cmssw-tool-conf package (which would bring the new utm library as a dependency).

If the site uses CVMFS, the IBs and libraries should automatically be available.

**Comment by blwiner** [comment]
@mulhearn: I see how this would allow us to get the uGT code to compile
without the update.  However, it seems to me that the utm needs to know how
to parse the xml of the L1Menu with MinBias triggers.  So I don't know that
this local definition helps.  Perhaps @tmatsush can comment.

On Thu, May 5, 2016 at 5:30 PM, mulhearn notifications@github.com wrote:

> I guess these are our guys:
> 
> ```
>         condition.getType() == esConditionType::MinBiasHFP0 ||
>         condition.getType() == esConditionType::MinBiasHFM0 ||
>         condition.getType() == esConditionType::MinBiasHFP1 ||
>         condition.getType() == esConditionType::MinBiasHFM1 )
> ```
> 
> So I am proposing:
> 
>    //LOCAL enum definition until UTM library is updated to version ?
>    enum {LOCAL_MinBiasHFPO=?, LOCAL_MinBiasHFMO=?,...}
>    //...
>             condition.getType() == LOCAL_MinBiasHFP0 ||
>    //...
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/cms-l1t-offline/cmssw/pull/295#issuecomment-217285894

## 

---

B. Winer

**Comment by tmatsush** [comment]
utm update is needed to parse menu with MinBias triggers.

**Comment by mulhearn** [comment]
@tmatsush:  just to be clear: are you saying it will e.g. crash if 807 version of UTM encounters minbias term in menu, or it will just not produce minbias part of trigger correctly?

If this is not case already, perhaps a future version of UTM could issue a warning and then set a condition and/or algorithm to just "false" if it encounters a new feature which it does not understand in a menu.  That way we can roll out new code even before UTM is updated, and even use new menus getting all but the new features.  Or maybe this is impossible to arrange....

In any event, I think this means my hack can work in our development branch, but we just cannot use the new menu in 807.

**Comment by tmatsush** [comment]
@mulhearn 
UTM will throw std::runtime_error when the library encounters unknown token in a menu.
It will be possible to pass "unknown" to downstream but then this should be handled by emulator in proper way.

**Comment by mulhearn** [comment]
Well, even if we catch "unknown", I guess there's nothing we can do, because we pass the entire menu, and there's no way for us to remove just the problematic part of menu...

**Comment by mulhearn** [comment]
This compiles now under a recent IB with new UTM, so I think we can now just go ahead with direct integration into CMSSW route, including other changes from Calo.

**Comment by fwyzard** [comment]
@mulhearn @rekovic can you make the PRs for CMSSW 8.0.x and 8.1.x ASAP ?

In order to use the new seeds during the van der Meer scans next week, Run Coordination is asking to  e able to test them online by this Friday - which means we will need to ask for a new CMSSW release with these changes tomorrow or Thursday at the latest.

.A

**Comment by mulhearn** [comment]
CMSSW PR tracked at #314.

**Pull request closed without merging**
