### PR TITLE
New twinmux emulator

### PR DESCRIPTION
**Pull request by gkaratha**
Taking the comments into account:
1) Push in two steps so we have history
2) Change directory to L1TTwinMux
3) Remove unnecessary files (like root)
4) Change two BMTF files in test directory to include the new TM emulator
No hard code or logic changed. Only paths from L1TwinMux -> L1TTwinMux

### CODE REVIEW

**Comment by thomreis** [comment]
Thanks @gkaratha for splitting this up. However, it does not look as if it worked as intended. The diff still shows only entire files as different.

**Comment by thomreis** [comment]
I believe you should take the files out of the TwinMux_v1 directory and place them in the interface and src directories, respectively, before changing them. Now it looks as if you have duplicated some files.

**Comment by gkaratha** [comment]
Hi @thomreis , Thanks for the comment. Indeed this is propably due to different structure of the directory. Perhaps we should do it in three steps? (1) move files 2) change structure 3) replace them)

**Comment by gkaratha** [comment]
@thomreis Ok seems that we wrote it at the same time. Ok I will try that

**Comment by thomreis** [comment]
@gkaratha I think this can be closed.

**Comment by rekovic** [comment]
this is superseded by https://github.com/cms-l1t-offline/cmssw/pull/589

**Pull request closed without merging**
