### PR TITLE
Disentangle CaloParams for Stage1 and Stage2 Trigger Upgrade

### PR DESCRIPTION
**Pull request by nsmith-**
Introduces new DataRecord L1TCaloStage2ParamsRcd
Bonus: Fixup Stage 1 in `customizeReEmul.py`
(re: https://hypernews.cern.ch/HyperNews/CMS/get/L1TrigEmulator/474/1.html)

Compares ok against `l1t-tsg-v6-cand-for-80X`

### CODE REVIEW

**Comment by mulhearn** [comment]
I'll put this into o2o dev branch today.

**Comment by mulhearn** [comment]
(new o2o 807 branch)

**Comment by mulhearn** [comment]
@rekovic can you cherry-pick 1669add into the integration branch?  Its harmless and useful to people that want to re-emulate stage1.

**Comment by mulhearn** [comment]
```
52442f1 is in the o2o dev branch at v4.0.
```

**Comment by rekovic** [comment]
Cherry-picked 1669add into the integration branch.   Tagged as l1t-integration-v49.1

**Pull request closed without merging**
